import test from 'node:test';import assert from 'node:assert/strict';import {database} from './d1-adapter.mjs';import {handleAttendance,guardAttendance} from '../worker-v2/attendance.js';import {attendanceReport,kstDay} from '../worker-v2/attendance-time.js';import {handleSop} from '../worker-v2/sop.js';
test('database rejects a join after checkout, even if a preflight validation raced',async()=>{const {call,DB}=setup(),r=(await call('checkin',{name:'并发甲',agency:'가온'})).record;await call('checkout',{id:r.id});DB.raw.exec("INSERT INTO v2_ops_jobs(id,job_type,biz_class,status) VALUES('RACE','bulk_op','bulk','working')");assert.throws(()=>DB.raw.prepare('INSERT INTO v2_ops_job_workers(id,job_id,worker_id,joined_at) VALUES(?,?,?,?)').run('RACEW','RACE',r.badgeId,new Date().toISOString()),/Attendance required/);});
test('verified attendance correction closes only the affected personal segment and logs its evidence',async()=>{const {call,DB}=setup(),r=(await call('checkin',{name:'补卡甲',agency:'가온'})).record;DB.raw.exec("INSERT INTO v2_ops_jobs(id,job_type,biz_class,status) VALUES('CORRECT','bulk_op','bulk','working')");DB.raw.prepare('INSERT INTO v2_ops_job_workers(id,job_id,worker_id,joined_at) VALUES(?,?,?,?)').run('CORRECTW','CORRECT',r.badgeId,r.inAt);const end=new Date().toISOString();const fixed=await call('correct',{id:r.id,version:r.version,inAt:r.inAt,outAt:end,reason:'负责人核实离场时间'});assert.equal(fixed.record.outAt,end);assert.equal(DB.raw.prepare("SELECT left_at FROM v2_ops_job_workers WHERE id='CORRECTW'").get().left_at,end);assert.equal(DB.raw.prepare("SELECT status FROM v2_ops_jobs WHERE id='CORRECT'").get().status,'working');const report=await call('summary');assert.equal(report.items[0].events.at(-1).after.corrected_segments.length,1);});
function setup(){const DB=database(),env={DB,SOP_ENVIRONMENT:'staging',SOP_ATTENDANCE_ENABLED:'true',SOP_UPGRADE_ENABLED:'true',SOP_REQUEST_USER:{id:'M',name:'测试负责人',role:'manager'}};const call=(a,v={})=>handleAttendance({action:'sop_attendance_'+a,client_req_id:crypto.randomUUID(),...v},env);return {DB,env,call};}
test('lost badge name search lists same names and preserves original attendance on reprint',async()=>{
 const {call,DB,env}=setup();const a=(await call('checkin',{name:'同名甲',agency:'가온'})).record,b=(await call('checkin',{name:'同名甲',agency:'포레인',confirm_distinct_person:true,reason:'确认不同人员'})).record;
 const out=(await call('checkout',{id:b.id})).record;env.SOP_REQUEST_USER.role='kiosk';
 const found=await call('search',{name:'  同名甲  '});assert.equal(found.items.length,2);assert.deepEqual(new Set(found.items.map(x=>x.record.id)),new Set([a.id,b.id]));
 const chosen=(await call('search',{name:'同名甲',agency:'포레인'})).items;assert.equal(chosen.length,1);assert.equal(chosen[0].record.outAt,out.outAt);
 const printed=await call('print',{id:chosen[0].record.id});assert.equal(printed.record.badgeId,b.badgeId);assert.equal(printed.record.inAt,b.inAt);assert.equal(printed.record.outAt,out.outAt);
 assert.equal(DB.raw.prepare('SELECT COUNT(*) n FROM ck_attendance_days').get().n,2);assert.equal(DB.raw.prepare('SELECT COUNT(*) n FROM ck_attendance_people').get().n,2);assert.equal(DB.raw.prepare('SELECT COUNT(*) n FROM ck_attendance_prints').get().n,1);
 assert.equal((await call('search',{name:'同名'})).items.length,0);await assert.rejects(call('search',{name:''}),/姓名/);await assert.rejects(call('search',{name:'同名甲',agency:'任意'}),/公司/);env.SOP_REQUEST_USER=null;await assert.rejects(call('search',{name:'同名甲'}),/权限/);
});
test('name recovery includes fixed badges before checkin, filters expired daily and disabled badges, normalizes Korean',async()=>{
 const {call,DB}=setup();const fixed=(await call('register',{name:'가상김',agency:'가온'})).person;
 let found=await call('search',{name:'가상김'.normalize('NFD')});assert.equal(found.items[0].person.badgeId,fixed.badgeId);assert.equal(found.items[0].record,null);assert.equal(DB.raw.prepare('SELECT COUNT(*) n FROM ck_attendance_days').get().n,0);
 const today=(await call('checkin',{badge:fixed.badgeId,agency:'포레인'})).record;assert.equal((await call('search',{name:'가상김',agency:'가온'})).items.length,0);found=await call('search',{name:'가상김',agency:'포레인'});assert.equal(found.items.length,1);assert.equal(found.items[0].record.id,today.id);
 const old=(await call('checkin',{name:'旧临时',agency:'가온'})).record;DB.raw.prepare("UPDATE ck_attendance_days SET day='2000-01-01' WHERE id=?").run(old.id);assert.equal((await call('search',{name:'旧临时'})).items.length,0);
 DB.raw.prepare('UPDATE ck_attendance_people SET enabled=0 WHERE id=?').run(fixed.id);assert.equal((await call('search',{name:'가상김'})).items.length,0);
});
test('checkin retry, company correction and reprint preserve identity and arrival',async()=>{const {call,DB}=setup(),payload={name:'测试甲',agency:'가온',client_req_id:crypto.randomUUID()};const first=await call('checkin',payload);assert.equal(first.record.badgeType,'daily');assert.deepEqual(await call('checkin',payload),first);const duplicate=await call('checkin',{name:'测试甲',agency:'포레인'});assert.equal(duplicate.identityRequired,true);assert.equal(duplicate.record,null);const changed=await call('company',{id:first.record.id,version:1,agency:'포레인'});assert.equal(changed.record.inAt,first.record.inAt);assert.equal(changed.record.badgeId,first.record.badgeId);await call('print',{id:first.record.id});assert.equal(DB.raw.prepare('SELECT COUNT(*) n FROM ck_attendance_days').get().n,1);await assert.rejects(call('company',{id:first.record.id,version:1,agency:'가온'}),/更新/);});
test('permanent badge is reusable but requires a daily record; validation and viewer permissions',async()=>{const {call,env}=setup();const p=await call('register',{name:'테스트',agency:'가온'});assert.match(p.person.badgeId,/^DAF-/);const guard=await guardAttendance({action:'sop_task_dispatch',workers:[{id:p.person.badgeId}]},env);assert.match(guard,/签到/);const day=await call('checkin',{badge:p.person.badgeId,agency:'포레인'});assert.equal(day.record.badgeType,'permanent');assert.equal((await call('lookup',{badge:p.person.badgeId+'|테스트'})).record.id,day.record.id);env.SOP_REQUEST_USER.role='viewer';await assert.rejects(call('checkout',{badge:p.person.badgeId}),/权限/);await assert.rejects(call('register',{name:'越权',agency:'가온'}),/权限/);assert.equal((await call('summary')).items.length,1);env.SOP_ENVIRONMENT='production';assert.equal((await call('summary')).ok,false);});
test('personal rest and checkout leave the team task running and block off-duty starts',async()=>{const {call,DB,env}=setup();const a=(await call('checkin',{name:'甲',agency:'가온'})).record,b=(await call('checkin',{name:'乙',agency:'포레인'})).record;const sql=DB.raw;sql.prepare("INSERT INTO v2_ops_jobs(id,job_type,biz_class,status,active_worker_count) VALUES('J','bulk_op','bulk','working',2)").run();for(const r of [a,b])sql.prepare('INSERT INTO v2_ops_job_workers(id,job_id,worker_id,worker_name,joined_at) VALUES(?,?,?,?,?)').run(r.id,'J',r.badgeId,r.name,r.inAt);
 await call('break_start',{id:a.id});assert.equal(sql.prepare("SELECT COUNT(*) n FROM v2_ops_job_workers WHERE left_at='' ").get().n,1);assert.match(await guardAttendance({action:'sop_task_dispatch',workers:[{id:a.badgeId}]},env),/休息/);const resumed=await call('break_end',{id:a.id});assert.deepEqual(resumed.resumedJobs,['J']);const out=await call('checkout',{badge:a.badgeId});assert.equal(out.needsReview,true);assert.equal(sql.prepare("SELECT status FROM v2_ops_jobs WHERE id='J'").get().status,'working');assert.equal(sql.prepare("SELECT active_worker_count n FROM v2_ops_jobs WHERE id='J'").get().n,1);assert.equal(sql.prepare("SELECT COUNT(*) n FROM v2_ops_job_workers WHERE worker_id=? AND left_at=''").get(b.badgeId).n,1);assert.match(await guardAttendance({action:'sop_task_dispatch',workers:[{id:a.badgeId}]},env),/签退/);assert.equal((await call('checkout',{badge:a.badgeId})).record.outAt,out.record.outAt);const summary=await call('summary');assert.equal(summary.items.length,2);assert.equal(summary.items.find(x=>x.record.id===a.id).breaks.length,1);});
test('each worker receives actual departmental minutes without dividing by team size; overlaps separated',()=>{const r={badgeId:'DA-X',day:'2026-09-21',inAt:'2026-09-21T08:00+09:00',outAt:'2026-09-21T17:00+09:00',breaks:[{start:'2026-09-21T12:00+09:00',end:'2026-09-21T13:00+09:00'}]},segments=[['bulk','08:00','12:00'],['direct_ship','13:00','15:00'],['import','14:30','17:00']].map(([department,a,b])=>({badgeId:r.badgeId,department,start:'2026-09-21T'+a+'+09:00',end:'2026-09-21T'+b+'+09:00'}));const v=attendanceReport(r,segments,'2026-09-21T18:00+09:00');assert.equal(v.presence,540);assert.equal(v.bulk,240);assert.equal(v.direct_ship,90);assert.equal(v.import,120);assert.equal(v.rest,60);assert.equal(v.conflict,30);assert.equal(v.unassigned,0);assert.equal(v.presence,v.bulk+v.direct_ship+v.import+v.rest+v.conflict);});
test('stale segments cannot accumulate into a new day and rest is never automatic',async()=>{const {call,DB}=setup();const r=(await call('checkin',{name:'旧任务甲',agency:'가온'})).record;DB.raw.exec("INSERT INTO v2_ops_jobs(id,job_type,biz_class,status) VALUES('OLD','bulk_op','bulk','working')");DB.raw.prepare("INSERT INTO v2_ops_job_workers(id,job_id,worker_id,joined_at,left_at) VALUES(?,?,?,?,'legacy')").run('W','OLD',r.badgeId,'2026-01-01T00:00:00Z');DB.raw.exec("UPDATE v2_ops_job_workers SET left_at='' WHERE id='W'");const s=await call('summary');assert.equal(s.items[0].totals.bulk,0);assert.equal(s.items[0].totals.rest,0);await call('checkout',{id:r.id});assert.equal(DB.raw.prepare("SELECT minutes_worked n FROM v2_ops_job_workers WHERE id='W'").get().n,0);});
test('dispatch and single-step review are atomic and idempotent, with all outputs retained',async()=>{const {env,DB}=setup();const sop=(action,data={})=>handleSop({action,client_req_id:crypto.randomUUID(),...data},env);const n=await sop('sop_need_create',{department:'bulk',title:'打托',customer:'虚拟C',instructions:'1-15箱打托',owner:'负责人'});assert.equal(n.ok,true,n.error);const req={need_id:n.id,department:'bulk',title:'打托',job_type:'bulk_op',workers:[{id:'TEST-A',name:'甲'},{id:'TEST-B',name:'乙'}],lead_id:'TEST-A',estimated_minutes:30,client_req_id:crypto.randomUUID()};const task=await sop('sop_task_dispatch',req);assert.equal(task.ok,true,task.error);assert.deepEqual(await sop('sop_task_dispatch',req),task);const view=await sop('sop_field_resolve',{code:'CKWORK|'+n.id+'|1'});assert.equal(view.task.status,'working');assert.equal(view.segments.length,2);const finish={id:task.id,revision:1,client_req_id:crypto.randomUUID(),decision:'pass',reason:'现场核对通过',result:{quantity:15,unit:'箱',description:'已打托',location:'A1',pallet_count:1,repaired_box_count:2,used_forklift:true}};const result=await sop('sop_task_complete_review',finish);assert.equal(result.ok,true,result.error);assert.deepEqual(await sop('sop_task_complete_review',finish),result);const final=await sop('sop_field_resolve',{code:task.id});assert.equal(final.task.status,'completed');assert.equal(final.task.result.repaired_box_count,2);assert.equal(final.need.status,'waiting_customer');assert.equal(DB.raw.prepare('SELECT COUNT(*) n FROM v2_ops_job_results').get().n,1);assert.equal(DB.raw.prepare("SELECT COUNT(*) n FROM v2_ops_job_workers WHERE left_at=''").get().n,0);});
test('failed review cannot partially close task or duplicate result',async()=>{const {env,DB}=setup(),sop=(action,data={})=>handleSop({action,client_req_id:crypto.randomUUID(),...data},env);const t=await sop('sop_task_create',{department:'bulk',title:'测试',job_type:'bulk_op',workers:[{id:'A',name:'甲'}],lead_id:'A',estimated_minutes:1});await sop('sop_task_start',{id:t.id,revision:1});const r=await sop('sop_task_complete_review',{id:t.id,revision:2,decision:'pass',reason:'',result:{quantity:1,unit:'箱',description:'完成',location:'A'}});assert.equal(r.ok,false);assert.equal(DB.raw.prepare("SELECT status FROM v2_ops_jobs WHERE id=?").get(t.id).status,'working');assert.equal(DB.raw.prepare('SELECT COUNT(*) n FROM v2_ops_job_results').get().n,0);});
