import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
if(!process.env.CK_JSDOM_MODULE)throw Error('CK_JSDOM_MODULE is required');
const mod=await import(process.env.CK_JSDOM_MODULE),{JSDOM}=mod.default||mod,flush=()=>new Promise(r=>setImmediate(r));
async function setup(t,{defer=false,reject='',unsupported=false,employee=false}={}){
 const dom=new JSDOM(fs.readFileSync(new URL('../attendance/index.html',import.meta.url),'utf8'),{url:'https://fixture.test/attendance/',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;t.after(()=>w.close());const calls=[],scanners=[];let checkoutResolve=null,hold=false;
 Object.defineProperty(w,'isSecureContext',{value:true});Object.defineProperty(w.navigator,'mediaDevices',{value:unsupported?undefined:{getUserMedia(){throw Error('Use mocked scanner only');}}});
 w.Html5Qrcode=class{constructor(id){this.id=id;this.live=false;this.stops=0;scanners.push(this);}start(camera,options,decoded){this.camera=camera;this.options=options;this.decoded=decoded;return new Promise((resolve,fail)=>{this.resolve=()=>{this.live=true;resolve();};this.reject=fail;if(reject)fail(Object.assign(Error(reject),{name:reject}));else if(!defer)this.resolve();});}stop(){this.stops++;if(!this.live)throw Error('not running');this.live=false;return Promise.resolve();}clear(){this.cleared=true;}};
 w.CKSession={ready:Promise.resolve(),user:{role:'kiosk'},request:async(action,b={})=>{calls.push({action,b});if(action==='sop_attendance_config')return {agencies:['가온'],asOf:new Date().toISOString()};if(action==='sop_attendance_employee_search')return {items:[{badgeId:'EMP-QA01',name:'登记姓名',employeeNo:'QA01',department:'bulk'}]};const r={record:{id:'D',badgeId:b.badge||'DA-TEST',name:'登记姓名',agency:'가온',inAt:new Date().toISOString(),outAt:action.endsWith('checkout')?new Date().toISOString():'',department:'bulk'}};if(hold&&action.endsWith('checkout'))return new Promise(resolve=>checkoutResolve=()=>resolve(r));return r;}};
 w.eval(fs.readFileSync(new URL('../shared/attendance-ui.js',import.meta.url),'utf8'));w.eval(fs.readFileSync(new URL('../shared/employee-attendance.js',import.meta.url),'utf8'));await w.CKAttendanceKiosk();await w.CKEmployee.kiosk();if(employee)w.document.querySelector('[data-kind=employee]').click();else w.document.getElementById('tab-out').click();
 const host=()=>w.document.querySelector(employee?'.ck-employee-terminal':'#terminal-content'),start=()=>host().querySelector('[data-camera-start]').click(),emit=(value,index=scanners.length-1)=>scanners[index].decoded(value),submit=()=>host().querySelector('form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 return {w,calls,scanners,host,start,emit,submit,hold(){hold=true;},resolveCheckout(){checkoutResolve();}};
}
test('daily camera fills canonical ID once, preserves explicit confirmation, and concurrent Enter/confirm submits once',async t=>{const s=await setup(t);s.start();await flush();assert.equal(s.scanners[0].camera.facingMode,'environment');const before=s.calls.length;const a=s.emit('DA-20261008-TEST|不要使用二维码姓名'),b=s.emit('DA-OTHER|另一人');await Promise.all([a,b]);assert.equal(s.calls.length,before);assert.equal(s.w.document.getElementById('code').value,'DA-20261008-TEST');assert.equal(s.scanners[0].live,false);s.hold();s.submit();s.submit();assert.equal(s.calls.filter(c=>c.action.endsWith('checkout')).length,1);s.resolveCheckout();await flush();assert.match(s.host().textContent,/登记姓名/);assert.equal(s.calls.find(c=>c.action.endsWith('checkout')).b.badge,'DA-20261008-TEST');});
test('employee in and out camera share existing search and punch only after explicit confirmation',async t=>{const s=await setup(t,{employee:true});for(const mode of ['in','out']){if(mode==='out'){s.host().querySelector('[data-next]').click();s.host().querySelector('[data-out]').click();}s.start();await flush();const before=s.calls.length;await s.emit('EMP-QA01|任意二维码姓名');assert.equal(s.calls.length,before);assert.equal(s.host().querySelector('input').value,'EMP-QA01');s.submit();await flush();assert.match(s.host().textContent,mode==='in'?/已签到/:/已下班/);}assert.equal(s.calls.filter(c=>c.action.endsWith('checkin')).length,1);assert.equal(s.calls.filter(c=>c.action.endsWith('checkout')).length,1);});
test('close while permission/start is pending stops a late camera and ignores late decoded frames',async t=>{const s=await setup(t,{defer:true});s.start();const scanner=s.scanners[0];s.host().querySelector('[data-camera-close]').click();await s.emit('DA-LATE|old');assert.equal(s.w.document.getElementById('code').value,'');scanner.resolve();await flush();await flush();assert.equal(scanner.live,false);assert.ok(scanner.stops>=1);assert.equal(s.calls.filter(c=>c.action.endsWith('checkout')).length,0);});
test('daily to employee switch stops camera; a stale callback cannot fill employee input',async t=>{const s=await setup(t);s.start();await flush();s.w.document.querySelector('[data-kind=employee]').click();await flush();await s.emit('DA-OLD');assert.equal(s.w.document.querySelector('#employee-term').value,'');assert.equal(s.scanners[0].live,false);});
test('up/down mode replacement and pagehide invalidate callbacks and release camera',async t=>{const s=await setup(t,{employee:true});s.start();await flush();s.host().querySelector('[data-out]').click();await flush();await s.emit('EMP-QA01');assert.equal(s.host().querySelector('input').value,'');assert.equal(s.scanners[0].live,false);s.start();await flush();s.w.dispatchEvent(new s.w.Event('pagehide'));await flush();assert.equal(s.scanners[1].live,false);});
test('wrong badge family is rejected without writes and manual entry stays usable',async t=>{const s=await setup(t,{employee:true});s.start();await flush();await s.emit('DA-OTHER');assert.match(s.host().querySelector('[data-camera-status]').textContent,/EMP/);assert.equal(s.host().querySelector('input').value,'');assert.equal(s.calls.some(c=>c.action.endsWith('checkin')),false);s.host().querySelector('input').value='EMP-QA01';s.submit();await flush();assert.equal(s.scanners[0].live,false);assert.equal(s.calls.filter(c=>c.action.endsWith('checkin')).length,1);});
for(const name of ['NotAllowedError','NotFoundError','NotReadableError'])test('camera '+name+' explains manual fallback without blocking form',async t=>{const s=await setup(t,{reject:name});s.start();await flush();assert.match(s.host().querySelector('[data-camera-status]').textContent,/输入工牌/);assert.equal(s.host().querySelector('[data-camera-start]').disabled,false);s.w.document.getElementById('code').value='DA-MANUAL';s.submit();await flush();assert.equal(s.calls.filter(c=>c.action.endsWith('checkout')).length,1);});
test('unsupported browser never requests a camera and keeps manual fallback',async t=>{const s=await setup(t,{unsupported:true});s.start();assert.equal(s.scanners.length,0);assert.match(s.host().querySelector('[data-camera-status]').textContent,/不支持/);assert.equal(s.host().querySelector('input').disabled,false);});
test('duplicate open clicks use one camera session',async t=>{const s=await setup(t,{defer:true});s.start();s.start();assert.equal(s.scanners.length,1);s.scanners[0].resolve();await flush();s.host().querySelector('[data-camera-close]').click();await flush();assert.equal(s.scanners[0].live,false);});
test('old checkout response cannot replace a different visible attendance form',async t=>{const s=await setup(t);s.hold();s.w.document.getElementById('code').value='DA-OLD';s.submit();s.w.document.getElementById('tab-in').click();await flush();s.resolveCheckout();await flush();assert.ok(s.w.document.getElementById('name'));assert.doesNotMatch(s.host().textContent,/已下班/);});
