import test from 'node:test';import assert from 'node:assert/strict';
import {database} from './d1-adapter.mjs';import {cargoExecution} from '../worker-v2/cargo-execution.js';import {handleSop} from '../worker-v2/sop.js';
import {cargoFixture as fixture} from './cargo-fixture.mjs';

test('partial completion and batch review preserve one real running task and no duplicated result or labor rows',async()=>{const s=fixture();for(let i=0;i<5;i++)await s.call('sop_cargo_group_complete',{group_id:'G'+i,quantity:5,unit:'箱'});await s.call('sop_cargo_group_review',{group_ids:['G0','G1','G2','G3','G4'],decision:'pass',reason:'核对25箱'});assert.equal(s.state().cargo_groups.groups[5].current_output_id,undefined);assert.equal(s.DB.raw.prepare("SELECT status FROM v2_ops_jobs WHERE id='T'").get().status,'working');assert.equal(s.DB.raw.prepare("SELECT COUNT(*) n FROM v2_ops_job_workers WHERE left_at=''").get().n,1);assert.equal(s.DB.raw.prepare('SELECT COUNT(*) n FROM v2_ops_job_results').get().n,0);await assert.rejects(()=>s.call('sop_cargo_job_finish',{reason:'不应收尾'}),/未审核/);});
test('six input boxes become explicit two pallets; final metrics recorded once for the real job',async()=>{const s=fixture();for(let i=0;i<6;i++)await s.call('sop_cargo_group_complete',{group_id:'G'+i,quantity:i===5?2:5,unit:i===5?'托':'箱'});await s.call('sop_cargo_group_review',{group_ids:['G0','G1','G2','G3','G4','G5'],decision:'pass',reason:'全部核实'});const body=s.body('sop_cargo_job_finish',{counts:{label_count:25,total_operated_box_count:31,used_carton_large_count:2,pallet_count:2},reason:'实际工耗整单一次'}),result=await cargoExecution(body,s.env,s.user);assert.deepEqual(await cargoExecution(body,s.env,s.user),result);const out=s.DB.raw.prepare('SELECT * FROM v2_ops_job_results').all();assert.equal(out.length,1);assert.equal(out[0].box_count,25);assert.equal(out[0].pallet_count,2);assert.equal(JSON.parse(out[0].result_json).total_operated_box_count,31);assert.equal(s.state().result,undefined);assert.equal(s.state().cargo_groups.groups[5].outputs[0].input_box_count,6);assert.equal(s.DB.raw.prepare("SELECT COUNT(*) n FROM v2_ops_job_workers WHERE left_at=''").get().n,0);});
test('duplicate completion cannot create more cargo, returned result is retained as immutable prior output',async()=>{const s=fixture();await s.call('sop_cargo_group_complete',{group_id:'G0',quantity:5,unit:'箱'});await assert.rejects(()=>s.call('sop_cargo_group_complete',{group_id:'G0',quantity:5,unit:'箱'}),/重复/);await s.call('sop_cargo_group_review',{group_id:'G0',decision:'return',reason:'重核'});await s.call('sop_cargo_group_complete',{group_id:'G0',quantity:4,unit:'箱'});const g=s.state().cargo_groups.groups[0];assert.equal(g.outputs.length,2);assert.equal(g.outputs[0].quantity,5);assert.equal(g.outputs[0].status,'returned');assert.equal(g.outputs[1].version,2);});
test('wrong group, other owner, forged actor, paused task and unacknowledged mapping cannot bypass server checks',async()=>{const s=fixture();await assert.rejects(()=>s.call('sop_cargo_group_complete',{group_id:'FOREIGN',quantity:5,unit:'箱'}),/不属于/);await assert.rejects(()=>cargoExecution(s.body('sop_cargo_group_complete',{group_id:'G0',quantity:5,unit:'箱'}),s.env,{...s.user,id:'OTHER'}),/派审员/);await s.call('sop_cargo_group_complete',{group_id:'G0',quantity:5,unit:'箱',actor_id:'forged'});assert.equal(s.state().cargo_groups.groups[0].outputs[0].completed_actor_id,'OWNER');s.DB.raw.prepare("UPDATE sop_records SET state=json_set(state,'$.status','paused') WHERE id='T'").run();await assert.rejects(()=>s.call('sop_cargo_group_complete',{group_id:'G1',quantity:5,unit:'箱'}),/暂停/);s.DB.raw.prepare("UPDATE sop_records SET state=json_set(state,'$.status','working') WHERE id='T'").run();s.DB.raw.prepare("UPDATE sop_records SET state=json_set(state,'$.cargo_groups.groups[1].ack_version',0) WHERE id='N'").run();await assert.rejects(()=>s.call('sop_cargo_group_complete',{group_id:'G1',quantity:5,unit:'箱'}),/确认/);});
test('batch review rejects one invalid group atomically and revision races allow one winner',async()=>{const s=fixture();await s.call('sop_cargo_group_complete',{group_id:'G0',quantity:5,unit:'箱'});await assert.rejects(()=>s.call('sop_cargo_group_review',{group_ids:['G0','FOREIGN'],decision:'pass',reason:'test'}),/不属于/);assert.equal(s.state().cargo_groups.groups[0].status,'awaiting_review');const b=s.body('sop_cargo_group_review',{group_ids:['G0'],decision:'pass',reason:'test'}),r=await Promise.allSettled([cargoExecution(b,s.env,s.user),cargoExecution({...b,client_req_id:crypto.randomUUID()},s.env,s.user)]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);});
test('legacy whole-task finish is blocked only for explicit grouped plans',async()=>{const s=fixture(),r=await handleSop({action:'sop_task_finish',id:'T',revision:1,client_req_id:crypto.randomUUID(),result:{quantity:31,unit:'箱'}},s.env);assert.equal(r.ok,false);assert.match(r.error,/分组操作/);assert.equal(s.DB.raw.prepare('SELECT COUNT(*) n FROM v2_ops_job_results').get().n,0);});
test('task revision guard rolls back group completion when pause wins during validation',async()=>{const s=fixture(),batch=s.env.DB.batch;let injected=false;s.env.DB.batch=async statements=>{if(!injected&&statements.some(x=>x.sql.startsWith('INSERT INTO sop_events'))){injected=true;s.DB.raw.prepare("UPDATE sop_records SET revision=revision+1,state=json_set(state,'$.status','paused') WHERE id='T'").run();}return batch(statements);};await assert.rejects(()=>s.call('sop_cargo_group_complete',{group_id:'G0',quantity:5,unit:'箱'}),/revision_conflict/);assert.equal(s.state().cargo_groups.groups[0].outputs,undefined);assert.equal(s.DB.raw.prepare("SELECT revision FROM sop_records WHERE id='N'").get().revision,1);});
