import test from 'node:test';
import assert from 'node:assert/strict';
import {expandMarks,normalizeCargoGroups,cargoGroups} from '../worker-v2/cargo-groups.js';
import {database} from './d1-adapter.mjs';
const example=()=>({total_range:'CP001-CP031',public_attachment_ids:[],groups:[['A','CP001-003',3],['B','CP005-009',5],['C','CP012-018',7],['D','CP022-028',7],['E','CP029-031',3],['打托','CP004,CP010-011,CP019-021',6]].map(([name,range,box_count])=>({name,range,box_count,one_mark_one_box:true,instructions:name==='打托'?'打托':'贴资料发牛奶快递',attachment_ids:[],no_documents_reason:'无需资料，仅测试'}))});
function fixture(){const DB=database(),env={DB,SOP_UPGRADE_ENABLED:'true',SOP_WORK_CHAIN_ENABLED:'true',SOP_ENVIRONMENT:'staging'},user={id:'M',name:'QA客服',role:'manager',scope:'office'};DB.raw.prepare('INSERT INTO sop_records VALUES(?,?,?,?,?,?)').run('N','need',1,'bulk',JSON.stringify({status:'pending',planned_quantity:31,planned_unit:'箱'}),'2026-10-08');return {env,user,DB,body:{action:'sop_cargo_groups_save',id:'N',revision:1,client_req_id:crypto.randomUUID(),...example()}};}
test('31 boxes: five document groups cover25 and pallet group covers6, preserving marks and input units',()=>{const g=normalizeCargoGroups(example());assert.equal(g.box_count,31);assert.equal(g.groups.length,6);assert.equal(g.groups.slice(0,5).reduce((n,x)=>n+x.box_count,0),25);assert.deepEqual(g.coverage,{checked:true,unassigned:[]});assert.equal(g.groups[0].marks[0],'CP001');assert.equal(g.groups[5].box_count,6);assert.equal(g.groups[5].output,undefined);});
test('range parser keeps zeroes, supports shortened endpoints, rejects duplicates and invalid ranges',()=>{assert.deepEqual(expandMarks('CP001~003,005,010-011'),['CP001','CP002','CP003','CP005','CP010','CP011']);for(const x of ['CP003-001','CP001-DP003','CP001-03','CP001,CP001','CP000000-999999',''])assert.throws(()=>expandMarks(x));});
test('overlap is rejected unless the actual cargo has distinct explicit identifiers and neither asserts one mark one box',()=>{const x=example();x.groups[1].range='CP003-007';assert.throws(()=>normalizeCargoGroups(x),/交叉/);const groups=['红托','蓝托'].map(identifier=>({range:'CP001',box_count:4,name:identifier,instructions:'贴不同资料',identifier}));assert.equal(normalizeCargoGroups({groups}).box_count,8);groups[1].identifier='红托';assert.throws(()=>normalizeCargoGroups({groups}),/交叉/);});
test('one mark can mean many boxes only with explicit quantity, optional total never claims complete coverage',()=>{const x={groups:[{name:'多箱',range:'CP001',box_count:6,instructions:'打托'}]};assert.equal(normalizeCargoGroups(x).coverage.checked,false);x.groups[0].one_mark_one_box=true;assert.throws(()=>normalizeCargoGroups(x),/箱数/);x.groups[0].one_mark_one_box=false;x.total_range='CP001-003';assert.deepEqual(normalizeCargoGroups(x).coverage.unassigned,['CP002','CP003']);});
test('hundreds of boxes with dozens of documents remain group rows, not individual plans',()=>{const x={total_range:'BX0001-0300',groups:Array.from({length:60},(_,i)=>({name:'G'+i,range:`BX${String(i*5+1).padStart(4,'0')}-${String(i*5+5).padStart(4,'0')}`,box_count:5,instructions:'贴资料',one_mark_one_box:true,attachment_ids:['FILE-'+i]}))};const g=normalizeCargoGroups(x);assert.equal(g.groups.length,60);assert.equal(g.box_count,300);assert.equal(g.coverage.unassigned.length,0);});
test('save retains audited versions, retries idempotently and rejects conflicting request reuse',async()=>{const s=fixture(),r=await cargoGroups(s.body,s.env,s.user);assert.equal(r.ok,true);assert.equal(r.cargo_version,1);assert.deepEqual(await cargoGroups(s.body,s.env,s.user),r);await assert.rejects(()=>cargoGroups({...s.body,total_range:''},s.env,s.user),/冲突/);const state=JSON.parse(s.DB.raw.prepare('SELECT state FROM sop_records WHERE id=?').get('N').state);assert.equal(state.cargo_groups.actor_id,'M');assert.equal(s.DB.raw.prepare('SELECT COUNT(*) n FROM sop_events').get().n,1);assert.equal(s.DB.raw.prepare('SELECT COUNT(*) n FROM v2_ops_jobs').get().n,0);});
test('parallel last revision has one winner and ambiguous response can be retried without a second version',async()=>{const s=fixture(),r=await Promise.allSettled([cargoGroups(s.body,s.env,s.user),cargoGroups({...s.body,client_req_id:crypto.randomUUID()},s.env,s.user)]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal(s.DB.raw.prepare('SELECT COUNT(*) n FROM sop_events').get().n,1);const a=fixture(),batch=a.env.DB.batch;a.env.DB.batch=async x=>{const r=await batch(x);if(x.some(s=>s.sql.startsWith('INSERT INTO sop_events')))throw Error('lost response');return r;};assert.equal((await cargoGroups(a.body,a.env,a.user)).ok,true);});
test('server rejects field actors, cross-plan group or file IDs, wrong totals and oversized notes',async()=>{const s=fixture();await assert.rejects(()=>cargoGroups(s.body,s.env,{...s.user,scope:'field'}),/办公室/);for(const change of [{id:'OTHER'},{attachment_ids:['FOREIGN']},{box_count:4},{instructions:'长'.repeat(4001)}]){const b=structuredClone(s.body);Object.assign(b.groups[0],change);await assert.rejects(()=>cargoGroups(b,s.env,s.user));}assert.equal(s.DB.raw.prepare('SELECT COUNT(*) n FROM sop_events').get().n,0);});
test('immutable file snapshots support many to many links and explicit public documents',async()=>{const s=fixture();for(const id of ['F1','COMMON'])s.DB.raw.prepare('INSERT INTO v2_attachments(id,related_doc_type,related_doc_id,attachment_category,file_name,file_key,file_size,content_type,uploaded_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,'sop_need','N','shipping_document',id+'.pdf','immutable/'+id,20,'application/pdf','QA','2026-10-08');s.body.public_attachment_ids=['COMMON'];s.body.groups[0].attachment_ids=['F1'];s.body.groups[1].attachment_ids=['F1'];await cargoGroups(s.body,s.env,s.user);const r=await cargoGroups({action:'sop_cargo_groups',id:'N'},s.env,s.user);assert.equal(r.cargo_groups.groups[0].documents[0].file_key,'immutable/F1');assert.deepEqual(r.cargo_groups.groups[0].documents,r.cargo_groups.groups[1].documents);assert.equal(r.cargo_groups.public_documents[0].id,'COMMON');});
test('no migration from old notes; started and allocated plans cannot be silently overwritten',async()=>{const s=fixture();let state=JSON.parse(s.DB.raw.prepare('SELECT state FROM sop_records').get().state);state.notes='CP001-031';s.DB.raw.prepare('UPDATE sop_records SET state=?').run(JSON.stringify(state));assert.equal((await cargoGroups({action:'sop_cargo_groups',id:'N'},s.env,s.user)).cargo_groups,null);for(const data of [{task_id:'T'},{result:{quantity:31,unit:'箱'}},{links:[{outbound_id:'OB'}]}]){s.DB.raw.prepare('UPDATE sop_records SET state=?').run(JSON.stringify({...state,...data}));await assert.rejects(()=>cargoGroups(s.body,s.env,s.user),/版本变更/);}});
test('actual Worker office session reaches group routes and records verified actor',async()=>{const {default:worker}=await import('../worker-v2/index.js');const {operationHeaders,rememberOperation,confirmOperation}=await import('./office-operator-fixture.mjs');const s=fixture();s.env.SOP_ACCESS_CONTROL='true';s.env.SOP_USERS_JSON=JSON.stringify([{...s.user,key:'isolated-cargo-key'}]);let cookie='';const call=async(action,body={})=>{const r=await worker.fetch(new Request('https://fixture.test/api',{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie,...operationHeaders(cookie)},body:JSON.stringify({action,client_req_id:crypto.randomUUID(),...body})}),s.env);if(r.headers.has('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return rememberOperation(await r.json(),cookie);};assert.equal((await call('sop_login',{sop_key:'isolated-cargo-key'})).ok,true);await confirmOperation(call,s.user.name);const r=await call('sop_cargo_groups_save',{...s.body,actor_id:'forged'});assert.equal(r.ok,true,r.error);const read=await call('sop_cargo_groups',{id:'N'});assert.equal(read.cargo_groups.actor_id,'M');});

test('simple pallet group retains notes without inventing a no-document explanation without assuming one mark equals one box',()=>{const g=normalizeCargoGroups({groups:[{range:'CP001',box_count:6,instructions:'打托',attachment_ids:[]}]});assert.equal(g.groups[0].one_mark_one_box,false);assert.equal(g.groups[0].box_count,6);assert.equal(g.groups[0].no_documents_reason,'');assert.equal(g.groups[0].name,'组 1');});

test('blank group notes, name, process selection and no-document reason are legal without fabricated instructions',()=>{const g=normalizeCargoGroups({groups:[{range:'A001',box_count:10,instructions:'',name:'',process_names:[],no_documents_reason:''}]}).groups[0];assert.equal(g.instructions,'');assert.equal(g.no_documents_reason,'');assert.equal(g.name,'组 1');assert.deepEqual(g.process_names,['作业']);assert.throws(()=>normalizeCargoGroups({groups:[{range:'A1',box_count:1,instructions:'x'.repeat(4001)}]}),/第1组备注最多4000字/);});
