import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import worker from '../worker-v2/index.js';import {database} from './d1-adapter.mjs';
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a3ioAAAAASUVORK5CYII=','base64');
function setup(){const DB=database(),files=new Map(),env={DB,SOP_ENVIRONMENT:'staging',SOP_UPGRADE_ENABLED:'true',SOP_PUBLIC_TEST_ACCESS:'true',R2_BUCKET:{async put(key,data,options){files.set(key,{bytes:Buffer.from(await new Response(data).arrayBuffer()),options});}}};
 const call=async(action,data={},ok=true)=>{const r=await worker.fetch(new Request('https://fixture.test/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,client_req_id:crypto.randomUUID(),...data})}),env),v=await r.json();if(ok)assert.equal(v.ok,true,v.message||v.error);return v;};
 const upload=async(id,bytes=png,type='image/png')=>{const fd=new FormData();for(const [k,v] of Object.entries({action:'v2_attachment_upload',related_doc_type:'sop_task',related_doc_id:id,attachment_category:'location_photo',uploaded_by:'伪造上传人'}))fd.append(k,v);fd.append('file',new File([bytes],'location.png',{type}));return (await worker.fetch(new Request('https://fixture.test/api',{method:'POST',body:fd}),env)).json();};
 const task=async(id='A')=>{const t=await call('sop_task_create',{department:'bulk',title:'虚拟货位照片测试',job_type:'bulk_op',workers:[{id,name:'虚拟操作员'}],lead_id:id,estimated_minutes:5});return call('sop_task_start',{id:t.id,revision:t.revision});};
 return {DB,env,files,call,upload,task};}
test('creation date is automatic and cannot drift when expected arrival is edited',async()=>{const {call}=setup();const p=await call('v2_inbound_plan_create',{plan_date:'1999-01-01',expected_arrival:'2026-10-02',customer:'虚拟日期验收',biz_classes:['bulk']});const first=(await call('v2_inbound_plan_detail',{id:p.id})).plan;assert.equal(first.plan_date,new Date(Date.now()+9*3600000).toISOString().slice(0,10));await call('v2_inbound_plan_update',{id:p.id,plan_date:'1998-01-01',expected_arrival:'2026-10-03',biz_classes:['bulk']});const next=(await call('v2_inbound_plan_detail',{id:p.id})).plan;assert.equal(next.plan_date,first.plan_date);assert.equal(next.created_at,first.created_at);assert.equal(next.expected_arrival,'2026-10-03');});
test('external bulk orders dispatch actual people and preserve outputs without an office plan',async()=>{const {call,DB}=setup();const start=await call('sop_native_start',{payload:{action:'v2_bulk_op_job_start',work_order_no:'EXT-QA-0922',client_req_id:'external-start'},workers:[{id:'A',name:'甲'},{id:'B',name:'乙'}],lead_id:'A',estimated_minutes:5,labor_department:'bulk'});await call('v2_bulk_op_job_finish',{job_id:start.job_id,worker_id:'A',complete_job:true,customer:'虚拟外部客户',label_count:5,total_operated_box_count:20,pallet_count:3});const job=DB.raw.prepare('SELECT * FROM v2_ops_jobs WHERE id=?').get(start.job_id);assert.equal(job.status,'completed');assert.equal(job.related_doc_id,'EXT-QA-0922');assert.equal(DB.raw.prepare("SELECT COUNT(*) n FROM v2_ops_job_workers WHERE job_id=? AND left_at!=''").get(start.job_id).n,2);const result=JSON.parse(DB.raw.prepare('SELECT result_json FROM v2_ops_job_results WHERE job_id=?').get(start.job_id).result_json);assert.equal(result.label_count,5);assert.equal(result.pallet_count,3);assert.equal(DB.raw.prepare('SELECT COUNT(*) n FROM v2_outbound_orders').get().n,0);const bad=await call('v2_bulk_op_job_start',{work_order_no:'NEED-internal',worker_id:'A'},false);assert.equal(bad.ok,false);assert.match(bad.error,/需求/);});
test('photo upload and review retain images and metrics without duplicate text entry',async()=>{const {task,upload,call,DB,files}=setup(),t=await task();const invalid=await upload(t.id,Buffer.from('not an image'));assert.equal(invalid.ok,false);const photo=await upload(t.id);assert.equal(photo.ok,true,photo.error);assert.equal(files.size,1);assert.equal(DB.raw.prepare('SELECT uploaded_by FROM v2_attachments WHERE id=?').get(photo.id).uploaded_by,'测试负责人');const finish={id:t.id,revision:t.revision,result:{quantity:3,unit:'托',pallet_count:3,operated_box_count:20,label_count:6,location_photos:[photo.id]},decision:'pass',reason:'数量与货位照片已核对',client_req_id:'photo-finish'};await call('sop_task_complete_review',finish);await call('sop_task_complete_review',finish);const record=(await call('sop_get',{id:t.id})).record;assert.equal(record.status,'completed');assert.equal(record.result.description,'');assert.equal(record.result.location,'');assert.equal(record.result.location_photos[0].file_key,photo.file_key);assert.equal(record.result.label_count,6);assert.equal(DB.raw.prepare('SELECT COUNT(*) n FROM v2_ops_job_results WHERE job_id=?').get(t.id).n,1);assert.equal((await upload(t.id)).ok,false);});
test('photos belonging to another task cannot be attached and a failed review keeps timing open',async()=>{const {task,upload,call,DB}=setup(),a=await task('A'),b=await task('B'),photo=await upload(a.id);const bad=await call('sop_task_complete_review',{id:b.id,revision:b.revision,result:{quantity:1,unit:'托',location_photos:[photo.id]},decision:'pass',reason:'检查'},false);assert.equal(bad.ok,false);assert.match(bad.error,/本任务/);assert.equal(DB.raw.prepare('SELECT status FROM v2_ops_jobs WHERE id=?').get(b.id).status,'working');assert.equal(DB.raw.prepare("SELECT COUNT(*) n FROM v2_ops_job_workers WHERE job_id=? AND left_at=''").get(b.id).n,1);});
test('downloadable template imports with the existing parser and preserves leading zero identifiers',async()=>{const context={};vm.createContext(context);vm.runInContext(fs.readFileSync(new URL('../shared/xlsx.full.min.js',import.meta.url),'utf8'),context);const {XLSX}=context,book=XLSX.read(fs.readFileSync(new URL('../shared/templates/pallet-details.xlsx.b64',import.meta.url),'utf8'),{type:'base64'});const grid=XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{header:1,raw:false,defval:''});assert.equal(grid[0][0],'托盘号');assert.equal(grid[0][1],'箱唛/条码');assert.equal(grid[0].length,6);assert.equal(grid.slice(1).some(r=>r.some(x=>String(x).trim())),false);
 XLSX.utils.sheet_add_aoa(book.Sheets[book.SheetNames[0]],[['0001','001234567890','','','','']],{origin:'A2'});const bytes=XLSX.write(book,{type:'array',bookType:'xlsx'});let sent;const c={window:{},XLSX,FormData,crypto,confirm:()=>true,fetch:async()=>({json:async()=>({ok:true,id:'ATT-template'})}),CKSession:{user:{name:'测试'},request:async(a,b)=>{sent=b;return {ok:true};}}};vm.createContext(c);vm.runInContext(fs.readFileSync(new URL('../shared/sop-planning-ui.js',import.meta.url),'utf8'),c);await c.window.CKUploadWorkDetails({id:'NEED-template',revision:1},{name:'template.xlsx',size:bytes.byteLength,arrayBuffer:async()=>bytes});assert.equal(sent.rows[0].pallet,'0001');assert.equal(sent.rows[0].mark,'001234567890');assert.equal(sent.rows[0].quantity,1);
});
