import test from 'node:test';import assert from 'node:assert/strict';import worker from '../worker-v2/index.js';import {database} from './d1-adapter.mjs';
async function setup(t,extra={}){
 const DB=database();t.after(()=>DB.raw.close());const env={DB,SOP_ENVIRONMENT:'staging',SOP_UPGRADE_ENABLED:'true',SOP_PUBLIC_TEST_ACCESS:'true',SOP_WORK_CHAIN_ENABLED:'true'};
 const call=async(action,body={})=>(await worker.fetch(new Request('https://fixture.invalid/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,client_req_id:crypto.randomUUID(),...body})}),env)).json();
 const ok=async(action,body)=>{const r=await call(action,body);assert.equal(r.ok,true,JSON.stringify(r));return r;};await ok('sop_identity');const stamp='2026-09-15T00:00:00.000Z';
 DB.raw.prepare("INSERT INTO v2_outbound_orders(id,customer,biz_class,outbound_mode,status,display_no,planned_box_count,created_at,updated_at,uses_stock_operation,stock_operation_status) VALUES('OLD-ORDER','Synthetic legacy','bulk','customer_pickup','ready_to_ship','OLD-001',4,?,?,?,?)").run(stamp,stamp,extra.uses_stock_operation||0,extra.stock_operation_status||'');
 DB.raw.prepare("INSERT INTO v2_ops_jobs(id,job_type,related_doc_type,related_doc_id,biz_class,status,created_by,created_at,updated_at,active_worker_count) VALUES('OLD-JOB','load_outbound','outbound_order','OLD-ORDER','bulk','working','OLD-A',?,?,2)").run(stamp,stamp);
 for(const id of ['OLD-A','OLD-B'])DB.raw.prepare('INSERT INTO v2_ops_job_workers(id,job_id,worker_id,worker_name,joined_at) VALUES(?,?,?,?,?)').run(id+'-SEG','OLD-JOB',id,'Synthetic '+id,stamp);
 const finish=body=>call('v2_outbound_load_finish',{job_id:'OLD-JOB',worker_id:'OLD-A',complete_job:true,box_count:4,pallet_count:0,...body});
 const snap=()=>({job:DB.raw.prepare("SELECT id,status FROM v2_ops_jobs WHERE id='OLD-JOB'").get(),workers:DB.raw.prepare("SELECT id,joined_at,left_at,minutes_worked FROM v2_ops_job_workers WHERE job_id='OLD-JOB' ORDER BY id").all(),order:DB.raw.prepare("SELECT status,actual_box_count FROM v2_outbound_orders WHERE id='OLD-ORDER'").get(),results:DB.raw.prepare("SELECT COUNT(*) n FROM v2_ops_job_results WHERE job_id='OLD-JOB'").get().n});
 return {DB,env,call,ok,finish,snap};
}
test('true pre-upgrade load appears without mutation; explicit continuation retains job, documents and original crew clocks',async t=>{
 const s=await setup(t),before=s.snap(),home=await s.ok('sop_dispatch_list');assert.equal(home.items.length,1);assert.equal(home.items[0].task_kind,'legacy');assert.equal(home.items[0].business_no,'OLD-001');assert.deepEqual(s.snap(),before);assert.equal(s.DB.raw.prepare('SELECT COUNT(*) n FROM sop_records').get().n,0);
 await s.ok('sop_native_adopt',{job_id:'OLD-JOB'});await s.ok('sop_native_adopt',{job_id:'OLD-JOB'});assert.deepEqual(s.snap(),before);assert.equal((await s.ok('v2_ops_job_detail',{job_id:'OLD-JOB'})).can_manage_dispatch,true);assert.equal((await s.ok('sop_dispatch_list')).items[0].task_kind,'dispatch');
 assert.equal((await s.finish()).ok,true);assert.equal((await s.finish()).ok,true);const done=s.snap();assert.equal(done.job.status,'completed');assert.equal(done.order.status,'shipped');assert.equal(done.order.actual_box_count,4);assert.equal(done.results,1);assert.ok(done.workers.every(x=>x.left_at));assert.equal(s.DB.raw.prepare('SELECT COUNT(*) n FROM ck_load_trips').get().n,0);
});
test('a new load still requires a reviewed need; legacy discovery cannot be used to create a new truck',async t=>{const s=await setup(t);assert.equal((await s.finish()).ok,false);const p={payload:{action:'v2_outbound_load_start',order_id:'OLD-ORDER',client_req_id:crypto.randomUUID()},workers:[{id:'NEW',name:'Synthetic new'}],lead_id:'NEW',estimated_minutes:15,labor_department:'bulk'};const r=await s.call('sop_native_start',p);assert.equal(r.ok,false);assert.match(r.error,/作业|原任务|缺少/);});
for(const [name,change,body,pattern]of [
 ['short load',null,{box_count:3},/数量|未装完/],
 ['warehouse change',"UPDATE v2_outbound_orders SET warehouse_ack_required=1 WHERE id='OLD-ORDER'",{},/变更/],
 ['pickup change',"UPDATE v2_outbound_orders SET pickup_confirm_required=1 WHERE id='OLD-ORDER'",{},/提货/],
 ['cancelled order',"UPDATE v2_outbound_orders SET status='cancelled' WHERE id='OLD-ORDER'",{},/取消/]
])test('continued legacy load retains '+name+' gate and leaves crew working',async t=>{const s=await setup(t);await s.ok('sop_native_adopt',{job_id:'OLD-JOB'});if(change)s.DB.raw.exec(change);const before=s.snap(),r=await s.finish(body);assert.equal(r.ok,false);assert.match(r.error,pattern);assert.deepEqual(s.snap(),before);});
test('legacy stock-operation completion remains mandatory',async t=>{const s=await setup(t,{uses_stock_operation:1,stock_operation_status:'working'});await s.ok('sop_native_adopt',{job_id:'OLD-JOB'});const r=await s.finish();assert.equal(r.ok,false);assert.match(r.error,/库内作业/);assert.equal(s.snap().results,0);});
test('legacy continuation still blocks a linked unreviewed need',async t=>{const s=await setup(t);const data={customer:'Synthetic legacy',title:'Synthetic need',status:'working',source_type:'outbound',source_id:'OLD-ORDER',links:[]};s.DB.raw.prepare("INSERT INTO sop_records VALUES('OLD-NEED','need',1,'bulk',?,?)").run(JSON.stringify(data),new Date().toISOString());await s.ok('sop_native_adopt',{job_id:'OLD-JOB'});const r=await s.finish();assert.equal(r.ok,false);assert.match(r.error,/审核/);assert.equal(s.snap().results,0);});
test('legacy shipment race rolls back every result and clock; same original job completes after confirmation',async t=>{const s=await setup(t);await s.ok('sop_native_adopt',{job_id:'OLD-JOB'});const before=s.snap(),batch=s.DB.batch.bind(s.DB);let first=true;s.DB.batch=async sql=>{if(first&&sql.some(x=>x.sql.includes("UPDATE v2_outbound_orders SET status='shipped'"))){first=false;s.DB.raw.exec("UPDATE v2_outbound_orders SET warehouse_ack_required=1 WHERE id='OLD-ORDER'");}return batch(sql);};const r=await s.finish();assert.equal(r.ok,false);const after=s.snap();assert.deepEqual(after.job,before.job);assert.deepEqual(after.workers,before.workers);assert.equal(after.results,0);s.DB.raw.exec("UPDATE v2_outbound_orders SET warehouse_ack_required=0 WHERE id='OLD-ORDER'");assert.equal((await s.finish()).ok,true);});
test('legacy continuation metadata failure rolls back and the original job remains available for retry',async t=>{const s=await setup(t),before=s.snap();s.DB.raw.exec("CREATE TRIGGER fail_adopt BEFORE INSERT ON sop_records WHEN NEW.id='OLD-JOB' BEGIN SELECT RAISE(ABORT,'fixture_adopt_failure'); END");assert.equal((await s.call('sop_native_adopt',{job_id:'OLD-JOB'})).ok,false);assert.deepEqual(s.snap(),before);assert.equal(s.DB.raw.prepare("SELECT COUNT(*) n FROM sop_events WHERE record_id='OLD-JOB'").get().n,0);s.DB.raw.exec('DROP TRIGGER fail_adopt');await s.ok('sop_native_adopt',{job_id:'OLD-JOB'});});
test('concurrent legacy continuation of the same original job creates one ownership history and no extra clock',async t=>{const s=await setup(t),before=s.snap(),responses=await Promise.all([s.call('sop_native_adopt',{job_id:'OLD-JOB'}),s.call('sop_native_adopt',{job_id:'OLD-JOB'})]);assert.ok(responses.every(r=>r.ok));assert.deepEqual(s.snap(),before);assert.equal(s.DB.raw.prepare("SELECT COUNT(*) n FROM sop_records WHERE id='OLD-JOB'").get().n,1);assert.equal(s.DB.raw.prepare("SELECT COUNT(*) n FROM sop_events WHERE record_id='OLD-JOB'").get().n,1);});
