import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const source=fs.readFileSync(new URL('../003/app.js',import.meta.url),'utf8'),scannerSource=source.slice(source.indexOf('async function startLocationScan'),source.indexOf('async function loadMaterials'));
function setup(){let resolveStart,rejectStart,started=false,stops=0;const start=new Promise((resolve,reject)=>{resolveStart=()=>{started=true;resolve();};rejectStart=reject;});
 const nodes=new Map();const E=id=>{if(!nodes.has(id))nodes.set(id,{value:'FIXTURE-A01',textContent:'',classes:new Set(),classList:{add(x){this.owner.classes.add(x);},contains(x){return this.owner.classes.has(x);}}});const n=nodes.get(id);n.classList.owner=n;return n;};
 E('locationPickerModal').classes.add('hidden');const target={value:''},context=vm.createContext({Promise,S003:{lang:'zh',locationScanner:null,locationTarget:target},Html5Qrcode:class{start(){return start;}stop(){stops++;if(!started)throw Error('Cannot stop, scanner is not running or paused.');started=false;return Promise.resolve();}clear(){}},E,T:x=>x,val:id=>E(id).value,findActiveLocation:code=>code==='FIXTURE-A01'?{location_code:code}:null,setLocationControlValue:(t,v)=>{t.value=v;},closeLocationPicker(){},toast(){},errorText:x=>x});vm.runInContext(scannerSource,context);
 return{context,target,E,resolveStart,rejectStart,stops:()=>stops,started:()=>started};}
test('manual location input closes a camera still starting without throwing, then stops a late camera',async()=>{const f=setup(),pending=f.context.startLocationScan();assert.doesNotThrow(()=>f.context.applyManualLocationCode());assert.equal(f.target.value,'FIXTURE-A01');assert.equal(f.context.S003.locationScanner,null);assert.equal(f.E('locationScannerModal').classes.has('hidden'),true);await new Promise(r=>setImmediate(r));f.resolveStart();await pending;await new Promise(r=>setImmediate(r));assert.equal(f.started(),false);assert.equal(f.stops(),2);});
test('camera permission failure preserves manual location fallback and clears scanner safely',async()=>{const f=setup(),pending=f.context.startLocationScan();f.rejectStart(Error('Fixture permission denied'));await pending;await new Promise(r=>setImmediate(r));assert.equal(f.context.S003.locationScanner,null);assert.match(f.E('locationScannerError').textContent,/手动输入/);assert.doesNotThrow(()=>f.context.applyManualLocationCode());assert.equal(f.target.value,'FIXTURE-A01');});
test('unregistered manual location stays open and cannot replace the chosen putaway position',async()=>{const f=setup();f.E('manualLocationCode').value='UNKNOWN';f.context.applyManualLocationCode();assert.equal(f.target.value,'');assert.equal(f.E('locationScannerError').textContent,'location_not_registered');assert.equal(f.E('locationScannerModal').classes.has('hidden'),false);});

function extract(name){const pattern=new RegExp('(?:async )?function '+name+'\\('),m=source.match(pattern);if(!m)throw Error('Function missing: '+name);const start=m.index,next=source.slice(start+1).search(/\n(?:async )?function [A-Za-z]/);return next<0?source.slice(start):source.slice(start,start+1+next);}
function importFixture(kind){
 const nodes=new Map(),errors=[],requests=[],previews=[];const E=id=>{if(!nodes.has(id))nodes.set(id,{disabled:false,value:'',className:'',innerHTML:'',textContent:''});return nodes.get(id);};
 const context=vm.createContext({Uint8Array,ArrayBuffer,TextDecoder,TextEncoder,File,Number,Object,Array,Set,Map,JSON,S003:{},E,T:x=>x,esc:x=>x,errorText:x=>x,renderLocationImportErrors:x=>errors.push(...x),renderMaterialImportErrors:x=>errors.push(...x),renderLocationImportPreview:x=>previews.push(x),renderMaterialImportPreview:x=>previews.push(x),operatorPayload:()=>({operator_id:'FIXTURE-M'}),api:async(a,d)=>{requests.push({action:a,data:d});return{ok:true,items:d.rows,created_count:d.rows.length,updated_count:0};}});
 vm.runInContext(fs.readFileSync(new URL('../shared/xlsx.full.min.js',import.meta.url),'utf8'),context);
 const header=kind==='location'?'LOCATION_IMPORT_HEADERS':'MATERIAL_IMPORT_HEADERS',start=source.indexOf('var '+header),end=source.indexOf('\nfunction ',start);vm.runInContext(source.slice(start,end),context);
 const functions=['normalizeImportStatus',kind==='location'?'mapLocationImportRows':'mapMaterialImportRows',kind==='location'?'localLocationImportErrors':'localMaterialImportErrors',kind==='location'?'readLocationImport':'readMaterialImport'];for(const f of functions)vm.runInContext(extract(f),context);
 return{context,errors,requests,previews,read:file=>context[kind==='location'?'readLocationImport':'readMaterialImport']({files:[file]})};
}
test('UTF8 Chinese location CSV without BOM reaches the real import preview unchanged',async()=>{const f=importFixture('location');await f.read(new File(['位置编码*,位置名称,状态\nFIXTURE-A01,合成库位,active\n'],'fixture.csv',{type:'text/csv'}));assert.deepEqual(f.errors,[]);assert.equal(f.requests.length,1);assert.equal(f.requests[0].data.rows[0].location_code,'FIXTURE-A01');assert.equal(f.requests[0].data.rows[0].location_name,'合成库位');assert.equal(f.previews.length,1);});
test('UTF8 Chinese material CSV without BOM preserves master name, specification and unit',async()=>{const f=importFixture('material');await f.read(new File(['耗材编号,中文名称*,分类*,规格,单位*,期初库存\nFIXTURE-TAPE,测试胶带,包材,透明宽五厘米,卷,0\n'],'fixture.csv',{type:'text/csv'}));assert.deepEqual(f.errors,[]);assert.equal(f.requests.length,1);const row=f.requests[0].data.rows[0];assert.equal(row.name_zh,'测试胶带');assert.equal(row.category,'包材');assert.equal(row.spec,'透明宽五厘米');assert.equal(row.unit,'卷');});
test('numeric CSV material codes and barcodes retain every leading zero',async()=>{const f=importFixture('material');await f.read(new File(['耗材编号,条码,中文名称*,分类*,单位*,期初库存\n00123,00900123456,测试标签,包材,卷,0\n'],'fixture.csv',{type:'text/csv'}));assert.deepEqual(f.errors,[]);assert.equal(f.requests[0].data.rows[0].material_code,'00123');assert.equal(f.requests[0].data.rows[0].barcode,'00900123456');});
test('long numeric CSV barcodes retain all digits without floating point rounding',async()=>{const f=importFixture('material');await f.read(new File(['耗材编号,条码,中文名称*,分类*,单位*,期初库存\nFIXTURE-ID,12345678901234567890,测试标签,包材,卷,0\n'],'fixture.csv',{type:'text/csv'}));assert.deepEqual(f.errors,[]);assert.equal(f.requests[0].data.rows[0].barcode,'12345678901234567890');});
test('Excel material workbook retains native Chinese cells with original parsing behavior',async()=>{const f=importFixture('material'),wb=f.context.XLSX.utils.book_new();f.context.XLSX.utils.book_append_sheet(wb,f.context.XLSX.utils.aoa_to_sheet([['中文名称*','分类*','单位*'],['工作手套','用品','双']]),'耗材');const data=f.context.XLSX.write(wb,{bookType:'xlsx',type:'array'});await f.read(new File([data],'fixture.xlsx'));assert.deepEqual(f.errors,[]);assert.equal(f.requests[0].data.rows[0].name_zh,'工作手套');assert.equal(f.requests[0].data.rows[0].unit,'双');});
test('real material form accepts a zero stocktake but still rejects zero issue quantity',async()=>{if(!process.env.CK_JSDOM_MODULE)throw Error('CK_JSDOM_MODULE is required, this check must not skip');const mod=await import(process.env.CK_JSDOM_MODULE),{JSDOM}=mod.default||mod;const dom=new JSDOM(fs.readFileSync(new URL('../003/index.html',import.meta.url),'utf8'),{url:'https://fixture.test/003/',runScripts:'outside-only'}),w=dom.window;w.S003={operatorName:'Fixture manager',lang:'zh',currentMaterial:{item:{id:'FIXTURE-M',name_zh:'Fixture material',current_qty:10,unit:'卷'}}};w.E=id=>w.document.getElementById(id);w.T=x=>x;w.txnLabel=x=>x;w.fmtQty=x=>String(x);w.isField=()=>false;w.eval(extract('openMaterialTxn'));w.openMaterialTxn('stocktake');w.E('mtQty').value='0';assert.equal(w.E('mtQty').checkValidity(),true);assert.equal(w.E('mtQty').form.checkValidity(),true);w.openMaterialTxn('issue');w.E('mtQty').value='0';assert.equal(w.E('mtQty').checkValidity(),false);dom.window.close();});
