import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const source=fs.readFileSync(new URL('../003/app.js',import.meta.url),'utf8'),scannerSource=source.slice(source.indexOf('async function startLocationScan'),source.indexOf('async function loadMaterials'));
function setup(){let resolveStart,rejectStart,started=false,stops=0;const start=new Promise((resolve,reject)=>{resolveStart=()=>{started=true;resolve();};rejectStart=reject;});
 const nodes=new Map();const E=id=>{if(!nodes.has(id))nodes.set(id,{value:'FIXTURE-A01',textContent:'',classes:new Set(),classList:{add(x){this.owner.classes.add(x);},contains(x){return this.owner.classes.has(x);}}});const n=nodes.get(id);n.classList.owner=n;return n;};
 E('locationPickerModal').classes.add('hidden');const target={value:''},context=vm.createContext({Promise,S003:{lang:'zh',locationScanner:null,locationTarget:target},Html5Qrcode:class{start(){return start;}stop(){stops++;if(!started)throw Error('Cannot stop, scanner is not running or paused.');started=false;return Promise.resolve();}clear(){}},E,T:x=>x,val:id=>E(id).value,findActiveLocation:code=>code==='FIXTURE-A01'?{location_code:code}:null,setLocationControlValue:(t,v)=>{t.value=v;},closeLocationPicker(){},toast(){},errorText:x=>x});vm.runInContext(scannerSource,context);
 return{context,target,E,resolveStart,rejectStart,stops:()=>stops,started:()=>started};}
test('manual location input closes a camera still starting without throwing, then stops a late camera',async()=>{const f=setup(),pending=f.context.startLocationScan();assert.doesNotThrow(()=>f.context.applyManualLocationCode());assert.equal(f.target.value,'FIXTURE-A01');assert.equal(f.context.S003.locationScanner,null);assert.equal(f.E('locationScannerModal').classes.has('hidden'),true);await new Promise(r=>setImmediate(r));f.resolveStart();await pending;await new Promise(r=>setImmediate(r));assert.equal(f.started(),false);assert.equal(f.stops(),2);});
test('camera permission failure preserves manual location fallback and clears scanner safely',async()=>{const f=setup(),pending=f.context.startLocationScan();f.rejectStart(Error('Fixture permission denied'));await pending;await new Promise(r=>setImmediate(r));assert.equal(f.context.S003.locationScanner,null);assert.match(f.E('locationScannerError').textContent,/手动输入/);assert.doesNotThrow(()=>f.context.applyManualLocationCode());assert.equal(f.target.value,'FIXTURE-A01');});
test('unregistered manual location stays open and cannot replace the chosen putaway position',async()=>{const f=setup();f.E('manualLocationCode').value='UNKNOWN';f.context.applyManualLocationCode();assert.equal(f.target.value,'');assert.equal(f.E('locationScannerError').textContent,'location_not_registered');assert.equal(f.E('locationScannerModal').classes.has('hidden'),false);});
