import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';
const adjacent=fileURLToPath(new URL('../',import.meta.url)),repo=path.resolve(process.env.CK_REVIEW_REPO||(fs.existsSync(path.join(adjacent,'worker-v2/index.js'))?adjacent:fileURLToPath(new URL('../../ck-system-review-03a32e9/',import.meta.url))));
const {default:worker}=await import(pathToFileURL(path.join(repo,'worker-v2/index.js'))),{database}=await import(pathToFileURL(path.join(repo,'tests/d1-adapter.mjs')));
function fixture(t){const DB=database();t.after(()=>DB.raw.close());const env={DB,SOP_ENVIRONMENT:'staging',SOP_UPGRADE_ENABLED:'true',SOP_PUBLIC_TEST_ACCESS:'true'};const call=async(action,data={})=>(await worker.fetch(new Request('https://fixture.invalid/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,client_req_id:crypto.randomUUID(),...data})}),env)).json();const ok=async(action,data)=>{const r=await call(action,data);assert.equal(r.ok,true,action+': '+(r.error||r.message));return r;};const request=(action,data={},name='A',key=crypto.randomUUID())=>({payload:{action,client_req_id:key,...data},workers:[{id:'QA-'+name,name:'QA '+name}],lead_id:'QA-'+name,estimated_minutes:15,labor_department:'bulk'});return{DB,env,call,ok,request};}
test('first-time external pick same form and request restores the original dispatch after its internal create normalization',async t=>{const f=fixture(t),request=f.request('v2_pick_job_start_by_docs',{pick_doc_nos:['QA-NEW-PICK-A','QA-NEW-PICK-B']},'A','QA-PICK-LOSTREPLY'),first=await f.ok('sop_native_start',request),retry=await f.ok('sop_native_start',request);assert.equal(retry.job_id,first.job_id);assert.equal(f.DB.raw.prepare('SELECT COUNT(*) n FROM v2_ops_jobs').get().n,1);});
test('bulk dispatch commit cannot resurrect an order cancelled by a completed office request after preflight',async t=>{
 const f=fixture(t),order=await f.ok('v2_outbound_order_create',{customer:'QA synthetic bulk',biz_class:'bulk',outbound_mode:'customer_pickup',planned_box_count:20}),batch=f.DB.batch;let injected=false;
 f.DB.batch=async statements=>{if(!injected&&statements.some(s=>s.sql?.includes('INSERT INTO v2_idempotency_keys')&&s.args?.includes('QA-BULK-CANCEL-RACE'))){injected=true;await f.ok('v2_outbound_order_update_status',{id:order.id,status:'cancelled'});}return batch(statements);};
 const reply=await f.call('sop_native_start',f.request('v2_bulk_op_job_start',{work_order_no:order.id},'A','QA-BULK-CANCEL-RACE'));assert.equal(injected,true);assert.equal(reply.ok,false);assert.equal(f.DB.raw.prepare('SELECT status FROM v2_outbound_orders WHERE id=?').get(order.id).status,'cancelled');assert.equal(f.DB.raw.prepare('SELECT COUNT(*) n FROM v2_ops_jobs').get().n,0);assert.equal(f.DB.raw.prepare('SELECT COUNT(*) n FROM v2_ops_job_workers').get().n,0);
});
test('legacy pick finalize rechecks no active workers inside its transaction and cannot close a newly joined picker',async t=>{
 const f=fixture(t),numbers=['QA-LEGACY-RACE-PICK'],j=await f.ok('v2_pick_job_start',{pick_doc_nos:numbers,worker_id:'QA-A',worker_name:'QA A'}),batch=f.DB.batch;let injected=false;
 f.DB.batch=async statements=>{if(!injected&&statements.some(s=>s.sql?.includes("'trip_finalize'"))){injected=true;await f.ok('v2_pick_job_start_by_docs',{pick_doc_nos:numbers,worker_id:'QA-B',worker_name:'QA B'});}return batch(statements);};
 const reply=await f.call('v2_pick_job_finalize',{job_id:j.job_id,worker_id:'QA-A'});assert.equal(injected,true);assert.equal(reply.ok,false);assert.equal(f.DB.raw.prepare('SELECT left_at FROM v2_ops_job_workers WHERE job_id=? AND worker_id=?').get(j.job_id,'QA-B').left_at,'');assert.notEqual(f.DB.raw.prepare('SELECT status FROM v2_ops_jobs WHERE id=?').get(j.job_id).status,'completed');assert.equal(f.DB.raw.prepare("SELECT COUNT(*) n FROM v2_ops_job_results WHERE job_id=? AND json_extract(result_json,'$.kind')='trip_finalize'").get(j.job_id).n,0);
});
test('legacy stock final completion cannot close another worker who joins after the last-person preflight',async t=>{
 const f=fixture(t),order=await f.ok('v2_outbound_order_create',{customer:'QA synthetic stock',biz_class:'bulk',outbound_mode:'customer_pickup',uses_stock_operation:1}),j=await f.ok('v2_outbound_stock_op_start',{outbound_order_id:order.id,worker_id:'QA-A',worker_name:'QA A'}),batch=f.DB.batch;let injected=false;
 f.DB.batch=async statements=>{if(!injected&&statements.some(s=>s.sql?.includes('INSERT INTO v2_ops_job_results')&&s.args?.includes('RES-FINAL-'+j.job_id))){injected=true;await f.ok('v2_outbound_stock_op_start',{outbound_order_id:order.id,worker_id:'QA-B',worker_name:'QA B'});}return batch(statements);};
 await f.call('v2_outbound_stock_op_finish',{job_id:j.job_id,worker_id:'QA-A',box_count:20});assert.equal(injected,true);assert.equal(f.DB.raw.prepare('SELECT left_at FROM v2_ops_job_workers WHERE job_id=? AND worker_id=?').get(j.job_id,'QA-B').left_at,'');assert.notEqual(f.DB.raw.prepare('SELECT status FROM v2_ops_jobs WHERE id=?').get(j.job_id).status,'completed');assert.equal(f.DB.raw.prepare('SELECT status FROM v2_outbound_orders WHERE id=?').get(order.id).status,'stock_operating');
});
test('unplanned unload without loans concurrently replays the same request as one successful dispatch',async t=>{const f=fixture(t),request=f.request('v2_unplanned_unload_start',{biz_class:'bulk'},'A','QA-UNPLANNED-CONCURRENT'),replies=await Promise.all([f.call('sop_native_start',request),f.call('sop_native_start',request)]);assert.ok(replies.every(r=>r.ok),JSON.stringify(replies));assert.equal(replies[0].job_id,replies[1].job_id);assert.equal(f.DB.raw.prepare('SELECT COUNT(*) n FROM v2_ops_jobs').get().n,1);assert.equal(f.DB.raw.prepare('SELECT COUNT(*) n FROM v2_field_feedbacks').get().n,1);});
test('different external inbound references on the same plan remain independently dispatchable in parallel',async t=>{
 const f=fixture(t),plan=await f.ok('v2_inbound_plan_create',{customer:'QA inbound parallel',biz_classes:['direct_ship'],external_inbound_nos:['QA-EXT-ONE','QA-EXT-TWO'],lines:[{unit_type:'carton',planned_qty:20}]}),unload=await f.ok('v2_unload_job_start',{plan_id:plan.id,worker_id:'QA-U',worker_name:'QA U',biz_class:'bulk'});await f.ok('v2_unload_job_finish',{job_id:unload.job_id,worker_id:'QA-U',complete_job:true,result_lines:[{unit_type:'carton',actual_qty:20}],box_count:20});
 const replies=await Promise.all(['QA-EXT-ONE','QA-EXT-TWO'].map((no,i)=>f.call('sop_native_start',f.request('v2_inbound_job_start',{plan_id:plan.id,external_inbound_no:no,biz_class:'direct_ship',job_type:'inbound_direct'},'PERSON-'+i))));assert.ok(replies.every(r=>r.ok),JSON.stringify(replies));assert.notEqual(replies[0].job_id,replies[1].job_id);assert.equal(f.DB.raw.prepare("SELECT COUNT(*) n FROM v2_ops_jobs WHERE job_type='inbound_direct'").get().n,2);
});
test('different external bulk numbers remain independently dispatchable in parallel',async t=>{const f=fixture(t),replies=await Promise.all(['QA-BULK-ONE','QA-BULK-TWO'].map((no,i)=>f.call('sop_native_start',f.request('v2_bulk_op_job_start',{work_order_no:no,customer:'QA customer'},'PERSON-'+i))));assert.ok(replies.every(r=>r.ok),JSON.stringify(replies));assert.notEqual(replies[0].job_id,replies[1].job_id);});
test('dispatching an unowned pending pick trip preserves the original job ID and its documents',async t=>{const f=fixture(t),j=await f.ok('v2_pick_job_start',{worker_id:'QA-CREATOR',pick_doc_nos:['QA-OLD-PICK']}),started=await f.ok('sop_native_start',f.request('v2_pick_job_start_by_docs',{pick_doc_nos:['QA-OLD-PICK']}));assert.equal(started.job_id,j.job_id);assert.equal(started.is_new_job,false);assert.equal(f.DB.raw.prepare('SELECT COUNT(*) n FROM v2_ops_jobs').get().n,1);});
