import {operationHeaders,rememberOperation,confirmOperation} from './office-operator-fixture.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import worker from '../worker-v2/index.js';import {database} from './d1-adapter.mjs';import {createOutboundBookingBatch} from '../worker-v2/outbound-booking-batch.js';
async function fixture(quantity=100){const DB=database(),user={id:'M',name:'QA manager',role:'manager',scope:'office'},env={DB,SOP_ENVIRONMENT:'staging',SOP_UPGRADE_ENABLED:'true',SOP_WORK_CHAIN_ENABLED:'true',SOP_ACCESS_CONTROL:'true',SOP_ACCEPT_NEW:'true',SOP_USERS_JSON:JSON.stringify([{...user,key:'batch-outbound-fixture-only'}])};let cookie='';const call=async(action,b={})=>{const r=await worker.fetch(new Request('https://fixture.test/api',{method:'POST',headers:{Cookie:cookie,...operationHeaders(cookie),'Content-Type':'application/json'},body:JSON.stringify({action,client_req_id:crypto.randomUUID(),...b})}),env);if(r.headers.has('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return rememberOperation(await r.json(),cookie);};await call('sop_login',{sop_key:'batch-outbound-fixture-only'});await confirmOperation(call,user.name);const created=await call('sop_need_create',{department:'bulk',source_type:'inventory',supply_chain_no:'QA-STOCK',customer:'QA booking',title:'QA work',instructions:'QA instruction',planned_quantity:quantity,planned_unit:'箱'});assert.equal(created.ok,true,created.error);const get=async()=> (await call('sop_get',{id:created.id})).record,n=await get();const booking=(q=20,fields={})=>({quantity:q,expected_ship_at:'2026-10-03',outbound_mode:'customer_pickup',destination:'QA destination',po_no:'QA PO',outbound_requirement:'QA transport note',...fields});const body=rows=>({id:n.id,revision:n.revision,outbounds:rows,client_req_id:crypto.randomUUID()});return{DB,env,user,call,get,n,booking,body};}
test('one booking action creates independent shipping fields, reserves the aggregate once, and replays original orders after lost acknowledgement',async()=>{
 const s=await fixture(),body=s.body([s.booking(30),s.booking(20,{expected_ship_at:'2026-10-04',outbound_mode:'milk_pallet',destination:'QA B',po_no:'QA PO B',outbound_requirement:'QA B note'})]),r=await s.call('v2_outbound_order_batch_create',body);assert.equal(r.ok,true,r.error);assert.equal(r.outbounds.length,2);assert.deepEqual(await s.call('v2_outbound_order_batch_create',body),r);assert.equal(s.DB.raw.prepare('SELECT count(*) n FROM v2_outbound_orders').get().n,2);
 const rows=s.DB.raw.prepare('SELECT * FROM v2_outbound_orders ORDER BY expected_ship_at').all();assert.equal(rows[0].planned_box_count,30);assert.equal(rows[1].planned_box_count,20);assert.equal(rows[1].po_no,'QA PO B');assert.equal(rows[1].outbound_mode,'milk_pallet');assert.equal(rows[1].destination,'QA B');assert.equal(rows[1].outbound_requirement,'QA B note');assert.equal(rows[1].instruction,s.n.instructions);assert.equal((await s.get()).links.length,2);assert.equal((await s.call('sop_work_need_search',{search:s.n.id})).items[0].remaining,50);
 assert.equal((await s.call('v2_outbound_order_batch_create',{...body,outbounds:[s.booking(31),body.outbounds[1]]})).ok,false);assert.equal((await s.call('v2_outbound_load_start',{order_id:r.outbounds[0].id,worker_id:'QA',worker_name:'QA'})).ok,false,'unreviewed work must not load');
});
test('same customer/date plans get unique public numbers; zero capacity, malformed rows, wrong units and field roles cannot book',async()=>{
 const s=await fixture(10),bad=[[],[s.booking(0)],[s.booking(11)],[s.booking(1,{expected_ship_at:'2026-02-30'})],[s.booking(1,{unit:'托'})],[s.booking(1,{outbound_mode:'fake'})]];for(const rows of bad)assert.equal((await s.call('v2_outbound_order_batch_create',s.body(rows))).ok,false);assert.equal(s.DB.raw.prepare('SELECT count(*) n FROM v2_outbound_orders').get().n,0);
 for(const user of [{...s.user,scope:'field'},{id:'D',name:'QA dispatch',role:'dispatcher',departments:['bulk']}])await assert.rejects(()=>createOutboundBookingBatch(s.body([s.booking(1)]),{...s.env,SOP_REQUEST_USER:user}),/办公室/);
 const r=await s.call('v2_outbound_order_batch_create',s.body([s.booking(5),s.booking(5)]));assert.equal(r.ok,true,r.error);assert.equal(new Set(r.outbounds.map(x=>x.display_no)).size,2);assert.equal((await s.call('sop_work_need_search',{search:s.n.id})).items[0].remaining,0);const n=await s.get();assert.equal((await s.call('v2_outbound_order_batch_create',{id:n.id,revision:n.revision,outbounds:[s.booking(1)]})).ok,false);
});
test('batch reservations include old bookings, cancelled reservations release capacity, and independent concurrent batches cannot oversell',async()=>{
 const s=await fixture(100),old=await s.call('v2_outbound_order_create',{customer:s.n.customer,biz_class:'bulk',outbound_mode:'customer_pickup',expected_ship_at:'2026-10-03',sop_existing_need_id:s.n.id,sop_need_revision:s.n.revision,sop_link_quantity:40});assert.equal(old.ok,true,old.error);let n=await s.get();assert.equal((await s.call('v2_outbound_order_batch_create',{id:n.id,revision:n.revision,outbounds:[s.booking(40),s.booking(30)]})).ok,false);
 await s.call('v2_outbound_order_update_status',{id:old.id,status:'cancelled'});n=await s.get();const base={id:n.id,revision:n.revision,outbounds:[s.booking(35),s.booking(35)]},results=await Promise.all([s.call('v2_outbound_order_batch_create',base),s.call('v2_outbound_order_batch_create',base)]);assert.equal(results.filter(x=>x.ok).length,1);assert.equal(s.DB.raw.prepare("SELECT count(*) n FROM v2_outbound_orders WHERE status!='cancelled'").get().n,2);assert.equal((await s.call('sop_work_need_search',{search:n.id})).items[0].remaining,30);
});
test('failure on the second order rolls back all orders and the requirement reservation; the same request can retry',async()=>{
 const s=await fixture(),body=s.body([s.booking(20),s.booking(20,{po_no:'QA FAIL'})]);s.DB.raw.exec("CREATE TRIGGER qa_fail_second_booking BEFORE INSERT ON v2_outbound_orders WHEN NEW.po_no='QA FAIL' BEGIN SELECT RAISE(ABORT,'QA second order failure'); END;");const r=await s.call('v2_outbound_order_batch_create',body);assert.equal(r.ok,false);assert.equal(s.DB.raw.prepare('SELECT count(*) n FROM v2_outbound_orders').get().n,0);assert.equal((await s.get()).revision,s.n.revision);assert.equal((await s.get()).links.length,0);s.DB.raw.exec('DROP TRIGGER qa_fail_second_booking');const retried=await s.call('v2_outbound_order_batch_create',body);assert.equal(retried.ok,true,retried.error);assert.equal(retried.outbounds.length,2);
});
test('committed-but-lost database acknowledgement and concurrent identical requests return one atomic booking set',async()=>{
 const s=await fixture(),original=s.DB.batch.bind(s.DB);let lost=false;s.DB.batch=async statements=>{const r=await original(statements);if(!lost&&statements.some(x=>x.sql.startsWith('INSERT INTO v2_outbound_orders'))){lost=true;throw Error('QA acknowledgement lost');}return r;};const body=s.body([s.booking(20),s.booking(20)]),r=await s.call('v2_outbound_order_batch_create',body);assert.equal(r.ok,true,r.error);assert.deepEqual(await s.call('v2_outbound_order_batch_create',body),r);assert.equal(s.DB.raw.prepare('SELECT count(*) n FROM v2_outbound_orders').get().n,2);
 const f=await fixture(),same=f.body([f.booking(20),f.booking(20)]),results=await Promise.all([f.call('v2_outbound_order_batch_create',same),f.call('v2_outbound_order_batch_create',same)]);assert.equal(results[0].ok,true,results[0].error);assert.deepEqual(results[0],results[1]);assert.equal(f.DB.raw.prepare('SELECT count(*) n FROM v2_outbound_orders').get().n,2);
});
test('reviewed pallet output preserves carton input and reserves pallets, including prior reservations, without new processing time',async()=>{
 const s=await fixture(100);s.DB.raw.prepare("UPDATE sop_records SET state=json_set(state,'$.result',json(?),'$.status','waiting_customer') WHERE id=?").run(JSON.stringify({quantity:4,unit:'托',description:'QA packed result'}),s.n.id);
 const r=await s.call('v2_outbound_order_batch_create',s.body([s.booking(2,{unit:'托'}),s.booking(1,{unit:'托'})]));assert.equal(r.ok,true,r.error);const n=await s.get();assert.equal(n.planned_quantity,100);assert.equal(n.planned_unit,'箱');assert.equal(n.status,'waiting_customer');assert.equal(n.links[0].phase,'confirmed');const orders=s.DB.raw.prepare('SELECT * FROM v2_outbound_orders').all();assert.deepEqual(orders.map(x=>x.planned_pallet_count).sort(),[1,2]);assert.equal(orders.every(x=>x.planned_box_count===0&&x.stock_operation_status==='completed'),true);assert.equal(s.DB.raw.prepare('SELECT count(*) n FROM v2_ops_job_workers').get().n,0);assert.equal((await s.call('sop_work_need_search',{search:n.id})).items[0].remaining,1);
});
