/**
 * CK Warehouse V2 — Collab Config & i18n
 * Shared config for collaboration center (/ck/002/)
 */

var V2_API = "https://ck-v2-api.ck91888.workers.dev";
var V2_KEY_STORAGE = "ck_v2_collab_k";
var V2_LANG_KEY = "ck_v2_lang";
var V2_USER_KEY = "ck_v2_collab_user";

// ===== i18n =====
var LANG = {
  zh: {
    app_title: "协同中心",
    app_subtitle: "入库计划 · 出库作业 · 问题点沟通 · 核对异常",
    login_title: "请输入访问码",
    login_placeholder: "访问码",
    login_btn: "进入",
    login_error: "访问码错误或网络异常",
    logout: "退出",
    lang_switch: "한국어",
    // Tabs
    tab_home: "今日看板",
    tab_issue: "问题点沟通",
    tab_outbound: "出库作业单",
    tab_inbound: "入库计划",
    tab_feedback: "现场反馈",
    tab_check: "核对中心",
    tab_ledger: "作业台账",
    // Actions
    new_issue: "+ 新建问题点",
    new_outbound: "+ 出库作业单",
    new_inbound: "+ 入库计划",
    new_feedback: "+ 现场反馈",
    // Fields
    date: "日期",
    customer: "客户",
    biz_class: "业务分类",
    status: "状态",
    priority: "优先级",
    submitted_by: "提出人",
    created_at: "创建时间",
    updated_at: "更新时间",
    remark: "备注",
    save: "保存",
    cancel: "取消",
    close_issue: "关闭问题",
    cancel_issue: "作废问题",
    back: "← 返回",
    refresh: "刷新",
    loading: "加载中...",
    no_data: "暂无数据",
    confirm: "确认",
    // Issue
    issue_summary: "问题摘要",
    issue_description: "问题描述",
    issue_type: "问题类型",
    related_doc_no: "关联单号",
    latest_feedback: "最新反馈",
    total_work_time: "累计处理工时",
    handle_history: "处理记录",
    attachments: "附件",
    // Status
    status_pending: "待处理",
    status_processing: "处理中",
    status_responded: "已反馈",
    status_completed: "已完成",
    status_closed: "已关闭",
    status_cancelled: "已取消",
    status_draft: "草稿",
    status_issued: "已下发",
    status_working: "作业中",
    status_arrived: "已到货",
    status_field_working: "现场卸货中",
    status_unloaded_pending_info: "已卸货·待补充",
    // Biz class
    biz_direct_ship: "代发",
    biz_bulk: "大货",
    biz_return: "退件",
    biz_import: "进口",
    // Priority
    priority_urgent: "紧急",
    priority_high: "高",
    priority_normal: "普通",
    priority_low: "低",
    // Inbound
    cargo_summary: "货物摘要",
    expected_arrival: "预计到达",
    purpose: "用途",
    plan_date: "计划日期",
    // Outbound
    order_date: "日期",
    operation_mode: "操作模式",
    outbound_mode: "出库模式",
    instruction: "作业说明",
    wms_order_no: "WMS工单号",
    sku: "SKU",
    quantity: "数量",
    add_line: "添加明细",
    // Dashboard
    today_issues: "今日问题点",
    today_outbound: "今日待执行出库",
    today_inbound: "今日待确认入库",
    today_feedback: "今日现场反馈",
    upcoming_inbound: "未来3工作日入库",
    minutes: "分钟",
    // Unit types
    unit_container_large: "大柜",
    unit_container_small: "小柜",
    unit_pallet: "托",
    unit_carton: "箱",
    unit_cbm: "方(CBM)",
    planned_qty: "计划数量",
    actual_qty: "实际数量",
    diff: "差异",
    diff_note: "差异说明",
    plan_lines: "货物明细",
    add_plan_line: "添加明细",
    auto_create_outbound: "同时创建出库单",
    qr_code: "QR码",
    print: "打印",
    // Feedback
    feedback_type: "反馈类型",
    feedback_unload_no_doc: "无单卸货",
    feedback_general: "一般反馈",
    convert_to_inbound: "转正为入库计划",
    status_open: "待处理",
    status_converted: "已转正",
  },
  ko: {
    app_title: "협업센터",
    app_subtitle: "입고계획 · 출고작업 · 이슈소통 · 확인/이상",
    login_title: "액세스 코드를 입력하세요",
    login_placeholder: "액세스 코드",
    login_btn: "입장",
    login_error: "비밀번호 오류 또는 네트워크 오류",
    logout: "로그아웃",
    lang_switch: "中文",
    tab_home: "오늘의 대시보드",
    tab_issue: "이슈 소통",
    tab_outbound: "출고 작업단",
    tab_inbound: "입고 계획",
    tab_feedback: "현장 피드백",
    tab_check: "확인 센터",
    tab_ledger: "작업 대장",
    new_issue: "+ 새 이슈",
    new_outbound: "+ 출고 작업단",
    new_inbound: "+ 입고 계획",
    new_feedback: "+ 현장 피드백",
    date: "날짜",
    customer: "고객",
    biz_class: "업무 분류",
    status: "상태",
    priority: "우선순위",
    submitted_by: "제출자",
    created_at: "생성 시간",
    updated_at: "업데이트 시간",
    remark: "비고",
    save: "저장",
    cancel: "취소",
    close_issue: "이슈 종료",
    cancel_issue: "이슈 취소",
    back: "← 뒤로",
    refresh: "새로고침",
    loading: "로딩중...",
    no_data: "데이터 없음",
    confirm: "확인",
    issue_summary: "이슈 요약",
    issue_description: "이슈 설명",
    issue_type: "이슈 유형",
    related_doc_no: "관련 번호",
    latest_feedback: "최신 피드백",
    total_work_time: "누적 처리 시간",
    handle_history: "처리 이력",
    attachments: "첨부파일",
    status_pending: "대기중",
    status_processing: "처리중",
    status_responded: "피드백완료",
    status_completed: "완료",
    status_closed: "종료",
    status_cancelled: "취소됨",
    status_draft: "초안",
    status_issued: "배정됨",
    status_working: "작업중",
    status_arrived: "도착",
    status_field_working: "현장 하차중",
    status_unloaded_pending_info: "하차완료·정보보완",
    biz_direct_ship: "직배송",
    biz_bulk: "대량화물",
    biz_return: "반품",
    biz_import: "수입",
    priority_urgent: "긴급",
    priority_high: "높음",
    priority_normal: "보통",
    priority_low: "낮음",
    cargo_summary: "화물 요약",
    expected_arrival: "예상 도착",
    purpose: "용도",
    plan_date: "계획 날짜",
    order_date: "날짜",
    operation_mode: "작업 모드",
    outbound_mode: "출고 모드",
    instruction: "작업 설명",
    wms_order_no: "WMS 주문번호",
    sku: "SKU",
    quantity: "수량",
    add_line: "명세 추가",
    today_issues: "오늘의 이슈",
    today_outbound: "오늘의 출고 대기",
    today_inbound: "오늘의 입고 대기",
    today_feedback: "오늘의 현장 피드백",
    upcoming_inbound: "향후 3영업일 입고",
    minutes: "분",
    unit_container_large: "대형 컨테이너",
    unit_container_small: "소형 컨테이너",
    unit_pallet: "팔레트",
    unit_carton: "박스",
    unit_cbm: "CBM",
    planned_qty: "계획 수량",
    actual_qty: "실제 수량",
    diff: "차이",
    diff_note: "차이 설명",
    plan_lines: "화물 명세",
    add_plan_line: "명세 추가",
    auto_create_outbound: "출고 작업단 동시 생성",
    qr_code: "QR코드",
    print: "인쇄",
    feedback_type: "피드백 유형",
    feedback_unload_no_doc: "서류없는 하차",
    feedback_general: "일반 피드백",
    convert_to_inbound: "입고계획으로 전환",
    status_open: "대기중",
    status_converted: "전환됨",
  }
};

function getLang() {
  return localStorage.getItem(V2_LANG_KEY) || "zh";
}

function setLang(lang) {
  localStorage.setItem(V2_LANG_KEY, lang);
}

function L(key) {
  var lang = getLang();
  var dict = LANG[lang] || LANG.zh;
  return dict[key] || (LANG.zh[key]) || key;
}

function esc(s) {
  return String(s || "").replace(/[&<>"']/g, function(c) {
    return ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c];
  });
}
