/**
 * CK Warehouse V2 — Collab Config & i18n
 * Shared config for collaboration center (/ck/002/)
 */

// workers.dev 在国内访问不稳定，生产环境统一使用自定义域名 api.ck91888.cn
var V2_API = "https://api.ck91888.cn";
var V2_KEY_STORAGE = "ck_v2_collab_k";
var V2_LANG_KEY = "ck_v2_lang";
var V2_USER_KEY = "ck_v2_collab_user";

// ===== i18n =====
var LANG = {
  zh: {
    app_title: "协同中心",
    app_subtitle: "入库计划 · 出库作业 · 问题点沟通 · 核对异常",
    login_title: "请输入访问码",
    login_placeholder: "访问码",
    login_btn: "进入",
    login_error: "访问码错误或网络异常",
    logout: "退出",
    lang_switch: "한국어",
    // Tabs
    tab_home: "今日看板",
    tab_issue: "问题点沟通",
    tab_outbound: "出库作业单",
    tab_inbound: "入库计划",
    tab_feedback: "现场反馈",
    tab_check: "核对中心",
    tab_ledger: "作业台账",
    // Actions
    new_issue: "+ 新建问题点",
    new_outbound: "+ 出库作业单",
    new_inbound: "+ 入库计划",
    new_feedback: "+ 现场反馈",
    // Fields
    date: "日期",
    customer: "客户",
    biz_class: "业务分类",
    status: "状态",
    priority: "优先级",
    submitted_by: "提出人",
    created_at: "创建时间",
    updated_at: "更新时间",
    remark: "备注",
    save: "保存",
    cancel: "取消",
    close_issue: "完成问题",
    cancel_issue: "作废问题",
    complete_issue: "完成问题（满意）",
    rework_issue: "追加处理（不满意）",
    confirm_complete_issue: "确认完成该问题点",
    rework_prompt: "请输入追加处理要求：",
    rework_sent: "已发送追加处理要求给现场",
    rework_note: "追加处理要求",
    status_rework_required: "需追加处理",
    back: "← 返回",
    refresh: "刷新",
    loading: "加载中...",
    no_data: "暂无数据",
    confirm: "确认",
    // Issue
    issue_summary: "问题摘要",
    issue_description: "问题描述",
    issue_type: "问题类型",
    related_doc_no: "关联单号",
    latest_feedback: "最新反馈",
    total_work_time: "累计处理工时",
    handle_history: "处理记录",
    attachments: "附件",
    vehicle_photos: "提货车辆照片",
    // Status
    status_pending: "待处理",
    status_processing: "处理中",
    status_responded: "已反馈",
    status_completed: "已完成",
    status_closed: "已关闭",
    status_cancelled: "已取消",
    status_pending_issue: "待下发",
    status_draft: "草稿",
    status_issued: "已下发",
    status_working: "操作中",
    status_ready_to_ship: "待出库",
    status_shipped: "已出库",
    status_reopen_pending: "待再操作",
    status_arrived: "已到货",
    status_field_working: "现场卸货中",
    status_unloaded_pending_info: "已卸货·待补充",
    status_unloading_putting_away: "卸货中+理货中",
    status_arrived_pending_putaway: "已到库待理货",
    status_putting_away: "理货中",
    // Biz class
    biz_direct_ship: "代发",
    biz_bulk: "大货",
    biz_return: "退件",
    biz_import: "进口",
    // Priority
    priority_urgent: "紧急",
    priority_high: "高",
    priority_normal: "普通",
    priority_low: "低",
    // Inbound
    cargo_summary: "货物摘要",
    expected_arrival: "预计到达",
    purpose: "用途",
    plan_date: "计划日期",
    // Outbound
    order_date: "日期",
    outbound_mode: "出库模式",
    instruction: "作业说明",
    destination: "目的地",
    po_no: "PO号 / 발주번호",
    wms_work_order_no: "WMS工单号",
    planned_box_count: "计划箱数",
    planned_pallet_count: "计划托数",
    actual_box_count: "实际箱数",
    actual_pallet_count: "实际托数",
    planned_box_pallet: "计划箱/托",
    actual_box_pallet: "实际箱/托",
    unit_box: "箱",
    unit_pallet: "托",
    planned_prefix: "计划",
    select_outbound_mode: "请选择出库模式",
    // Outbound mode enum
    outmode_warehouse_dispatch: "仓库叫车",
    outmode_customer_pickup: "客户自提",
    outmode_milk_express: "牛奶快递",
    outmode_milk_pallet: "牛奶托盘",
    outmode_container_pickup: "柜子提货",
    sku: "SKU",
    quantity: "数量",
    add_line: "添加明细",
    // Dashboard
    today_issues: "今日问题点",
    today_outbound: "今日待执行出库",
    today_inbound: "今日待确认入库",
    today_feedback: "今日现场反馈",
    upcoming_inbound: "未来3工作日入库",
    minutes: "分钟",
    // Unit types
    unit_container_large: "大柜",
    unit_container_small: "小柜",
    unit_pallet: "托",
    unit_carton: "箱",
    unit_cbm: "方(CBM)",
    planned_qty: "计划数量",
    actual_qty: "实际数量",
    diff: "差异",
    diff_note: "差异说明",
    plan_lines: "货物明细",
    add_plan_line: "添加明细",
    auto_create_outbound: "同时创建出库单",
    qr_code: "QR码",
    print: "打印",
    // Feedback
    feedback_type: "反馈类型",
    feedback_unload_no_doc: "无单卸货",
    feedback_general: "一般反馈",
    convert_to_inbound: "转正为入库计划",
    status_open: "待处理",
    status_converted: "已转正",
    // Order ops (按单操作)
    order_ops_title: "按单操作记录",
    order_ops_filter_all: "全部类型",
    order_ops_job_type_pick_direct: "代发拣货",
    order_ops_job_type_bulk_op: "大货操作",
    order_ops_job_type_load_outbound: "出库装货",
    order_ops_job_type_unload: "卸货",
    order_ops_job_type_inbound_direct: "代发入库",
    order_ops_job_type_inbound_bulk: "大货入库",
    order_ops_job_type_inbound_return: "退件入库",
    order_ops_job_type_sort: "分拣",
    order_ops_job_type_check: "核对",
    order_ops_job_type_pickup_delivery_import: "外出取/送货",
    order_ops_search: "查询",
    order_ops_back_to_list: "← 返回列表",
    order_ops_col_type: "类型",
    order_ops_col_trip_or_work: "趟次/工单",
    order_ops_col_doc: "单号",
    order_ops_col_people: "参与人员",
    order_ops_col_count: "人数",
    order_ops_col_time: "开始时间",
    order_ops_col_status: "状态",
    order_ops_col_ops: "操作",
    order_ops_detail_base_info: "基础信息",
    order_ops_detail_pick_docs: "拣货单号",
    order_ops_detail_workers: "参与人员",
    order_ops_detail_results: "操作结果",
    order_ops_field_status: "状态",
    order_ops_field_biz_class: "业务分类",
    order_ops_field_job_type: "作业类型",
    order_ops_field_trip_no: "趟次号",
    order_ops_field_work_order: "工单号",
    order_ops_field_started_at: "开始时间",
    order_ops_field_updated_at: "更新时间",
    order_ops_field_active_count: "当前在岗",
    order_ops_field_creator: "发起人",
    order_ops_status_pending: "待开始",
    order_ops_status_working: "进行中",
    order_ops_status_awaiting_close: "待续作业",
    order_ops_status_completed: "已完成",
    order_ops_status_cancelled: "已取消",
    order_ops_flow_order_op: "按单操作",
    order_ops_leave_reason_leave: "暂离",
    order_ops_leave_reason_finished: "完成",
    order_ops_leave_reason_job_completed: "任务关闭",
    order_ops_leave_reason_interrupted: "被中断",
    order_ops_leave_reason_admin_cleanup: "主管清理",
    order_ops_view_detail: "详情",
    set_reopen_pending: "设为待再操作",
  },
  ko: {
    app_title: "협업센터",
    app_subtitle: "입고계획 · 출고작업 · 이슈소통 · 확인/이상",
    login_title: "액세스 코드를 입력하세요",
    login_placeholder: "액세스 코드",
    login_btn: "입장",
    login_error: "비밀번호 오류 또는 네트워크 오류",
    logout: "로그아웃",
    lang_switch: "中文",
    tab_home: "오늘의 대시보드",
    tab_issue: "이슈 소통",
    tab_outbound: "출고 작업단",
    tab_inbound: "입고 계획",
    tab_feedback: "현장 피드백",
    tab_check: "확인 센터",
    tab_ledger: "작업 대장",
    new_issue: "+ 새 이슈",
    new_outbound: "+ 출고 작업단",
    new_inbound: "+ 입고 계획",
    new_feedback: "+ 현장 피드백",
    date: "날짜",
    customer: "고객",
    biz_class: "업무 분류",
    status: "상태",
    priority: "우선순위",
    submitted_by: "제출자",
    created_at: "생성 시간",
    updated_at: "업데이트 시간",
    remark: "비고",
    save: "저장",
    cancel: "취소",
    close_issue: "이슈 완료",
    cancel_issue: "이슈 취소",
    complete_issue: "이슈 완료 (만족)",
    rework_issue: "추가 처리 요청 (불만족)",
    confirm_complete_issue: "이 이슈를 완료 처리하시겠습니까",
    rework_prompt: "추가 처리 요청 내용을 입력하세요:",
    rework_sent: "추가 처리 요청이 현장으로 전송되었습니다",
    rework_note: "추가 처리 요청",
    status_rework_required: "추가처리필요",
    back: "← 뒤로",
    refresh: "새로고침",
    loading: "로딩중...",
    no_data: "데이터 없음",
    confirm: "확인",
    issue_summary: "이슈 요약",
    issue_description: "이슈 설명",
    issue_type: "이슈 유형",
    related_doc_no: "관련 번호",
    latest_feedback: "최신 피드백",
    total_work_time: "누적 처리 시간",
    handle_history: "처리 이력",
    attachments: "첨부파일",
    vehicle_photos: "차량 사진",
    status_pending: "대기중",
    status_processing: "처리중",
    status_responded: "피드백완료",
    status_completed: "완료",
    status_closed: "종료",
    status_cancelled: "취소됨",
    status_pending_issue: "배정대기",
    status_draft: "초안",
    status_issued: "배정됨",
    status_working: "작업중",
    status_ready_to_ship: "출고대기",
    status_shipped: "출고완료",
    status_reopen_pending: "재작업 대기",
    status_arrived: "도착",
    status_field_working: "현장 하차중",
    status_unloaded_pending_info: "하차완료·정보보완",
    status_unloading_putting_away: "하차중+입고중",
    status_arrived_pending_putaway: "입고대기",
    status_putting_away: "입고중",
    biz_direct_ship: "직배송",
    biz_bulk: "대량화물",
    biz_return: "반품",
    biz_import: "수입",
    priority_urgent: "긴급",
    priority_high: "높음",
    priority_normal: "보통",
    priority_low: "낮음",
    cargo_summary: "화물 요약",
    expected_arrival: "예상 도착",
    purpose: "용도",
    plan_date: "계획 날짜",
    order_date: "날짜",
    outbound_mode: "출고 모드",
    instruction: "작업 설명",
    destination: "목적지",
    po_no: "PO번호 / 발주번호",
    wms_work_order_no: "WMS 작업지시번호",
    planned_box_count: "계획 박스 수",
    planned_pallet_count: "계획 팔레트 수",
    actual_box_count: "실적 박스 수",
    actual_pallet_count: "실적 팔레트 수",
    planned_box_pallet: "계획 박스/팔레트",
    actual_box_pallet: "실적 박스/팔레트",
    unit_box: "박스",
    unit_pallet: "팔레트",
    planned_prefix: "계획",
    select_outbound_mode: "출고 모드를 선택하세요",
    outmode_warehouse_dispatch: "창고 차량 배차",
    outmode_customer_pickup: "고객 자가 픽업",
    outmode_milk_express: "밀크런 택배",
    outmode_milk_pallet: "밀크런 팔레트",
    outmode_container_pickup: "컨테이너 픽업",
    sku: "SKU",
    quantity: "수량",
    add_line: "명세 추가",
    today_issues: "오늘의 이슈",
    today_outbound: "오늘의 출고 대기",
    today_inbound: "오늘의 입고 대기",
    today_feedback: "오늘의 현장 피드백",
    upcoming_inbound: "향후 3영업일 입고",
    minutes: "분",
    unit_container_large: "대형 컨테이너",
    unit_container_small: "소형 컨테이너",
    unit_pallet: "팔레트",
    unit_carton: "박스",
    unit_cbm: "CBM",
    planned_qty: "계획 수량",
    actual_qty: "실제 수량",
    diff: "차이",
    diff_note: "차이 설명",
    plan_lines: "화물 명세",
    add_plan_line: "명세 추가",
    auto_create_outbound: "출고 작업단 동시 생성",
    qr_code: "QR코드",
    print: "인쇄",
    feedback_type: "피드백 유형",
    feedback_unload_no_doc: "서류없는 하차",
    feedback_general: "일반 피드백",
    convert_to_inbound: "입고계획으로 전환",
    status_open: "대기중",
    status_converted: "전환됨",
    // Order ops (주문별 작업)
    order_ops_title: "주문별 작업 기록",
    order_ops_filter_all: "전체 유형",
    order_ops_job_type_pick_direct: "직배송 피킹",
    order_ops_job_type_bulk_op: "대량화물 작업",
    order_ops_job_type_load_outbound: "출고 상차",
    order_ops_job_type_unload: "하차",
    order_ops_job_type_inbound_direct: "직배송 입고",
    order_ops_job_type_inbound_bulk: "대량화물 입고",
    order_ops_job_type_inbound_return: "반품 입고",
    order_ops_job_type_sort: "분류",
    order_ops_job_type_check: "검수",
    order_ops_job_type_pickup_delivery_import: "외부 픽업·배송",
    order_ops_search: "조회",
    order_ops_back_to_list: "← 목록으로",
    order_ops_col_type: "유형",
    order_ops_col_trip_or_work: "트립/공정",
    order_ops_col_doc: "번호",
    order_ops_col_people: "참여 작업자",
    order_ops_col_count: "인원수",
    order_ops_col_time: "시작 시간",
    order_ops_col_status: "상태",
    order_ops_col_ops: "작업",
    order_ops_detail_base_info: "기본 정보",
    order_ops_detail_pick_docs: "피킹 번호",
    order_ops_detail_workers: "참여 작업자",
    order_ops_detail_results: "작업 결과",
    order_ops_field_status: "상태",
    order_ops_field_biz_class: "업무 분류",
    order_ops_field_job_type: "작업 유형",
    order_ops_field_trip_no: "트립 번호",
    order_ops_field_work_order: "공정 번호",
    order_ops_field_started_at: "시작 시간",
    order_ops_field_updated_at: "업데이트 시간",
    order_ops_field_active_count: "현재 근무",
    order_ops_field_creator: "개시자",
    order_ops_status_pending: "대기",
    order_ops_status_working: "진행중",
    order_ops_status_awaiting_close: "작업 대기",
    order_ops_status_completed: "완료",
    order_ops_status_cancelled: "취소됨",
    order_ops_flow_order_op: "주문별 작업",
    order_ops_leave_reason_leave: "일시 퇴장",
    order_ops_leave_reason_finished: "완료",
    order_ops_leave_reason_job_completed: "작업 종료",
    order_ops_leave_reason_interrupted: "중단됨",
    order_ops_leave_reason_admin_cleanup: "관리자 정리",
    order_ops_view_detail: "상세",
    set_reopen_pending: "재작업 대기로 변경",
  }
};

function getLang() {
  return localStorage.getItem(V2_LANG_KEY) || "zh";
}

function setLang(lang) {
  localStorage.setItem(V2_LANG_KEY, lang);
}

function L(key) {
  var lang = getLang();
  var dict = LANG[lang] || LANG.zh;
  return dict[key] || (LANG.zh[key]) || key;
}

function esc(s) {
  return String(s || "").replace(/[&<>"']/g, function(c) {
    return ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c];
  });
}
