/**
 * CK Warehouse V2 — 003 Consumables & Assets
 * 耗材与物品管理 / 소모품·비품 관리
 */
var V2_API = "https://api.ck91888.cn";
var V2_003_OPS_KEY_STORAGE = "ck_v2_003_ops_key";
var V2_003_AUTH_KEY = "ck_v2_003_auth";
var V2_003_ROLE_KEY = "ck_v2_003_role";
var V2_003_BADGE_KEY = "ck_v2_003_badge";
var V2_003_BADGE_DAY_KEY = "ck_v2_003_badge_day";
var V2_003_LANG_KEY = "ck_v2_003_lang";
var V2_003_ADMIN_NAME_KEY = "ck_v2_003_admin_name";

var LANG = {
  zh: {
    app_title: "耗材与物品管理",
    app_subtitle: "CK 仓库 · 仁川",
    field_entry: "现场使用",
    field_entry_sub: "扫工牌领用、消耗或归还",
    admin_entry: "管理后台",
    admin_entry_sub: "建档、入库、盘点与统计",
    back_home: "返回系统首页",
    badge_title: "请扫描工牌",
    badge_hint: "识别操作人后才能记录领用和归还",
    scan_badge: "开始扫码",
    manual_badge: "手动输入工牌",
    admin_login: "管理员登录",
    access_code: "请输入访问码",
    enter: "进入系统",
    back: "返回",
    logout: "退出",
    switch_lang: "한국어",
    dashboard: "总览",
    materials: "耗材",
    assets: "仓库物品",
    ledger: "出入记录",
    settings: "基础设置",
    material_count: "耗材种类",
    low_stock: "库存预警",
    asset_count: "物品总数",
    assigned_assets: "已领用物品",
    repair_assets: "维修中",
    today_records: "今日记录",
    recent_activity: "最近动态",
    no_data: "暂无数据",
    loading: "加载中...",
    search: "搜索名称、编号或条码",
    all_categories: "全部分类",
    all_statuses: "全部状态",
    only_low: "只看库存预警",
    query: "查询",
    scan_item: "扫码查找",
    add_material: "新增耗材",
    add_asset: "新增物品",
    current_stock: "当前库存",
    min_stock: "最低库存",
    warehouse: "仓库",
    location: "位置/货位",
    category: "分类",
    spec: "规格",
    unit: "单位",
    status: "状态",
    supplier: "供应商",
    cost: "单价",
    note: "备注",
    edit: "修改资料",
    inbound: "入库",
    issue: "领用",
    use: "消耗",
    return_item: "退回",
    adjust: "库存调整",
    stocktake: "盘点",
    transaction_history: "库存流水",
    material_code: "耗材编号",
    barcode: "条码（可选）",
    name_zh: "中文名称",
    name_ko: "韩文名称（可选）",
    opening_qty: "期初库存",
    active: "启用",
    inactive: "停用",
    save: "保存",
    cancel: "取消",
    qty: "数量",
    counted_qty: "实盘数量",
    delta_qty: "调整数量（可填负数）",
    recipient: "领用人",
    purpose: "用途",
    related_doc: "关联单号/任务",
    operator: "操作人",
    time: "时间",
    before_qty: "操作前",
    after_qty: "操作后",
    confirm_submit: "确认提交",
    asset_code: "物品编号",
    asset_name: "物品名称",
    brand: "品牌",
    model: "型号",
    serial_no: "序列号",
    keeper: "当前领用人",
    purchase_date: "购买日期",
    purchase_cost: "采购价格",
    warranty_until: "保修截止",
    available: "在库可用",
    assigned: "已领用",
    repair: "维修中",
    retired: "已报废",
    lost: "遗失",
    assign: "领用物品",
    return_asset: "归还物品",
    transfer: "调拨位置",
    repair_start: "送修",
    repair_done: "维修完成",
    retire: "报废",
    mark_lost: "标记遗失",
    print_qr: "打印二维码",
    upload_photo: "上传照片",
    photos: "物品照片",
    asset_history: "物品流转记录",
    all_records: "全部记录",
    material_records: "耗材记录",
    asset_records: "物品记录",
    start_date: "开始日期",
    end_date: "结束日期",
    export_csv: "导出 CSV",
    locations: "仓库与位置",
    add_location: "新增位置",
    location_code: "位置编码",
    location_name: "位置名称",
    success: "操作成功",
    failed: "操作失败",
    scan_title: "扫描耗材或物品二维码",
    manual_code: "手动输入编号/条码",
    start_scan: "开始扫描",
    close: "关闭",
    not_found: "没有找到对应记录",
    confirm_action: "请确认本次操作信息",
    low_stock_badge: "库存不足",
    field_mode: "现场端",
    admin_mode: "管理员",
    viewer_mode: "只读",
    change_name: "修改操作人姓名",
    required_fields: "请填写必填项",
    confirm_retire: "确定报废这件物品吗？",
    confirm_lost: "确定将这件物品标记为遗失吗？",
    photo_uploaded: "照片上传成功"
  },
  ko: {
    app_title: "소모품·비품 관리",
    app_subtitle: "CK 창고 · 인천",
    field_entry: "현장 사용",
    field_entry_sub: "명찰 스캔 후 수령·사용·반납",
    admin_entry: "관리자 화면",
    admin_entry_sub: "등록·입고·재고조사·통계",
    back_home: "시스템 홈으로",
    badge_title: "명찰을 스캔하세요",
    badge_hint: "수령 및 반납 기록을 위해 작업자 확인이 필요합니다",
    scan_badge: "스캔 시작",
    manual_badge: "명찰 직접 입력",
    admin_login: "관리자 로그인",
    access_code: "접근 코드를 입력하세요",
    enter: "시스템 입장",
    back: "뒤로",
    logout: "로그아웃",
    switch_lang: "中文",
    dashboard: "현황",
    materials: "소모품",
    assets: "창고 비품",
    ledger: "입출고 기록",
    settings: "기초 설정",
    material_count: "소모품 종류",
    low_stock: "재고 경고",
    asset_count: "비품 총수",
    assigned_assets: "사용 중 비품",
    repair_assets: "수리 중",
    today_records: "오늘 기록",
    recent_activity: "최근 활동",
    no_data: "데이터 없음",
    loading: "로딩중...",
    search: "이름·번호·바코드 검색",
    all_categories: "전체 분류",
    all_statuses: "전체 상태",
    only_low: "재고 경고만",
    query: "검색",
    scan_item: "스캔 검색",
    add_material: "소모품 추가",
    add_asset: "비품 추가",
    current_stock: "현재 재고",
    min_stock: "최소 재고",
    warehouse: "창고",
    location: "위치/로케이션",
    category: "분류",
    spec: "규격",
    unit: "단위",
    status: "상태",
    supplier: "공급업체",
    cost: "단가",
    note: "비고",
    edit: "정보 수정",
    inbound: "입고",
    issue: "수령",
    use: "사용",
    return_item: "반납",
    adjust: "재고 조정",
    stocktake: "재고 조사",
    transaction_history: "재고 이력",
    material_code: "소모품 번호",
    barcode: "바코드 (선택)",
    name_zh: "중문 명칭",
    name_ko: "한글 명칭 (선택)",
    opening_qty: "기초 재고",
    active: "사용",
    inactive: "미사용",
    save: "저장",
    cancel: "취소",
    qty: "수량",
    counted_qty: "실사 수량",
    delta_qty: "조정 수량 (음수 가능)",
    recipient: "수령인",
    purpose: "용도",
    related_doc: "관련 번호/작업",
    operator: "작업자",
    time: "시간",
    before_qty: "작업 전",
    after_qty: "작업 후",
    confirm_submit: "확인 제출",
    asset_code: "비품 번호",
    asset_name: "비품명",
    brand: "브랜드",
    model: "모델",
    serial_no: "시리얼 번호",
    keeper: "현재 사용자",
    purchase_date: "구매일",
    purchase_cost: "구매 가격",
    warranty_until: "보증 만료",
    available: "사용 가능",
    assigned: "사용 중",
    repair: "수리 중",
    retired: "폐기",
    lost: "분실",
    assign: "비품 수령",
    return_asset: "비품 반납",
    transfer: "위치 이동",
    repair_start: "수리 접수",
    repair_done: "수리 완료",
    retire: "폐기",
    mark_lost: "분실 처리",
    print_qr: "QR 인쇄",
    upload_photo: "사진 업로드",
    photos: "비품 사진",
    asset_history: "비품 이동 이력",
    all_records: "전체 기록",
    material_records: "소모품 기록",
    asset_records: "비품 기록",
    start_date: "시작일",
    end_date: "종료일",
    export_csv: "CSV 내보내기",
    locations: "창고 및 위치",
    add_location: "위치 추가",
    location_code: "위치 코드",
    location_name: "위치명",
    success: "처리 완료",
    failed: "처리 실패",
    scan_title: "소모품 또는 비품 QR 스캔",
    manual_code: "번호/바코드 직접 입력",
    start_scan: "스캔 시작",
    close: "닫기",
    not_found: "해당 기록을 찾을 수 없습니다",
    confirm_action: "작업 정보를 확인하세요",
    low_stock_badge: "재고 부족",
    field_mode: "현장",
    admin_mode: "관리자",
    viewer_mode: "읽기 전용",
    change_name: "작업자 이름 변경",
    required_fields: "필수 항목을 입력하세요",
    confirm_retire: "이 비품을 폐기 처리하시겠습니까?",
    confirm_lost: "이 비품을 분실 처리하시겠습니까?",
    photo_uploaded: "사진 업로드 완료"
  }
};

var MATERIAL_CATEGORIES = ["纸箱", "胶带", "标签", "打包膜", "托盘", "办公用品", "劳保用品", "清洁用品", "设备耗材", "其他"];
var ASSET_CATEGORIES = ["PDA", "打印机", "电子秤", "电脑", "叉车", "地牛", "推车", "工具", "货架", "网络设备", "监控设备", "其他"];
var MATERIAL_UNITS = ["个", "只", "卷", "张", "箱", "包", "瓶", "套", "块", "台", "kg", "m"];
