/**
 * CK Warehouse V2 — 003 Consumables & Assets
 * 耗材与物品管理 / 소모품·비품 관리
 */
var V2_API = "https://api.ck91888.cn";
var V2_003_AUTH_KEY = "ck_v2_003_auth";
var V2_003_ROLE_KEY = "ck_v2_003_role";
var V2_003_BADGE_KEY = "ck_v2_003_badge";
var V2_003_BADGE_DAY_KEY = "ck_v2_003_badge_day";
var V2_003_LANG_KEY = "ck_v2_003_lang";
var V2_003_ADMIN_NAME_KEY = "ck_v2_003_admin_name";

var LANG = {
  zh: {
    app_title: "耗材与物品管理",
    app_subtitle: "CK 仓库 · 仁川",
    field_entry: "现场使用",
    field_entry_sub: "扫工牌领用、消耗或归还",
    admin_entry: "管理后台",
    admin_entry_sub: "建档、入库、盘点与统计",
    back_home: "返回系统首页",
    badge_title: "请扫描工牌",
    badge_hint: "识别操作人后才能记录领用和归还",
    scan_badge: "开始扫码",
    manual_badge: "手动输入工牌",
    admin_login: "管理员登录",
    access_code: "请输入访问码",
    enter: "进入系统",
    back: "返回",
    logout: "退出",
    switch_lang: "한국어",
    dashboard: "总览",
    workbench: "工作台",
    materials: "耗材",
    assets: "物品",
    field_assets: "物品",
    purchasing: "采购到货",
    receiving: "收货",
    ledger: "出入记录",
    my_records: "我的记录",
    settings: "基础设置",
    material_count: "耗材种类",
    low_stock: "库存预警",
    asset_count: "物品总数",
    assigned_assets: "已领用物品",
    repair_assets: "维修中",
    today_records: "今日记录",
    recent_activity: "最近动态",
    department_usage: "部门耗材统计",
    department_usage_hint: "按部门、耗材和单位分别统计领用、消耗与退回",
    all_departments: "全部部门",
    department: "使用部门",
    choose_department: "请选择部门",
    department_direct: "代发",
    department_bulk: "大货",
    department_import: "进口",
    hello: "你好",
    field_ready: "请选择要办理的现场操作",
    my_today_records: "我今日操作",
    scan_to_operate: "扫描耗材或物品",
    scan_to_operate_sub: "扫码后直接领用、消耗或归还",
    material_work: "耗材操作",
    material_work_sub: "搜索并办理领用、消耗、退回",
    asset_work: "物品操作",
    asset_work_sub: "领用、归还或转移物品",
    my_records_sub: "只查看本人提交的操作",
    my_recent_activity: "我的最近操作",
    request_purchase: "申请采购",
    request_purchase_sub: "选择已备案耗材并填写预计需求量",
    arrival_receiving: "到货收货",
    arrival_receiving_sub: "扫描快递单或办理供应商送货",
    no_data: "暂无数据",
    loading: "加载中...",
    search: "搜索名称、编号或条码",
    all_categories: "全部分类",
    all_statuses: "全部状态",
    only_low: "只看库存预警",
    query: "查询",
    scan_item: "扫码查找",
    add_material: "新增耗材",
    bulk_import: "表格批量导入",
    bulk_import_materials: "批量导入耗材",
    import_step_1: "1. 下载模板并填写耗材",
    import_update_hint: "耗材编号或条码与现有记录一致时更新资料；期初库存只对新建耗材生效。",
    download_template: "下载 Excel 模板",
    choose_spreadsheet: "选择 Excel 或 CSV 文件",
    import_waiting: "尚未选择文件",
    confirm_import: "确认批量导入",
    add_asset: "新增物品",
    current_stock: "当前库存",
    min_stock: "最低库存",
    location: "位置/货位",
    storage_location: "存放位置/货位（可选）",
    category: "分类",
    spec: "规格",
    unit: "单位",
    status: "状态",
    supplier: "供应商",
    cost: "单价",
    note: "备注",
    edit: "修改资料",
    delete_material: "删除耗材",
    confirm_delete_material: "确定永久删除“{name}”吗？\n\n只有库存为 0 且没有库存、采购、发货或收货记录的耗材才能删除。此操作无法撤销。",
    material_deleted: "耗材已删除",
    material_archived: "耗材已有业务记录，已改为停用",
    delete_blocked_archive: "该耗材不能永久删除：{reason}。\n\n是否改为停用？停用后历史记录仍会保留。",
    delete_reason_stock: "当前库存 {qty}",
    delete_reason_history: "库存流水 {count} 条",
    delete_reason_purchase: "采购记录 {count} 条",
    delete_reason_shipping: "发货/收货记录 {count} 条",
    inbound: "入库",
    issue: "领用",
    use: "消耗",
    return_item: "退回",
    adjust: "库存调整",
    stocktake: "盘点",
    transaction_history: "库存流水",
    material_code: "耗材编号",
    barcode: "条码（可选）",
    name_zh: "中文名称",
    name_ko: "韩文名称（可选）",
    opening_qty: "期初库存",
    active: "启用",
    inactive: "停用",
    save: "保存",
    cancel: "取消",
    qty: "数量",
    counted_qty: "实盘数量",
    delta_qty: "调整数量（可填负数）",
    recipient: "领用人",
    purpose: "用途",
    related_doc: "关联单号/任务",
    operator: "操作人",
    time: "时间",
    before_qty: "操作前",
    after_qty: "操作后",
    confirm_submit: "确认提交",
    asset_code: "物品编号",
    asset_name: "物品名称",
    brand: "品牌",
    model: "型号",
    serial_no: "序列号",
    keeper: "当前领用人",
    purchase_date: "购买日期",
    purchase_cost: "采购价格",
    warranty_until: "保修截止",
    available: "在库可用",
    assigned: "已领用",
    repair: "维修中",
    retired: "已报废",
    lost: "遗失",
    assign: "领用物品",
    return_asset: "归还物品",
    transfer: "变更存放位置",
    repair_start: "送修",
    repair_done: "维修完成",
    retire: "报废",
    mark_lost: "标记遗失",
    print_qr: "打印二维码",
    upload_photo: "上传照片",
    photos: "物品照片",
    asset_history: "物品流转记录",
    all_records: "全部记录",
    material_records: "耗材记录",
    asset_records: "物品记录",
    start_date: "开始日期",
    end_date: "结束日期",
    export_csv: "导出 CSV",
    locations: "存放位置",
    add_location: "新增位置",
    location_code: "位置编码",
    location_name: "位置名称",
    success: "操作成功",
    failed: "操作失败",
    scan_title: "扫描耗材或物品二维码",
    manual_code: "手动输入编号/条码",
    start_scan: "开始扫描",
    close: "关闭",
    not_found: "没有找到对应记录",
    confirm_action: "请确认本次操作信息",
    low_stock_badge: "库存不足",
    field_mode: "现场端",
    admin_mode: "管理员",
    viewer_mode: "只读",
    change_name: "修改操作人姓名",
    required_fields: "请填写必填项",
    confirm_retire: "确定报废这件物品吗？",
    confirm_lost: "确定将这件物品标记为遗失吗？",
    photo_uploaded: "照片上传成功",
    purchase_search: "搜索采购单、快递单、供应商",
    status_requested: "待采购",
    status_purchasing: "采购中",
    status_shipped: "已发货待收货",
    status_partial: "部分到货",
    status_completed: "全部到货",
    status_cancelled: "已取消",
    only_discrepancy: "只看有差异",
    new_purchase_request: "新建采购申请",
    receiving_desk: "收货工作台",
    receiving_hint: "扫描快递面单，或从待到货列表选择供应商送货",
    scan_tracking: "扫描快递单号",
    tracking_or_shipment: "输入快递单号或系统到货单号",
    pending_express: "待收快递",
    pending_supplier: "待收供应商送货",
    urgency: "紧急程度",
    normal: "普通",
    urgent: "紧急",
    request_reason: "申请原因",
    choose_material: "请选择已备案耗材",
    choose_material_action: "选择耗材",
    material_selection_hint: "必须从已备案耗材中点选，不能只输入相似名称",
    material_search: "搜索名称、编号或规格",
    material_picker_title: "选择已备案耗材",
    material_picker_hint: "输入文字只用于搜索，点中一条已备案耗材后才算选择成功",
    material_no_match: "没有找到匹配耗材，请联系管理员先备案",
    add_line: "添加",
    add_material_hint: "请先添加需要采购的耗材",
    submit_request: "提交申请",
    purchase_ordering: "采购下单",
    purchase_channel: "采购渠道",
    platform_order_no: "平台订单号",
    expected_date: "预计到货日期",
    ordered_items: "实际采购明细",
    save_purchase: "保存采购结果",
    register_shipment: "登记发货/送货",
    express_delivery: "快递发货",
    supplier_delivery: "供应商送货",
    tracking_no: "快递单号",
    shipment_items: "本批发货明细",
    confirm_shipment: "确认登记",
    requested_qty: "预计需求量",
    requested_qty_hint: "仓库填写大概需要多少；实际采购量由采购负责人下单时填写",
    ordered_qty: "实际采购量",
    actual_purchase_hint: "预计需求量只作参考，请按实际下单数量逐项填写；没有购买的填 0",
    actual_qty_placeholder: "填写实际数量",
    received_qty: "已到数量",
    expected_qty: "预计数量",
    actual_received: "实际收到",
    putaway_location: "上架位置",
    difference_note: "差异说明",
    discrepancy: "存在差异",
    requester: "申请人",
    purchaser: "采购人",
    shipment_no: "到货单号",
    delivery_method: "送货方式",
    arrival_photos: "到货照片",
    take_arrival_photo: "拍摄到货照片",
    photo_required: "供应商送货必须先拍摄至少一张到货照片",
    confirm_receipt: "确认收货并入库",
    receipt_success: "收货完成，库存已更新",
    already_received: "该到货单已经收货，不能重复入库",
    start_purchase: "采购下单",
    add_shipment: "登记发货",
    cancel_order: "取消采购单",
    close_difference: "按差异关闭",
    received_progress: "到货进度",
    no_pending: "暂无待收货记录",
    view_details: "查看详情",
    purchase_pending_count: "待采购",
    waiting_receipt_count: "待收货",
    partial_count: "部分到货",
    difference_count: "异常差异"
  },
  ko: {
    app_title: "소모품·비품 관리",
    app_subtitle: "CK 창고 · 인천",
    field_entry: "현장 사용",
    field_entry_sub: "명찰 스캔 후 수령·사용·반납",
    admin_entry: "관리자 화면",
    admin_entry_sub: "등록·입고·재고조사·통계",
    back_home: "시스템 홈으로",
    badge_title: "명찰을 스캔하세요",
    badge_hint: "수령 및 반납 기록을 위해 작업자 확인이 필요합니다",
    scan_badge: "스캔 시작",
    manual_badge: "명찰 직접 입력",
    admin_login: "관리자 로그인",
    access_code: "접근 코드를 입력하세요",
    enter: "시스템 입장",
    back: "뒤로",
    logout: "로그아웃",
    switch_lang: "中文",
    dashboard: "현황",
    workbench: "작업대",
    materials: "소모품",
    assets: "비품",
    field_assets: "비품",
    purchasing: "구매·입고",
    receiving: "입고",
    ledger: "입출고 기록",
    my_records: "내 기록",
    settings: "기초 설정",
    material_count: "소모품 종류",
    low_stock: "재고 경고",
    asset_count: "비품 총수",
    assigned_assets: "사용 중 비품",
    repair_assets: "수리 중",
    today_records: "오늘 기록",
    recent_activity: "최근 활동",
    department_usage: "부서별 소모품 통계",
    department_usage_hint: "부서·소모품·단위별 수령, 사용, 반납 수량",
    all_departments: "전체 부서",
    department: "사용 부서",
    choose_department: "부서를 선택하세요",
    department_direct: "배송대행",
    department_bulk: "대형화물",
    department_import: "수입",
    hello: "안녕하세요",
    field_ready: "처리할 현장 작업을 선택하세요",
    my_today_records: "오늘 내 작업",
    scan_to_operate: "소모품·비품 스캔",
    scan_to_operate_sub: "스캔 후 수령·사용·반납 처리",
    material_work: "소모품 작업",
    material_work_sub: "검색 후 수령·사용·반납 처리",
    asset_work: "비품 작업",
    asset_work_sub: "비품 수령·반납·위치 이동",
    my_records_sub: "내가 등록한 작업만 확인",
    my_recent_activity: "내 최근 작업",
    request_purchase: "구매 요청",
    request_purchase_sub: "등록된 소모품을 선택하고 예상 필요 수량 입력",
    arrival_receiving: "도착 입고",
    arrival_receiving_sub: "택배 송장 스캔 또는 공급업체 배송 처리",
    no_data: "데이터 없음",
    loading: "로딩중...",
    search: "이름·번호·바코드 검색",
    all_categories: "전체 분류",
    all_statuses: "전체 상태",
    only_low: "재고 경고만",
    query: "검색",
    scan_item: "스캔 검색",
    add_material: "소모품 추가",
    bulk_import: "엑셀 일괄 등록",
    bulk_import_materials: "소모품 일괄 등록",
    import_step_1: "1. 양식을 내려받아 소모품을 입력하세요",
    import_update_hint: "기존 번호 또는 바코드가 일치하면 정보를 수정하며, 기초 재고는 신규 소모품에만 반영됩니다.",
    download_template: "Excel 양식 다운로드",
    choose_spreadsheet: "Excel 또는 CSV 파일 선택",
    import_waiting: "선택된 파일 없음",
    confirm_import: "일괄 등록 확인",
    add_asset: "비품 추가",
    current_stock: "현재 재고",
    min_stock: "최소 재고",
    location: "위치/로케이션",
    storage_location: "보관 위치/로케이션 (선택)",
    category: "분류",
    spec: "규격",
    unit: "단위",
    status: "상태",
    supplier: "공급업체",
    cost: "단가",
    note: "비고",
    edit: "정보 수정",
    delete_material: "소모품 삭제",
    confirm_delete_material: "“{name}” 소모품을 영구 삭제하시겠습니까?\n\n재고가 0이고 재고·구매·발송·입고 기록이 없는 소모품만 삭제할 수 있습니다. 이 작업은 되돌릴 수 없습니다.",
    material_deleted: "소모품이 삭제되었습니다",
    material_archived: "업무 기록이 있어 사용 중지로 변경했습니다",
    delete_blocked_archive: "이 소모품은 영구 삭제할 수 없습니다: {reason}.\n\n사용 중지로 변경하시겠습니까? 기존 이력은 유지됩니다.",
    delete_reason_stock: "현재 재고 {qty}",
    delete_reason_history: "재고 이력 {count}건",
    delete_reason_purchase: "구매 기록 {count}건",
    delete_reason_shipping: "발송/입고 기록 {count}건",
    inbound: "입고",
    issue: "수령",
    use: "사용",
    return_item: "반납",
    adjust: "재고 조정",
    stocktake: "재고 조사",
    transaction_history: "재고 이력",
    material_code: "소모품 번호",
    barcode: "바코드 (선택)",
    name_zh: "중문 명칭",
    name_ko: "한글 명칭 (선택)",
    opening_qty: "기초 재고",
    active: "사용",
    inactive: "미사용",
    save: "저장",
    cancel: "취소",
    qty: "수량",
    counted_qty: "실사 수량",
    delta_qty: "조정 수량 (음수 가능)",
    recipient: "수령인",
    purpose: "용도",
    related_doc: "관련 번호/작업",
    operator: "작업자",
    time: "시간",
    before_qty: "작업 전",
    after_qty: "작업 후",
    confirm_submit: "확인 제출",
    asset_code: "비품 번호",
    asset_name: "비품명",
    brand: "브랜드",
    model: "모델",
    serial_no: "시리얼 번호",
    keeper: "현재 사용자",
    purchase_date: "구매일",
    purchase_cost: "구매 가격",
    warranty_until: "보증 만료",
    available: "사용 가능",
    assigned: "사용 중",
    repair: "수리 중",
    retired: "폐기",
    lost: "분실",
    assign: "비품 수령",
    return_asset: "비품 반납",
    transfer: "보관 위치 변경",
    repair_start: "수리 접수",
    repair_done: "수리 완료",
    retire: "폐기",
    mark_lost: "분실 처리",
    print_qr: "QR 인쇄",
    upload_photo: "사진 업로드",
    photos: "비품 사진",
    asset_history: "비품 이동 이력",
    all_records: "전체 기록",
    material_records: "소모품 기록",
    asset_records: "비품 기록",
    start_date: "시작일",
    end_date: "종료일",
    export_csv: "CSV 내보내기",
    locations: "보관 위치",
    add_location: "위치 추가",
    location_code: "위치 코드",
    location_name: "위치명",
    success: "처리 완료",
    failed: "처리 실패",
    scan_title: "소모품 또는 비품 QR 스캔",
    manual_code: "번호/바코드 직접 입력",
    start_scan: "스캔 시작",
    close: "닫기",
    not_found: "해당 기록을 찾을 수 없습니다",
    confirm_action: "작업 정보를 확인하세요",
    low_stock_badge: "재고 부족",
    field_mode: "현장",
    admin_mode: "관리자",
    viewer_mode: "읽기 전용",
    change_name: "작업자 이름 변경",
    required_fields: "필수 항목을 입력하세요",
    confirm_retire: "이 비품을 폐기 처리하시겠습니까?",
    confirm_lost: "이 비품을 분실 처리하시겠습니까?",
    photo_uploaded: "사진 업로드 완료",
    purchase_search: "구매번호·송장번호·공급업체 검색",
    status_requested: "구매 대기",
    status_purchasing: "구매 중",
    status_shipped: "발송 완료·입고 대기",
    status_partial: "일부 입고",
    status_completed: "전체 입고",
    status_cancelled: "취소",
    only_discrepancy: "차이 건만",
    new_purchase_request: "구매 요청 등록",
    receiving_desk: "입고 작업대",
    receiving_hint: "택배 송장을 스캔하거나 공급업체 배송 목록에서 선택하세요",
    scan_tracking: "택배 송장 스캔",
    tracking_or_shipment: "송장번호 또는 시스템 입고번호 입력",
    pending_express: "입고 대기 택배",
    pending_supplier: "입고 대기 공급업체 배송",
    urgency: "긴급도",
    normal: "일반",
    urgent: "긴급",
    request_reason: "요청 사유",
    choose_material: "등록된 소모품을 선택하세요",
    choose_material_action: "소모품 선택",
    material_selection_hint: "등록된 소모품 목록에서 반드시 선택해야 하며 비슷한 이름만 입력할 수 없습니다",
    material_search: "명칭·번호·규격 검색",
    material_picker_title: "등록된 소모품 선택",
    material_picker_hint: "문자 입력은 검색용이며 등록된 항목을 눌러야 선택이 완료됩니다",
    material_no_match: "일치하는 소모품이 없습니다. 관리자에게 먼저 등록을 요청하세요",
    add_line: "추가",
    add_material_hint: "구매할 소모품을 추가하세요",
    submit_request: "요청 제출",
    purchase_ordering: "구매 발주",
    purchase_channel: "구매 채널",
    platform_order_no: "플랫폼 주문번호",
    expected_date: "예상 도착일",
    ordered_items: "실제 구매 내역",
    save_purchase: "구매 결과 저장",
    register_shipment: "발송/배송 등록",
    express_delivery: "택배 발송",
    supplier_delivery: "공급업체 배송",
    tracking_no: "택배 송장번호",
    shipment_items: "이번 발송 내역",
    confirm_shipment: "등록 확인",
    requested_qty: "예상 필요 수량",
    requested_qty_hint: "창고는 대략적인 필요 수량을 입력하고 실제 구매 수량은 구매 담당자가 발주 시 입력합니다",
    ordered_qty: "실제 구매 수량",
    actual_purchase_hint: "예상 필요 수량은 참고용입니다. 실제 주문 수량을 품목별로 입력하고 구매하지 않은 품목은 0을 입력하세요",
    actual_qty_placeholder: "실제 수량 입력",
    received_qty: "입고 수량",
    expected_qty: "예상 수량",
    actual_received: "실제 수량",
    putaway_location: "적치 위치",
    difference_note: "차이 설명",
    discrepancy: "수량 차이",
    requester: "요청자",
    purchaser: "구매 담당",
    shipment_no: "입고 예정번호",
    delivery_method: "배송 방식",
    arrival_photos: "도착 사진",
    take_arrival_photo: "도착 사진 촬영",
    photo_required: "공급업체 배송은 도착 사진을 한 장 이상 촬영해야 합니다",
    confirm_receipt: "입고 확인 및 재고 반영",
    receipt_success: "입고 완료, 재고가 반영되었습니다",
    already_received: "이미 입고된 건으로 중복 반영할 수 없습니다",
    start_purchase: "구매 발주",
    add_shipment: "발송 등록",
    cancel_order: "구매 취소",
    close_difference: "차이 상태로 종료",
    received_progress: "입고 진행률",
    no_pending: "입고 대기 내역 없음",
    view_details: "상세 보기",
    purchase_pending_count: "구매 대기",
    waiting_receipt_count: "입고 대기",
    partial_count: "일부 입고",
    difference_count: "차이 발생"
  }
};

var MATERIAL_CATEGORIES = ["纸箱", "胶带", "标签", "打包膜", "托盘", "办公用品", "劳保用品", "清洁用品", "设备耗材", "其他"];
var ASSET_CATEGORIES = ["PDA", "打印机", "电子秤", "电脑", "叉车", "地牛", "推车", "工具", "货架", "网络设备", "监控设备", "其他"];
var MATERIAL_UNITS = ["个", "只", "卷", "张", "箱", "包", "瓶", "套", "块", "台", "kg", "m"];
