/* Shared real attendance UI. All writes are persisted by the staging Worker. */
(function(){'use strict';
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const agencies=['가온','포레인','동인천'],at=t=>t?new Date(t).toLocaleTimeString('en-GB',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit'}):'—',hours=n=>{const m=Math.round(n||0);return Math.floor(m/60)+':'+String(m%60).padStart(2,'0');},company=a=>a==='동인천'?'동인천（东仁川）':a,dept=d=>({bulk:'大货',direct_ship:'代发',import:'进口'}[d]||'其他');
const api=(action,data={})=>CKSession.request('sop_attendance_'+action,data);
function radios(current=''){return '<div class="agencies">'+agencies.map(a=>`<label class="agency"><input type="radio" name="agency" value="${a}" ${a===current?'checked':''} required><span>${a}</span><small>${a==='동인천'?'东仁川':'인력회사 / 人力公司'}</small></label>`).join('')+'</div>';}
function badge(r){qrcode.stringToBytes=qrcode.stringToBytesFuncs['UTF-8'];const qr=qrcode(0,'M');qr.addData(r.badgeId+'|'+r.name);qr.make();return `<div class="ck-label"><div class="badge-qr">${qr.createSvgTag({cellSize:4,margin:16,scalable:true})}</div><div class="badge-info"><div class="badge-heading"><b>CK</b><span>명찰 / 工牌</span></div><div class="badge-name ${r.name.length>22?'very-long':r.name.length>9?'long':''}">${e(r.name)}</div>${r.badgeType==='permanent'?'':`<div class="badge-agency">${e(company(r.agency))}</div>`}<div class="badge-date">${r.badgeType==='permanent'?'长期 / 고정':e(r.day)}</div><div class="badge-date">${e(r.badgeId.split('-').pop())}</div></div></div>`;}
async function print(r){if(r.inAt&&r.id){const x=await api('print',{id:r.id,client_req_id:crypto.randomUUID()});r=x.record;}let root=document.getElementById('print-root');if(!root){root=document.createElement('div');root.id='print-root';document.body.append(root);}root.innerHTML=badge(r);const style=document.createElement('style');style.textContent='@page{size:70mm 30mm;margin:0}';document.head.append(style);document.body.classList.add('ck-print-badge');try{window.print();}finally{document.body.classList.remove('ck-print-badge');style.remove();}return r;}
// Keep the same request id for a retry after a network error. A business rejection can be corrected.
function bind(form,action,values,done){let requestId='',signature='';form.onsubmit=async ev=>{ev.preventDefault();const buttons=[...form.querySelectorAll('button')],err=form.querySelector('[role=alert]');try{const data=values(),sig=JSON.stringify(data);if(sig!==signature||!requestId){signature=sig;requestId=crypto.randomUUID();}buttons.forEach(b=>b.disabled=true);if(err){err.hidden=true;err.textContent='';}const r=await api(action,{...data,client_req_id:requestId});await done(r);}catch(x){if(x.businessError)requestId='';if(err){err.hidden=false;err.textContent=x.message;}}finally{buttons.forEach(b=>b.disabled=false);}};}
window.CKAttendance={api,badge,print,at,hours};
window.CKAttendanceKiosk=async function(){
 await CKSession.ready;const config=await api('config'),root=document.getElementById('terminal-content');let mode='in',selected=null,timer=null;const el=id=>document.getElementById(id);
 const error='<p class="error" role="alert" hidden></p>',back='<button type="button" class="text-button" data-back>返回 / 돌아가기</button>';
 const clockOffset=Date.parse(config.asOf)-Date.now();function clock(){const d=new Date(Date.now()+clockOffset);el('kiosk-time').textContent=at(d);el('kiosk-date').textContent=d.toLocaleDateString('zh-CN',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',weekday:'short'})+' · 한국 시간';}clock();setInterval(clock,1000);
 function page(html){clearTimeout(timer);root.innerHTML=html;root.querySelector('[data-back]')?.addEventListener('click',()=>switchMode(mode));}
 function switchMode(m){mode=m;selected=null;el('tab-in').setAttribute('aria-selected',m==='in');el('tab-out').setAttribute('aria-selected',m==='out');m==='in'?checkin():lookup('checkout');}
 function checkin(){page(`<form class="form-body"><button type="button" class="permanent-entry" id="fixed">已有长期工牌？扫码签到 <span>고정 명찰로 출근 등록</span></button><label for="name" class="field-label">姓名 <span>이름</span></label><input id="name" class="text-input" autocomplete="off" maxlength="40" placeholder="请输入姓名 / 이름을 입력하세요" required><fieldset><legend class="field-label">人力公司 <span>인력회사</span></legend>${radios()}</fieldset>${error}<button class="primary">签到 <span>출근 등록</span></button><div class="helper-row"><button type="button" class="text-button" id="company">修改人力公司 / 회사 변경</button><button type="button" class="text-button" id="reprint">补打工牌 / 명찰 재출력</button></div></form>`);
  bind(root.querySelector('form'),'checkin',()=>({name:el('name').value,agency:root.querySelector('input[name=agency]:checked')?.value}),r=>{if(r.identityRequired){const name=el('name').value;page(`<div class="form-body"><h1 class="find-title">今天已有同名记录</h1><p>오늘 같은 이름의 출근 기록이 있습니다.</p><p class="soft-note">已签到但工牌丢失，可以按姓名查找并补打。<br>명찰을 분실했으면 이름으로 검색해 재출력하세요.<br>如果是同名的另一位人员，请工作人员核实。<br>동명이인은 담당자에게 확인하세요.</p><button class="primary" id="verify">按姓名查找工牌 / 이름으로 명찰 찾기</button>${back}</div>`);el('verify').onclick=()=>reprintSearch(name);return;}selected=r.record;success('in',r.existing);});
  el('fixed').onclick=()=>lookup('fixed');el('company').onclick=()=>lookup('company');el('reprint').onclick=()=>reprintSearch(el('name').value);el('name').focus();
 }
 function reprintSearch(name='',agency=''){
  page(`<div class="form-body reprint-body"><h1 class="find-title">补打工牌 <span>명찰 재출력</span></h1><p class="soft-note">工牌丢了也可以：输入签到时的姓名，找到自己的记录。<br>명찰이 없어도 출근 등록한 이름으로 찾을 수 있어요.</p><form><label class="field-label" for="find-name">姓名 <span>이름</span></label><input id="find-name" class="text-input" value="${e(name)}" maxlength="40" autocomplete="off" required placeholder="完整姓名 / 성명"><label class="field-label" for="find-agency">人力公司 <span>인력회사 · 可选 / 선택사항</span></label><select id="find-agency" class="text-input"><option value="">全部公司 / 전체</option>${agencies.map(a=>`<option value="${a}" ${a===agency?'selected':''}>${e(company(a))}</option>`).join('')}</select>${error}<button class="primary">查找工牌 / 명찰 찾기</button></form><div id="find-results" aria-live="polite"></div><details class="reprint-scan"><summary>也可扫描或输入工号 / 명찰 번호로 찾기</summary><form id="scan-reprint"><label for="find-code">工牌编号 / 명찰 번호</label><input id="find-code" class="text-input" autocomplete="off" required placeholder="DA-… / DAF-…">${error}<button class="secondary">查找 / 찾기</button></form></details>${back}</div>`);
  const terms=()=>({name:el('find-name').value,agency:el('find-agency').value});
  bind(root.querySelector('form'),'search',terms,r=>{const query=terms(),box=el('find-results');box.innerHTML=r.items.length?`<p class="find-count">找到 ${r.items.length} 条，请核对后选择自己。<br>${r.items.length}건 · 본인 기록을 선택하세요.</p><div class="badge-candidates">${r.items.map((x,i)=>{const v=x.record||x.person;return `<button type="button" class="badge-candidate" data-candidate="${i}"><span><strong>${e(v.name)}</strong><span>${e(company(v.agency))}</span><small>${x.record?`今日 ${at(v.inAt)} 签到 · ${v.outAt?'已下班 / 퇴근':'已签到 / 출근'}`:'长期工牌 · 今日未签到 / 고정 명찰 · 오늘 미출근'}</small><small>工牌尾号 / 명찰 끝자리 ${e(v.badgeId.split('-').pop())}</small></span><b>核对 →<small>확인</small></b></button>`;}).join('')}</div>`:'<p class="find-empty">没有找到记录。请核对姓名和公司；临时工牌仅可补打当天记录。<br>기록이 없습니다. 이름과 회사를 확인하세요. 일일 명찰은 당일 기록만 조회됩니다.</p>';box.querySelectorAll('[data-candidate]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const x=await api('lookup',{badge:r.items[Number(b.dataset.candidate)].person.badgeId});reprintReview(x,query);}catch(x){box.insertAdjacentHTML('beforeend',`<p class="error" role="alert">${e(x.message)}</p>`);b.disabled=false;}});});
  bind(el('scan-reprint'),'lookup',()=>({badge:el('find-code').value}),r=>reprintReview(r,terms()));el('find-name').focus();
 }
 function reprintReview(x,query){
  if(!x.record&&x.person.badgeType!=='permanent')throw Error('没有当天签到记录 / 오늘 출근 기록이 없습니다');
  selected=x.record||x.person;const r=selected;
  page(`<div class="form-body reprint-review"><h1 class="find-title">核对并补打 <span>확인 후 재출력</span></h1><h2>${e(r.name)}</h2><p class="record-meta">${e(company(r.agency))}<br>${r.inAt?`${e(r.day)} · 上班 / 출근 ${at(r.inAt)}${r.outAt?` · 下班 / 퇴근 ${at(r.outAt)}`:''}`:'长期工牌 · 今日未签到 / 고정 명찰 · 오늘 미출근'}</p><div class="badge-preview">${badge(r)}</div><p class="soft-note">补打原工牌，保留原上下班时间。<br>기존 명찰만 재출력하며 출퇴근 기록은 바뀌지 않습니다.</p>${error}<button type="button" class="primary" id="confirm-reprint">这是我，打印工牌 / 본인 확인 · 출력</button><p class="soft-note" id="reprint-note" role="status"></p><div class="helper-row"><button type="button" class="text-button" id="find-again">重新查找 / 다시 찾기</button><button type="button" class="text-button" id="reprint-done">返回签到 / 출근 화면</button></div></div>`);
  el('find-again').onclick=()=>reprintSearch(query.name,query.agency);el('reprint-done').onclick=()=>switchMode('in');
  el('confirm-reprint').onclick=async()=>{const b=el('confirm-reprint'),err=root.querySelector('[role=alert]');b.disabled=true;err.hidden=true;try{selected=await print(selected);el('reprint-note').textContent='已打开打印，请确认实际出纸。没有新增签到。 / 출력 창이 열렸습니다. 실제 출력을 확인하세요. 출근 기록은 추가되지 않았습니다.';}catch(x){err.textContent=x.message;err.hidden=false;}finally{b.disabled=false;}};
 }
 function lookup(purpose){const out=purpose==='checkout',title=out?'请扫描工牌下班 / 퇴근 명찰 스캔':purpose==='fixed'?'长期日当 · 扫码签到 / 고정 명찰 출근':'扫描工牌 / 명찰 스캔';page(`<form class="form-body"><div class="checkout-intro"><h1>${title}</h1><p>将工牌对准扫码器 / 명찰을 스캐너에 대세요</p></div><label class="field-label" for="code">工牌 <span>명찰</span></label><input id="code" class="text-input" required autocomplete="off" placeholder="扫描后回车 / 스캔 후 Enter">${error}<button class="primary">${out?'确认下班 / 퇴근 등록':'确认 / 확인'}</button>${back}</form>`);
  bind(root.querySelector('form'),out?'checkout':'lookup',()=>({badge:el('code').value}),r=>{if(out){selected=r.record;success('out',r.existing,r.needsReview);return;}if(purpose==='fixed'){if(r.person.badgeType!=='permanent')throw Error('请使用长期工牌 / 고정 명찰을 사용하세요');if(r.record){selected=r.record;success(r.record.outAt?'out':'in',true);}else fixed(r.person);return;}if(!r.record)throw Error('没有当天签到记录 / 오늘 출근 기록이 없습니다');selected=r.record;purpose==='company'?editCompany():success(selected.outAt?'out':'in',true);});el('code').focus();
 }
 function fixed(p){page(`<form class="form-body"><h1>${e(p.name)}</h1><p>确认今天的人力公司 / 오늘의 인력회사를 확인하세요</p>${radios(p.agency)}${error}<button class="primary">签到 / 출근 등록</button>${back}</form>`);bind(root.querySelector('form'),'checkin',()=>({badge:p.badgeId,agency:root.querySelector('input:checked').value}),r=>{selected=r.record;success(selected.outAt?'out':'in',r.existing);});}
 function editCompany(){page(`<form class="form-body"><h1 class="find-title">${e(selected.name)} · 修改公司</h1><p>인력회사를 변경하세요.</p>${radios(selected.agency)}<p class="soft-note">更正当天公司，保留工牌和签到时间。<br>당일 회사만 변경됩니다. 출근 시간은 유지됩니다.</p>${error}<button class="primary">保存 / 저장</button>${back}</form>`);bind(root.querySelector('form'),'company',()=>({id:selected.id,version:selected.version,agency:root.querySelector('input:checked').value}),r=>{selected=r.record;success(selected.outAt?'out':'in',true);});}
 function success(kind,existing,review){const out=kind==='out',r=selected;page(`<div class="success-panel" role="status"><div class="success-symbol">✓</div><h1>${e(r.name)}，${out?'已下班':'已签到'}</h1><p class="korean">${e(r.name)}님, ${out?'퇴근':'출근'} 등록이 완료되었습니다.</p><p class="greeting">${out?'今天辛苦了。':'美好的一天要加油哦。'}<br>${out?'오늘도 수고하셨습니다.':'오늘도 좋은 하루 보내세요. 힘내세요!'}</p><div class="record-meta">${e(company(r.agency))} · ${at(out?r.outAt:r.inAt)}</div>${out?'':`<div class="badge-preview">${badge(r)}</div><p class="print-note">${r.badgeType==='permanent'?'固定工牌可继续使用 / 고정 명찰을 계속 사용하세요':'70 × 30 mm · 请保管至下班 / 퇴근 시까지 보관하세요'}</p>`}<div class="success-actions">${out?'':`<button id="print" class="${r.badgeType==='permanent'?'secondary':'primary'}">${r.badgeType==='permanent'?'补打':'打印'}工牌 / 명찰 출력</button><button id="edit" class="secondary">修改公司 / 회사 변경</button>`}<button id="next" class="secondary">下一位 / 다음 분</button></div><p id="print-note" class="soft-note">${review?'个人作业计时已停止，负责人需核实；同组任务继续。':existing?'使用原记录，未重复签到或签退。 / 중복 기록 없이 처리되었습니다.':''}</p><p role="alert" class="error" hidden></p></div>`);
  el('next').onclick=()=>switchMode(out?'out':'in');if(out)timer=setTimeout(()=>switchMode('out'),8000);else{el('edit').onclick=editCompany;el('print').onclick=async()=>{const b=el('print');b.disabled=true;try{selected=await print(selected);el('print-note').textContent='已打开打印，请确认实际出纸。取消或卡纸可补打，不会重复签到。 / 실제 출력 여부를 확인하세요.';}catch(x){const p=root.querySelector('[role=alert]');p.textContent=x.message;p.hidden=false;}finally{b.disabled=false;}};}
 }
 el('tab-in').onclick=()=>switchMode('in');el('tab-out').onclick=()=>switchMode('out');switchMode('in');
};
window.CKLabor=async function(root,{field=false}={}){
 await CKSession.ready;root.classList.add('ck-labor');root.classList.toggle('ck-labor-field',field);const config=await api('config');let report=null,selectedId='',busy=false;
 root.innerHTML=`<div class="ck-section-heading"><div><p class="ck-eyebrow">PEOPLE & TIME</p><h2>${field?'现场人员与休息 / 인원·휴식':'日当人力 / 일용직 인력'}</h2><p>当天签到、实际休息与部门作业时长</p></div><div class="ck-actions"><a href="/attendance/" target="_blank">打开签到点 ↗</a>${!field?'<button data-permanent>长期工牌管理</button><button data-samename>同名人员核实</button><button data-register>登记长期工牌</button><button data-export>导出 CSV</button>':''}</div></div><div class="ck-filters"><label>日期 / 날짜<input type="date" data-date value="${config.day}"></label><label>人力公司 / 인력회사<select data-company><option value="">全部 / 전체</option>${agencies.map(a=>`<option value="${a}">${company(a)}</option>`).join('')}</select></label><label>姓名或工牌 / 이름·명찰<input data-search placeholder="搜索 / 검색"></label><button data-refresh>刷新 / 새로고침</button></div><p data-error class="ck-error" role="alert" hidden></p><div data-summary class="ck-metrics"></div><div data-peoplecards class="ck-person-cards"></div><div class="ck-table-wrap" tabindex="0"><table class="ck-table"><thead><tr><th>姓名 / 이름</th><th>公司</th><th>上下班</th><th>在岗</th><th>大货</th><th>代发</th><th>进口</th><th>休息</th><th>未归属</th><th>其他 / 冲突</th><th>操作</th></tr></thead><tbody data-rows></tbody></table></div><p class="ck-muted">单位：小时:分钟；个人时间不除以人数。仅扣除明确登记的休息。未归属不等于休息或空闲。未签退记录计算至本次刷新时间。</p><div data-agencies class="ck-agency-totals"></div><div data-stale></div><section data-detail></section><dialog class="ck-editor"><form><h2></h2><div data-fields></div><p role="alert" class="ck-error" hidden></p><div class="ck-actions"><button type="button" data-cancel>取消 / 취소</button><button type="submit">保存 / 저장</button></div></form></dialog>`;
 const $=s=>root.querySelector('[data-'+s+']'),showError=x=>{$('error').hidden=false;$('error').textContent=x.message;};
 const filtered=()=>report.items.filter(x=>(!$('company').value||x.record.agency===$('company').value)&&(!$('search').value||(x.record.name+' '+x.record.badgeId).toLowerCase().includes($('search').value.toLowerCase())));
 async function refresh(){if(busy)return;busy=true;$('refresh').disabled=true;try{report=await api('summary',{date:$('date').value});$('error').hidden=true;draw();if(selectedId)detail(selectedId);}catch(x){showError(x);}finally{busy=false;$('refresh').disabled=false;}}
 function draw(){const items=filtered(),sum=k=>items.reduce((n,x)=>n+x.totals[k],0);$('summary').innerHTML=[['当天签到',items.length+' 人'],['尚未签退',items.filter(x=>!x.record.outAt).length+' 人'],['部门作业',hours(sum('bulk')+sum('direct_ship')+sum('import'))],['已登记休息',hours(sum('rest'))]].map(([l,v])=>`<article><span>${l}</span><strong>${v}</strong></article>`).join('');
  $('rows').innerHTML=items.map(x=>{const r=x.record,v=x.totals;return `<tr><td><strong>${e(r.name)}</strong><small>${e(r.badgeId)}</small></td><td>${e(company(r.agency))}</td><td>${at(r.inAt)} – ${at(r.outAt)}<small>${{out:'已下班',rest:'休息中',working:'作业中',unassigned:'未分配作业'}[x.status]}${v.flags.length?' · 待核实':''}</small></td>${['presence','bulk','direct_ship','import','rest','unassigned'].map(k=>`<td>${hours(v[k])}</td>`).join('')}<td>${hours(v.other)} / ${hours(v.conflict)}</td><td><button class="ck-small" data-person="${e(r.id)}">明细${field?' / 休息':''}</button></td></tr>`;}).join('')||'<tr><td colspan="11" class="ck-empty">当天暂无符合条件的签到记录 / 출근 기록이 없습니다</td></tr>';
  $('agencies').innerHTML=agencies.map(a=>{const ar=items.filter(x=>x.record.agency===a);return `<article><h3>${company(a)}</h3><p>${ar.length} 人签到 · ${ar.filter(x=>!x.record.outAt).length} 人未签退</p><p>${['bulk','direct_ship','import'].map(k=>dept(k)+' '+hours(ar.reduce((n,x)=>n+x.totals[k],0))).join('　')}</p></article>`;}).join('');$('stale').innerHTML=report.stale.length?`<p class="ck-warning">此前有 ${report.stale.length}${report.stale.length===100?'＋':''} 条未签退记录，请按对应日期核实补卡，不计入今天出勤。</p>`:'';
  if(field)$('peoplecards').innerHTML=items.map(x=>`<article><div><strong>${e(x.record.name)}</strong><small>${e(company(x.record.agency))} · ${{out:'已下班 / 퇴근',rest:'休息中 / 휴식',working:'作业中 / 작업 중',unassigned:'待安排 / 배정 대기'}[x.status]}</small></div><p>${x.currentJobs.length?x.currentJobs.map(j=>e(dept(j.department))).join(' · '):'当前没有作业计时'}</p><button class="ck-small" data-person="${e(x.record.id)}">${x.status==='rest'?'休息明细 / 휴식 상세':'明细与休息 / 상세·휴식'}</button></article>`).join('')||'<p class="ck-muted">当天暂无签到人员。</p>';
  root.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>detail(b.dataset.person));
 }
 function dialog(title,html,action,data,done){const d=root.querySelector('dialog'),f=d.querySelector('form');d.querySelector('h2').textContent=title;$('fields').innerHTML=html;d.querySelector('[role=alert]').hidden=true;$('cancel').onclick=()=>d.close();bind(f,action,()=>({...data,...Object.fromEntries(new FormData(f))}),async r=>{d.close();await refresh();if(done)await done(r);});d.showModal();}
 function detail(id){selectedId=id;const x=report.items.find(x=>x.record.id===id);if(!x)return;const r=x.record,canEdit=['manager','dispatcher'].includes(config.user.role),today=r.day===config.day,events=[...x.segments.map(s=>({start:s.start,end:s.end,label:dept(s.department)+' · '+s.jobNo+(s.reason?' · '+s.reason:'')})),...x.breaks.map(b=>({...b,label:'实际休息 / 휴식'}))].sort((a,b)=>a.start.localeCompare(b.start));$('detail').innerHTML=`<div class="ck-detail-card"><div class="ck-section-heading"><h3>${e(r.name)} · 当日明细</h3><button data-close class="ck-small">收起</button></div>${x.totals.flags.length?`<p class="ck-warning">${x.totals.flags.map(e).join('；')}</p>`:''}<p>上班 ${at(r.inAt)} · 下班 ${at(r.outAt)} · ${e(company(r.agency))}</p><div class="ck-actions">${canEdit&&today&&!r.outAt?`<button data-rest>${x.status==='rest'?'结束休息 / 휴식 종료':'开始休息 / 휴식 시작'}</button>`:''}${config.user.role==='manager'?'<button data-correct>核实补卡 / 기록 정정</button>':''}${today?'<button data-reprint>补打工牌 / 재출력</button>':''}</div><ol class="ck-timeline">${events.map(s=>`<li><time>${at(s.start)} – ${at(s.end)}</time><span>${e(s.label)}</span></li>`).join('')||'<li>暂无作业或休息记录</li>'}</ol><details><summary>修改与打印历史 · ${x.events.length} 条</summary>${x.events.map(a=>`<p>${at(a.at)} · ${e(a.action.replace('sop_attendance_',''))} · ${e(a.actor)}${a.before.agency!==a.after.agency?' · '+e(a.before.agency||'')+' → '+e(a.after.agency||''):''}${a.after.correction_reason?' · '+e(a.after.correction_reason):''}</p>`).join('')}</details></div>`;
  if(field)$('detail').scrollIntoView({block:'start'});
  $('close').onclick=()=>{selectedId='';$('detail').replaceChildren();};if($('rest'))$('rest').onclick=()=>dialog(x.status==='rest'?'结束休息':'开始休息',`<p>${e(r.name)}：${x.status==='rest'?'恢复仍在进行的原任务；若原任务已结束，则回到未分配状态。':'现在停止个人作业计时，并开始记录休息。'}</p>`,x.status==='rest'?'break_end':'break_start',{id:r.id});if($('reprint'))$('reprint').onclick=async()=>{try{await print(r);await refresh();}catch(x){showError(x);}};
  if($('correct'))$('correct').onclick=()=>{const local=t=>t?new Date(Date.parse(t)+9*3600000).toISOString().slice(0,16):'';dialog('核实上下班时间 / 출퇴근 정정',`<label>上班（韩国时间）<input name="inAt" type="datetime-local" value="${local(r.inAt)}" required></label><label>下班（留空表示未签退）<input name="outAt" type="datetime-local" value="${local(r.outAt)}"></label><label>核实原因<textarea name="reason" required></textarea></label>`,'correct',{id:r.id,version:r.version});const f=root.querySelector('dialog form');bind(f,'correct',()=>{const v=Object.fromEntries(new FormData(f));return {id:r.id,version:r.version,reason:v.reason,inAt:v.inAt+':00+09:00',outAt:v.outAt?v.outAt+':00+09:00':''};},async()=>{root.querySelector('dialog').close();await refresh();});};
 }
 if($('samename'))$('samename').onclick=()=>dialog('同名不同人 · 核实后另建签到',`<p>确认是不同的两个人后才使用此入口。新工牌不会覆盖已有签到。</p><label>姓名<input name="name" required maxlength="40"></label><label>人力公司<select name="agency" required><option value="">请选择</option>${agencies.map(a=>`<option>${a}</option>`).join('')}</select></label><label>核实说明<textarea name="reason" required></textarea></label>`,'checkin',{confirm_distinct_person:true},async r=>{await print(r.record);});
 if($('permanent'))$('permanent').onclick=async()=>{try{const r=await api('people'),d=root.querySelector('dialog');d.querySelector('h2').textContent='长期工牌 / 고정 명찰';$('fields').innerHTML=r.items.map(p=>`<p><strong>${e(p.name)}</strong> · ${e(p.badgeId)} <button type="button" data-print-person="${e(p.id)}">补打 / 재출력</button></p>`).join('')||'<p>暂无长期工牌，请先登记。</p>';d.querySelector('[type=submit]').hidden=true;$('cancel').textContent='关闭 / 닫기';$('cancel').onclick=()=>{d.close();d.querySelector('[type=submit]').hidden=false;};d.querySelector('[role=alert]').hidden=true;d.onclose=()=>{d.querySelector('[type=submit]').hidden=false;$('cancel').textContent='取消 / 취소';};d.querySelectorAll('[data-print-person]').forEach(b=>b.onclick=async()=>{try{d.close();await print(r.items.find(p=>p.id===b.dataset.printPerson));}catch(x){showError(x);}});d.showModal();}catch(x){showError(x);}};
 if($('register'))$('register').onclick=()=>dialog('登记长期工牌 / 고정 명찰 등록',`<label>姓名 / 이름<input name="name" maxlength="40" required></label><label>人力公司<select name="agency" required><option value="">请选择 / 선택</option>${agencies.map(a=>`<option>${a}</option>`).join('')}</select></label><label>已有固定工号（可留空自动生成）<input name="badge" placeholder="DAF-..."></label>`,'register',{},async r=>{await print(r.person);});
 if($('export'))$('export').onclick=()=>{if(!report)return;const cell=v=>{let s=String(v??'');if(/^[\s]*[=+\-@]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};const data=[['日期','姓名','工牌','公司','上班','下班','在岗分钟','大货分钟','代发分钟','进口分钟','休息分钟','未归属分钟','其他分钟','冲突分钟','异常','截至时间'],...filtered().map(({record:r,totals:v})=>[r.day,r.name,r.badgeId,r.agency,r.inAt,r.outAt,...['presence','bulk','direct_ship','import','rest','unassigned','other','conflict'].map(k=>Math.round(v[k]*100)/100),v.flags.join('；'),report.asOf])];const url=URL.createObjectURL(new Blob(['\ufeff'+data.map(row=>row.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='CK_日当人力_'+report.date+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 $('date').onchange=refresh;$('refresh').onclick=refresh;$('company').onchange=draw;$('search').oninput=draw;await refresh();return {refresh};
};
})();
