(function(){
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time=s=>s?new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(s)):'—';
const api=(action,data={})=>CKSession.request('sop_courier_'+action,data);
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date());
const status=s=>s==='handed_over'?'已交接 / 인계 완료':'待交接 / 인계 대기';
let rules,owners;
const label=id=>owners.find(x=>x[0]===id)?.[1]||id||'—';
const options=(all=false)=> (all?'<option value="">全部所属 / 전체</option>':'')+owners.map(x=>'<option value="'+esc(x[0])+'">'+esc(x[1])+'</option>').join('');
const alertText=(el,message,bad=false)=>{el.textContent=message;el.classList.toggle('courier-error',bad);};
function progressHtml(p){if(!p)return '';return '<section class="courier-progress"><h3>快递到仓 / 택배 도착 <span>'+p.received+' / '+p.total+'</span></h3><div class="courier-table-scroll"><table><thead><tr><th>快递单号 / 송장번호</th><th>所属 / 소속</th><th>入仓时间 / 도착 시간</th><th>扫描人 / 스캔 담당</th></tr></thead><tbody>'+p.items.map(x=>'<tr><td>'+esc(x.tracking_no)+'</td><td>'+esc(label(x.owner))+'</td><td>'+esc(x.received_at?time(x.received_at):'未到仓 / 미도착')+'</td><td>'+esc(x.scanner_name||'—')+'</td></tr>').join('')+'</tbody></table></div></section>';}
async function detail(id,refresh){
 const r=await api('detail',{id}),x=r.item,d=document.createElement('dialog');d.className='courier-dialog';
 d.innerHTML='<form method="dialog" class="courier-dialog-head"><h3>'+esc(x.tracking_no)+'</h3><button aria-label="关闭 / 닫기">×</button></form><p>入仓 / 도착：'+esc(time(x.received_at))+'<br>扫描人 / 스캔 담당：'+esc(x.scanner_name)+'</p><label>所属 / 소속<select name="owner">'+options()+'</select></label><label>接收人 / 인수자<input name="recipient" maxlength="100" value="'+esc(x.handed_to)+'"></label><label>备注／更正原因 / 비고·변경 사유<textarea name="note" rows="2" maxlength="300">'+esc(x.note)+'</textarea></label><p class="courier-feedback" role="status"></p><div class="courier-actions"><button data-save class="btn btn-outline">保存更正 / 수정 저장</button><button data-handoff class="btn btn-primary">确认交接 / 인계 완료</button></div><details><summary>操作记录 / 변경 이력（'+r.events.length+'）</summary>'+r.events.map(e=>{let v={};try{v=JSON.parse(e.detail);}catch{}return '<p>'+esc(time(e.created_at))+' '+esc(e.actor_name)+'<br>'+esc(e.kind==='receive'?'收货 / 수령':label(v.before?.owner)+' → '+label(v.after?.owner)+' · '+status(v.after?.status)+(v.after?.handed_to?' · '+v.after.handed_to:'')+(v.note?' · '+v.note:''))+'</p>';}).join('')+'</details>';
 let selectedOwner=x.owner;const ownerSelect=d.querySelector('[name=owner]'),ownerButtons=document.createElement('div');ownerButtons.className='courier-owner-buttons';ownerButtons.innerHTML=owners.map(o=>'<button type="button" data-owner="'+o[0]+'" aria-pressed="'+(o[0]===selectedOwner)+'">'+esc(o[1])+'</button>').join('');const ownerField=document.createElement('fieldset');ownerField.style.cssText='border:0;padding:0;margin:12px 0';ownerField.innerHTML='<legend>所属 / 소속</legend>';ownerSelect.parentElement.replaceWith(ownerField);ownerField.append(ownerButtons);ownerButtons.querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedOwner=b.dataset.owner;ownerButtons.querySelectorAll('button').forEach(o=>o.setAttribute('aria-pressed',String(o===b)));});d.querySelector('[data-handoff]').disabled=x.status==='handed_over';document.body.append(d);d.showModal();d.addEventListener('close',()=>d.remove());
 const save=async handed=>{const buttons=d.querySelectorAll('.courier-actions button');buttons.forEach(b=>b.disabled=true);try{await api('update',{id:x.id,version:x.version,owner:selectedOwner,handed_to:d.querySelector('[name=recipient]').value,note:d.querySelector('[name=note]').value,status:handed?'handed_over':x.status});d.close();await refresh();}catch(e){alertText(d.querySelector('[role=status]'),e.message,true);buttons.forEach(b=>b.disabled=false);d.querySelector('[data-handoff]').disabled=x.status==='handed_over';}};
 d.querySelector('[data-save]').onclick=()=>save(false);d.querySelector('[data-handoff]').onclick=()=>save(true);
}
function office(host){
 let offset=0,seq=0;host.classList.add('courier-office');
 host.innerHTML='<div class="courier-section-head"><h2>到仓快递 / 도착 택배</h2><span>外包装收货与交接 / 포장 수령·인계</span></div><form class="courier-filters"><label>所属 / 소속<select name="owner">'+options(true)+'</select></label><label>快递单号 / 송장번호<input name="keyword" type="search" placeholder="输入全部或部分单号 / 번호 검색"></label><label>入仓日期 / 도착일<input name="from" type="date" value="'+today()+'"></label><label>至 / 종료일<input name="to" type="date" value="'+today()+'"></label><label>交接 / 인계<select name="status"><option value="">全部 / 전체</option><option value="received">待交接 / 대기</option><option value="handed_over">已交接 / 완료</option></select></label><button class="btn btn-primary" type="submit">查询 / 검색</button></form><p class="courier-feedback" role="status"></p><div class="courier-table-scroll"><table><thead><tr><th>快递单号 / 송장번호</th><th>所属 / 소속</th><th>入仓时间 / 도착 시간</th><th>扫描人 / 스캔 담당</th><th>关联计划 / 입고 계획</th><th>交接 / 인계</th><th></th></tr></thead><tbody></tbody></table></div><div class="courier-pager"><span></span><button data-prev class="btn btn-outline">上一页 / 이전</button><button data-next class="btn btn-outline">下一页 / 다음</button></div>';
 const form=host.querySelector('form'),feedback=host.querySelector('[role=status]');
 const load=async()=>{const current=++seq;alertText(feedback,'读取中 / 불러오는 중');try{const filters=Object.fromEntries(new FormData(form));const r=await api('list',{...filters,offset,limit:50});if(seq!==current)return;
 host.querySelector('tbody').innerHTML=r.items.length?r.items.map(x=>'<tr><td class="courier-number">'+esc(x.tracking_no)+'</td><td>'+esc(label(x.owner))+'</td><td>'+esc(time(x.received_at))+'</td><td>'+esc(x.scanner_name)+'</td><td>'+(x.plan_id?'<button class="courier-link" data-plan="'+esc(x.plan_id)+'">'+esc(x.display_no)+'</button><small>'+esc(x.customer)+'</small>':x.shipment_id?'耗材／采购登记':'—')+'</td><td>'+esc(status(x.status))+(x.handed_to?'<small>'+esc(x.handed_to)+'</small>':'')+'</td><td><button class="btn btn-outline btn-sm" data-detail="'+esc(x.id)+'">明细 / 상세</button></td></tr>').join(''):'<tr><td colspan="7" class="courier-empty">当前条件下暂无快递记录 / 조회 결과가 없습니다</td></tr>';
 host.querySelector('.courier-pager span').textContent='共 '+r.total+' 件 · '+(Math.floor(offset/50)+1)+' / '+Math.max(1,Math.ceil(r.total/50));host.querySelector('[data-prev]').disabled=offset===0;host.querySelector('[data-next]').disabled=offset+50>=r.total;alertText(feedback,'');
 host.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail,load).catch(e=>alertText(feedback,e.message,true)));host.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>openInboundDetail(b.dataset.plan));
 }catch(e){if(seq===current)alertText(feedback,e.message,true);}};
 form.onsubmit=e=>{e.preventDefault();offset=0;load();};form.elements.keyword.addEventListener('input',()=>{if(form.elements.keyword.value){form.elements.from.value='';form.elements.to.value='';}});
 host.querySelector('[data-prev]').onclick=()=>{offset=Math.max(0,offset-50);load();};host.querySelector('[data-next]').onclick=()=>{offset+=50;load();};load();
}
function field(host){
 let owner='',busy=false,camera=null,recent=[],scanSeq=0,lastCamera='',lastCameraAt=0,scannerBadge='';
 host.className='courier-field';host.innerHTML='<h2>快递收货 / 택배 수령</h2><p class="courier-scanner">扫描人 / 스캔 담당：<strong>'+esc(CKSession.user.name)+'</strong> <button class="courier-link" data-person>更换工牌 / 명찰 변경</button></p><fieldset><legend>点选快递所属 / 소속 선택</legend><div class="courier-owner-buttons">'+owners.map(x=>'<button type="button" data-owner="'+x[0]+'" aria-pressed="false">'+esc(x[1])+'</button>').join('')+'</div></fieldset><form class="courier-scan-form"><label for="courierScanInput">快递单号 / 송장번호</label><div class="courier-scan-row"><input id="courierScanInput" name="tracking" autocomplete="off" autocapitalize="characters" spellcheck="false" placeholder="先点选所属 / 소속을 선택하세요" disabled><button type="submit" class="btn btn-primary" disabled>收货 / 수령</button></div><div class="courier-actions"><button type="button" data-camera class="btn btn-outline" disabled>相机扫码 / 카메라</button><span data-count>本次 0 件 / 0건</span></div><p class="courier-scan-hint">仅扫运单条码；每次一扫，收货后可继续扫描。<br>송장 바코드를 하나씩 스캔하세요.</p></form><div id="courierCamera" hidden></div><div class="courier-feedback" role="status" aria-live="polite">请先点选所属 / 먼저 소속을 선택하세요</div><div class="courier-recent"><h3>最近收货 / 최근 수령</h3><ul></ul></div>';
 const form=host.querySelector('form'),input=form.elements.tracking,feedback=host.querySelector('[role=status]'),cameraButton=host.querySelector('[data-camera]');
 const enable=()=>{input.disabled=busy||!owner;form.querySelector('[type=submit]').disabled=busy||!owner;cameraButton.disabled=busy||!owner;host.querySelectorAll('[data-owner]').forEach(b=>b.disabled=busy);};
 host.querySelectorAll('[data-owner]').forEach(b=>b.onclick=()=>{owner=b.dataset.owner;host.querySelectorAll('[data-owner]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));input.placeholder='扫描快递单号 / 송장번호 스캔';enable();alertText(feedback,'当前所属：'+label(owner));input.focus();});
 const receive=async raw=>{
  if(busy)return;if(!owner){alertText(feedback,'请先点选快递所属 / 소속을 선택하세요',true);return;}
  let code;try{code=rules.trackingNumber(raw);}catch(e){alertText(feedback,e.message,true);input.select();return;}
  busy=true;enable();alertText(feedback,'正在收货 / 수령 중…');
  try{const r=await api('receive',{owner,tracking_no:code,scanner_badge:scannerBadge}),x=r.item;
   let message=r.duplicate?'已收过，不重复计件 / 이미 수령한 송장':'收货成功 / 수령 완료';
   message+='\n'+x.tracking_no+' · '+label(x.owner)+'\n'+time(x.received_at)+' · '+x.scanner_name;
   if(r.owner_conflict)message+='\n此前所属不同，保留原归属；如需更正请在明细中核实 / 기존 소속 유지';
   if(r.plan)message+='\n'+r.plan.display_no+' · 快递 '+r.plan.progress.received+'/'+r.plan.progress.total+' · '+(r.plan.status==='completed'?'已入库 / 입고 완료':r.plan.progress.received===r.plan.progress.total?'已收齐，待后续理货／卸货 / 후속 작업 대기':'尚未收齐 / 일부 수령');
   alertText(feedback,message,r.owner_conflict);if(!r.duplicate){scanSeq++;host.querySelector('[data-count]').textContent='本次 '+scanSeq+' 件 / '+scanSeq+'건';}
   recent=[x,...recent.filter(y=>y.id!==x.id)].slice(0,8);host.querySelector('ul').innerHTML=recent.map(y=>'<li><div><b>'+esc(y.tracking_no)+'</b><small>'+esc(label(y.owner))+' · '+esc(time(y.received_at).slice(11))+'</small></div><button type="button" class="courier-link" data-recent="'+esc(y.id)+'">明细 / 상세</button></li>').join('');host.querySelectorAll('[data-recent]').forEach(b=>b.onclick=()=>detail(b.dataset.recent,async()=>{}).catch(e=>alertText(feedback,e.message,true)));input.value='';
  }catch(e){alertText(feedback,e.message,true);input.select();}finally{busy=false;enable();input.focus();}
 };
 form.onsubmit=e=>{e.preventDefault();receive(input.value);};
 async function stopCamera(){if(camera){try{await camera.stop();await camera.clear();}catch{}camera=null;}host.querySelector('#courierCamera').hidden=true;cameraButton.textContent='相机扫码 / 카메라';}
 cameraButton.onclick=async()=>{if(camera)return stopCamera();try{host.querySelector('#courierCamera').hidden=false;camera=new Html5Qrcode('courierCamera',{formatsToSupport:[Html5QrcodeSupportedFormats.CODE_128,Html5QrcodeSupportedFormats.CODE_39,Html5QrcodeSupportedFormats.ITF,Html5QrcodeSupportedFormats.CODABAR],verbose:false});await camera.start({facingMode:'environment'},{fps:10,qrbox:{width:260,height:100}},text=>{if(busy||text===lastCamera&&Date.now()-lastCameraAt<4000)return;lastCamera=text;lastCameraAt=Date.now();input.value=text;receive(text);},()=>{});cameraButton.textContent='关闭相机 / 카메라 닫기';}catch(e){await stopCamera();alertText(feedback,'无法打开相机，请使用扫码枪或输入单号 / 카메라를 열 수 없습니다',true);}};
 host.querySelector('[data-person]').onclick=()=>{const d=document.createElement('dialog');d.className='courier-dialog';d.innerHTML='<form><h3>扫描人工牌 / 담당자 명찰</h3><label>工牌 / 명찰<input name="badge" autocomplete="off" required></label><p role="status"></p><div class="courier-actions"><button class="btn btn-primary">确认 / 확인</button><button type="button" class="btn btn-outline" data-cancel>取消 / 취소</button></div></form>';document.body.append(d);d.showModal();d.querySelector('input').focus();d.querySelector('[data-cancel]').onclick=()=>d.close();d.onclose=()=>d.remove();d.querySelector('form').onsubmit=async e=>{e.preventDefault();const badge=d.querySelector('input').value.split('|')[0].trim();try{const r=await CKSession.request('sop_attendance_lookup',{badge});if(!r.record||r.record.outAt)throw Error('须先签到 / 먼저 출근 등록하세요');scannerBadge=r.person.badgeId;host.querySelector('.courier-scanner strong').textContent=r.person.name;d.close();input.focus();}catch(e){d.querySelector('[role=status]').textContent=e.message;}};};
 return {stop:stopCamera};
}
function installPlanFields(){
 const enhance=tr=>{const select=tr.querySelector('.ibc-line-type');if(!select||select.dataset.courier)return;select.dataset.courier='1';select.add(new Option('快递 / 택배','courier'));
 const wrap=document.createElement('label');wrap.className='courier-plan-numbers';wrap.hidden=true;wrap.innerHTML='快递单号 / 송장번호<textarea rows="3" maxlength="6000" placeholder="每行一个单号 / 한 줄에 한 번호"></textarea><small>数量按不同单号自动计算 / 송장별 수량 자동 계산</small>';tr.querySelector('td').append(wrap);
 const qty=tr.querySelector('.ibc-line-qty');select.addEventListener('change',()=>{const yes=select.value==='courier';wrap.hidden=!yes;qty.readOnly=yes;if(yes){qty.value='0';wrap.querySelector('textarea').focus();}});wrap.querySelector('textarea').oninput=()=>{try{qty.value=rules.trackingNumbers(wrap.querySelector('textarea').value).length;}catch{qty.value='0';}};
 };
 const add=window.addIbcLine;window.addIbcLine=function(...args){add(...args);document.querySelectorAll('#ibcLinesBody tr').forEach(enhance);};document.querySelectorAll('#ibcLinesBody tr').forEach(enhance);
 const read=window.getIbcLines;window.getIbcLines=function(){const old=read().filter(x=>x.unit_type!=='courier');let count=0;for(const tr of document.querySelectorAll('#ibcLinesBody tr'))if(tr.querySelector('select').value==='courier'){count++;const codes=rules.trackingNumbers(tr.querySelector('textarea').value);if(!codes.length)throw Error('选择快递后请填写快递单号 / 송장번호를 입력하세요');old.push({unit_type:'courier',planned_qty:codes.length,tracking_nos:codes,remark:tr.querySelector('.ibc-line-remark').value.trim()});}if(count>1)throw Error('请把快递单号填写在同一行 / 한 행에 입력하세요');return old;};
 const submit=window.submitInbound;window.submitInbound=async function(...args){try{getIbcLines();return await submit(...args);}catch(e){alert(e.message);}};
 const unit=window.unitTypeLabel;window.unitTypeLabel=value=>value==='courier'?'快递 / 택배':unit(value);
 const load=window.loadInboundDetail;window.loadInboundDetail=async function(...args){await load(...args);const p=window._currentInboundPlan;if(p?.courier_progress){document.getElementById('inboundDetailBody').insertAdjacentHTML('afterbegin',progressHtml(p.courier_progress));}};
 const edit=window.openInboundEditForm;window.openInboundEditForm=function(...args){edit(...args);const progress=window._currentInboundPlan?.courier_progress,box=document.querySelector('#ibEditOverlay .modal-box');if(progress&&box){const field=document.createElement('label');field.className='courier-plan-numbers';field.innerHTML='快递单号 / 송장번호<textarea id="courierEditCodes" rows="4">'+esc(progress.items.map(x=>x.tracking_no).join('\n'))+'</textarea>';box.querySelector('div').after(field);if(progress.received)field.querySelector('textarea').readOnly=true;}};
 const originalApi=window.api;window.api=async function(body){if(body.action==='v2_inbound_plan_update'&&document.getElementById('courierEditCodes')){try{const codes=rules.trackingNumbers(document.getElementById('courierEditCodes').value);if(!codes.length)throw Error('快递单号不能为空');body.lines=window._currentInboundLines.map(x=>x.unit_type==='courier'?{...x,tracking_nos:codes,planned_qty:codes.length}:x);}catch(e){return {ok:false,error:e.message};}}return originalApi(body);};
}
window.CKInstallCourier=async function(app){
 if(!window.CK_SOP_ROLLOUT?.staging||!['001','002'].includes(app))return;
 rules=await import('/shared/courier-rules.js');owners=rules.courierOwners;
 if(app==='002'){
  installPlanFields();const tabs=document.getElementById('mainTabs'),b=document.createElement('button');b.type='button';b.dataset.tab='courier';b.textContent='到仓快递 / 도착 택배';tabs.append(b);
  const view=document.createElement('div');view.id='view-courier';view.className='view';view.style.display='none';document.getElementById('page-main').append(view);b.onclick=()=>{goView('courier');tabs.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));office(view);};
  if(new URLSearchParams(location.search).get('tab')==='courier')b.click();
  }else{
  const oldUnit=window.unitLabel;window.unitLabel=value=>value==='courier'?'快递 / 택배':oldUnit(value);
  const page=document.createElement('div');page.id='page-courier';page.className='page';page.innerHTML='<div class="topbar"><button class="back-btn">← 返回 / 뒤로</button></div><div data-courier-host></div>';document.body.append(page);page.querySelector('button').onclick=()=>goPage('home');let instance;
  const b=document.createElement('button');b.type='button';b.className='home-btn';b.innerHTML='<span class="label">快递收货</span><span class="label-ko">택배 수령</span>';b.onclick=()=>{showPage('courier');if(!instance)instance=field(page.querySelector('[data-courier-host]'));};document.querySelector('#page-home .home-grid').append(b);
  const show=window.showPage;window.showPage=function(name,...args){if(name!=='courier')instance?.stop();return show(name,...args);};if(new URLSearchParams(location.search).get('tab')==='courier')b.click();
 }
};
})();
