(function(){
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time=s=>s?new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(s)):'—';
const api=(action,data={})=>CKSession.request('sop_courier_'+action,data);
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date());
const status=s=>s==='handed_over'?'已交接 / 인계 완료':'待交接 / 인계 대기';
let rules,owners;
const label=id=>owners.find(x=>x[0]===id)?.[1]||id||'—';
const options=(all=false)=> (all?'<option value="">全部所属 / 전체</option>':'')+owners.map(x=>'<option value="'+esc(x[0])+'">'+esc(x[1])+'</option>').join('');
const alertText=(el,message,bad=false)=>{el.textContent=message;el.classList.toggle('courier-error',bad);};
function progressHtml(p){if(!p)return '';return '<section class="courier-progress"><h3>快递到仓 / 택배 도착 <span>'+p.received+' / '+p.total+'</span></h3><div class="courier-table-scroll"><table><thead><tr><th>快递单号 / 송장번호</th><th>所属 / 소속</th><th>入仓时间 / 도착 시간</th><th>扫描人 / 스캔 담당</th></tr></thead><tbody>'+p.items.map(x=>'<tr><td>'+esc(x.tracking_no)+'</td><td>'+esc(label(x.owner))+'</td><td>'+esc(x.received_at?time(x.received_at):'未到仓 / 미도착')+'</td><td>'+esc(x.scanner_name||'—')+'</td></tr>').join('')+'</tbody></table></div></section>';}
async function detail(id,refresh,inlineHost,onClose){
 const r=await api('detail',{id}),x=r.item,d=document.createElement(inlineHost?'section':'dialog');d.className='courier-dialog'+(inlineHost?' courier-inline-editor':'');
 d.innerHTML='<form method="dialog" class="courier-dialog-head"><h3>'+esc(x.tracking_no)+'</h3><button aria-label="关闭 / 닫기">×</button></form><p>批次 / 차수：'+esc(x.batch_no||'历史无批次 / 과거 차수 없음')+'<br>入仓 / 도착：'+esc(time(x.received_at))+'<br>扫描人 / 스캔 담당：'+esc(x.scanner_name)+'</p><label>快递单号 / 송장번호<input name="tracking" maxlength="80" autocomplete="off" value="'+esc(x.tracking_no)+'"></label><label>所属 / 소속<select name="owner">'+options()+'</select></label><label>接收人 / 인수자<input name="recipient" maxlength="100" value="'+esc(x.handed_to)+'"></label><label>备注（选填） / 비고 (선택)<textarea name="note" rows="2" maxlength="300" placeholder="选填 / 선택">'+esc(x.note)+'</textarea></label><p class="courier-feedback" role="status"></p><div class="courier-actions"><button data-save class="btn btn-outline">保存更正 / 수정 저장</button><button data-handoff class="btn btn-primary">确认交接 / 인계 완료</button></div><details><summary>操作记录 / 변경 이력（'+r.events.length+'）</summary>'+r.events.map(e=>{let v={};try{v=JSON.parse(e.detail);}catch{}return '<p>'+esc(time(e.created_at))+' '+esc(e.actor_name)+'<br>'+esc(e.kind==='receive'?'收货 / 수령':(v.before?.tracking_no&&v.before.tracking_no!==v.after?.tracking_no?v.before.tracking_no+' → '+v.after.tracking_no+' · ':'')+label(v.before?.owner)+' → '+label(v.after?.owner)+' · '+status(v.after?.status)+(v.after?.handed_to?' · '+v.after.handed_to:'')+(v.note?' · '+v.note:''))+'</p>';}).join('')+'</details>';
 let selectedOwner=x.owner;const ownerSelect=d.querySelector('[name=owner]'),ownerButtons=document.createElement('div');ownerButtons.className='courier-owner-buttons';ownerButtons.innerHTML=owners.map(o=>'<button type="button" data-owner="'+o[0]+'" aria-pressed="'+(o[0]===selectedOwner)+'">'+esc(o[1])+'</button>').join('');const ownerField=document.createElement('fieldset');ownerField.style.cssText='border:0;padding:0;margin:12px 0';ownerField.innerHTML='<legend>所属 / 소속</legend>';ownerSelect.parentElement.replaceWith(ownerField);ownerField.append(ownerButtons);ownerButtons.querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedOwner=b.dataset.owner;ownerButtons.querySelectorAll('button').forEach(o=>o.setAttribute('aria-pressed',String(o===b)));});d.querySelector('[data-handoff]').disabled=x.status==='handed_over';if(inlineHost){inlineHost.closest('ul').querySelectorAll('.courier-inline-editor').forEach(x=>x.remove());inlineHost.append(d);d.querySelector('[name=note]').closest('label').remove();d.querySelector('[name=recipient]').closest('label').style.display='none';d.querySelector('[data-handoff]').style.display='none';d.close=()=>{d.remove();onClose?.();};d.querySelector('.courier-dialog-head').onsubmit=e=>{e.preventDefault();d.close();};}else{document.body.append(d);d.showModal();d.addEventListener('close',()=>d.remove());}
 const save=async handed=>{const buttons=d.querySelectorAll('.courier-actions button');buttons.forEach(b=>b.disabled=true);try{const updated=await api('update',{id:x.id,version:x.version,tracking_no:d.querySelector('[name=tracking]').value,owner:selectedOwner,handed_to:d.querySelector('[name=recipient]').value,note:d.querySelector('[name=note]')?.value,status:handed?'handed_over':x.status});d.close();await refresh(updated.item);}catch(e){alertText(d.querySelector('[role=status]'),e.message,true);buttons.forEach(b=>b.disabled=false);d.querySelector('[data-handoff]').disabled=x.status==='handed_over';}};
 d.querySelector('[data-save]').onclick=()=>save(false);d.querySelector('[data-handoff]').onclick=()=>save(true);
}
function batchStatus(x){return x.status==='completed'?'已完成 / 완료':'进行中 / 진행 중';}
function countsHtml(x){return '<b>'+esc(x.batch_no)+' · '+x.total+' 件 / 건</b><p>'+owners.map(o=>esc(o[1])+' '+(x.counts[o[0]]||0)).join(' · ')+'</p>';}
async function batchDetail(id,history=false,filters={}){
 const d=document.createElement('dialog');d.className='courier-dialog courier-office';d.innerHTML='<form method="dialog" class="courier-dialog-head"><h3></h3><button aria-label="关闭 / 닫기">×</button></form><div data-summary></div><p data-query></p><button data-all class="courier-link" hidden>查看本批全部 / 차수 전체 보기</button><p role="status"></p><div class="courier-table-scroll"><table><thead><tr><th>运单 / 송장</th><th>所属 / 소속</th><th>扫描人 / 담당자</th><th>时间 / 시간</th><th></th></tr></thead><tbody></tbody></table></div><div class="courier-pager"><span></span><button data-prev>上一页 / 이전</button><button data-next>下一页 / 다음</button></div>';document.body.append(d);d.showModal();d.onclose=()=>d.remove();let offset=0,matching=Boolean(filters.keyword);
 const load=async()=>{try{let batch;if(!history){batch=(await api('detail',{batch_id:id})).batch;d.querySelector('[data-summary]').innerHTML=countsHtml(batch)+'<p>'+esc(batchStatus(batch))+' · '+esc(batch.owner)+'<br>'+esc(batch.segments.map(w=>w.name).filter((v,i,a)=>a.indexOf(v)===i).join('、'))+'</p>';}
 d.querySelector('h3').textContent=history?'历史收货（无批次） / 과거 수령 (차수 없음)':batch.batch_no;
 const r=await api('list',{...(history?{...filters,history:true}:{batch_id:id,...(matching?{keyword:filters.keyword,owner:filters.owner,status:filters.status}:{})}),limit:50,offset});const keyword=String(filters.keyword||'').trim().toUpperCase().replace(/[ -]/g,'');d.querySelector('tbody').innerHTML=r.items.map(x=>'<tr><td>'+(keyword&&x.tracking_no.toUpperCase().replace(/[ -]/g,'').includes(keyword)?'<mark class="courier-match">'+esc(x.tracking_no)+'</mark>':esc(x.tracking_no))+'</td><td>'+esc(label(x.owner))+'</td><td>'+esc(x.scanner_name)+'</td><td>'+esc(time(x.received_at))+'</td><td><button class="courier-link" data-detail="'+esc(x.id)+'">明细 / 상세</button></td></tr>').join('')||'<tr><td colspan="5" class="courier-empty">没有匹配运单 / 일치하는 송장 없음</td></tr>';d.querySelector('[data-query]').textContent=keyword?((history||matching?'匹配运单 / 일치 송장: ':'本批全部；查询运单 / 차수 전체·검색 송장: ')+filters.keyword):'';d.querySelector('[data-all]').hidden=history||!keyword;d.querySelector('[data-all]').textContent=matching?'查看本批全部 / 차수 전체 보기':'仅看匹配运单 / 일치 송장만 보기';d.querySelector('.courier-pager span').textContent=(matching?'匹配 / 일치 ':'')+r.total+' 件 / 건 · '+(Math.floor(offset/50)+1);d.querySelector('[data-prev]').disabled=!offset;d.querySelector('[data-next]').disabled=offset+50>=r.total;d.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail,load).catch(e=>alertText(d.querySelector('[role=status]'),e.message,true)));}catch(e){alertText(d.querySelector('[role=status]'),e.message,true);}};
 d.querySelector('[data-all]').onclick=()=>{matching=!matching;offset=0;load();};d.querySelector('[data-prev]').onclick=()=>{offset=Math.max(0,offset-50);load();};d.querySelector('[data-next]').onclick=()=>{offset+=50;load();};await load();
}
function office(host){
 let offset=0,seq=0;host.classList.add('courier-office');
 host.innerHTML='<div class="courier-section-head"><h2>到仓快递 / 도착 택배</h2><button data-history class="courier-link">历史无批次 / 과거 차수 없음</button></div><form class="courier-filters"><label>所属 / 소속<select name="owner">'+options(true)+'</select></label><label>快递单号 / 송장번호<input name="keyword" type="search" placeholder="输入全部或部分单号 / 번호 검색"></label><label>批次日期 / 차수 날짜<input name="from" type="date" value="'+today()+'"></label><label>至 / 종료일<input name="to" type="date" value="'+today()+'"></label><label>交接 / 인계<select name="status"><option value="">全部 / 전체</option><option value="received">待交接 / 대기</option><option value="handed_over">已交接 / 완료</option></select></label><button class="btn btn-primary">查询 / 검색</button><button type="button" data-clear class="btn btn-outline">清空筛选 / 필터 초기화</button></form><p class="courier-feedback" role="status"></p><div class="courier-table-scroll"><table><thead><tr><th>扫描批次 / 스캔 차수</th><th>总件数 / 수량</th><th>派工人 / 배정 담당</th><th>开始 / 시작</th><th>状态 / 상태</th><th></th></tr></thead><tbody></tbody></table></div><div class="courier-pager"><span></span><button data-prev>上一页 / 이전</button><button data-next>下一页 / 다음</button></div>';
 const form=host.querySelector('form'),feedback=host.querySelector('[role=status]');
 const load=async()=>{const current=++seq;try{const filters=Object.fromEntries(new FormData(form)),r=await api('list',{...filters,mode:'batches',offset,limit:50});if(seq!==current)return;host.querySelector('tbody').innerHTML=r.items.map(x=>'<tr'+(filters.keyword?' class="courier-matched-batch"':'')+'><td>'+esc(x.batch_no)+'</td><td>'+x.total+'</td><td>'+esc(x.owner)+'</td><td>'+esc(time(x.created_at))+'</td><td>'+esc(batchStatus(x))+'</td><td><button class="courier-link" data-batch="'+esc(x.id)+'">'+(filters.keyword?'匹配运单 / 일치 송장':'明细 / 상세')+'</button></td></tr>').join('')||'<tr><td colspan="6" class="courier-empty">'+(filters.keyword?'没有匹配批次 / 일치 차수 없음':'暂无批次 / 차수 없음')+'</td></tr>';host.querySelector('.courier-pager span').textContent=r.total+' 批 / 차수 · '+(Math.floor(offset/50)+1);host.querySelector('[data-prev]').disabled=!offset;host.querySelector('[data-next]').disabled=offset+50>=r.total;host.querySelectorAll('[data-batch]').forEach(b=>b.onclick=()=>batchDetail(b.dataset.batch,false,filters));
 let oldTotal=0;if(filters.keyword){const old=await api('list',{...filters,from:'',to:'',history:true});if(seq!==current)return;oldTotal=old.total;alertText(feedback,r.total||oldTotal?'查询运单 / 검색 송장: '+filters.keyword+'\n匹配 '+r.total+' 批 / 일치 '+r.total+' 차수'+(oldTotal?'；另有 '+oldTotal+' 件历史无批次，点击上方历史查询 / 과거 '+oldTotal+'건·상단 과거 조회':''):'未找到该运单（批次或历史） / 송장 조회 결과 없음');}else alertText(feedback,'');host.querySelector('[data-history]').textContent='历史无批次 / 과거 차수 없음'+(oldTotal?'（'+oldTotal+' 件 / 건）':'');}catch(e){if(seq===current)alertText(feedback,e.message,true);}};
 form.onsubmit=e=>{e.preventDefault();offset=0;load();};form.elements.keyword.oninput=()=>{if(form.elements.keyword.value.trim()){form.elements.from.value='';form.elements.to.value='';}else{form.elements.from.value=form.elements.from.defaultValue;form.elements.to.value=form.elements.to.defaultValue;offset=0;load();}};host.querySelector('[data-clear]').onclick=()=>{form.reset();offset=0;load();};
 host.querySelector('[data-history]').onclick=()=>batchDetail('',true,Object.fromEntries(new FormData(form)));host.querySelector('[data-prev]').onclick=()=>{offset=Math.max(0,offset-50);load();};host.querySelector('[data-next]').onclick=()=>{offset+=50;load();};load();
 const params=new URLSearchParams(location.search);if(params.get('batch'))batchDetail(params.get('batch'));if(params.get('receipt'))detail(params.get('receipt'),load).catch(e=>alertText(feedback,e.message,true));
}
function field(host){
 let owner='',busy=false,camera=null,batch=null,scannerBadge='',timer=null,visible=false,generation=0,picker=null,peopleDialog=null,finishIntent=null,lastCamera='',lastCameraAt=0,editing=false;
 const intentKey='ck-courier-start:'+CKSession.user.id,scanKey='ck-courier-scan:'+CKSession.user.id;
 const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'null');}catch{return null;}};
 const feedback=()=>host.querySelector('[data-feedback]');
 const message=(m,bad=false)=>{if(feedback())alertText(feedback(),m,bad);};
 async function stopCamera(){if(camera){const c=camera;camera=null;await c.stop().catch(()=>{});await c.clear().catch(()=>{});}host.querySelector('#courierCamera')?.setAttribute('hidden','');}
 async function stop(){visible=false;generation++;clearInterval(timer);timer=null;await stopCamera();await peopleDialog?.close(null);peopleDialog=null;await picker?.destroy();picker=null;}
 async function finishedHome(token){if(token!==generation||!visible||batch?.status!=='completed')return;await stop();owner='';scannerBadge='';finishIntent=null;batch=null;busy=false;editing=false;host.replaceChildren();window._navStack=[];window._pageParams={};window.CKClearNativeJob?.();const url=new URL(location.href);if(url.searchParams.get('tab')==='courier'){url.searchParams.delete('tab');history.replaceState(history.state,'',url.pathname+url.search+url.hash);}window.showPage('home');}
 function enable(){const can=batch&&batch.status==='working'&&scannerBadge&&owner&&!busy&&!editing;host.querySelectorAll('[data-scan] input,[data-scan] button').forEach(x=>x.disabled=!can);host.querySelectorAll('[data-owner]').forEach(x=>x.disabled=busy||editing||!scannerBadge||batch?.status!=='working');host.querySelectorAll('[data-finish],[data-people],[data-person]').forEach(x=>x.disabled=busy||editing||batch?.status==='completed');}
 function paintCounts(){host.querySelector('[data-batch-title]').textContent=batch.batch_no+' · '+batchStatus(batch);host.querySelector('[data-total]').textContent='本批 '+batch.total+' 件 / '+batch.total+'건';for(const b of host.querySelectorAll('[data-owner]'))b.querySelector('small').textContent=(batch.counts[b.dataset.owner]||0)+' 件 / 건';host.querySelector('[data-crew]').textContent='当前人员 / 현재 인원: '+(batch.workers.map(w=>w.name).join('、')||'暂无 / 없음');}
 async function refresh(token=generation){if(!visible||!batch||busy||editing)return;try{const r=await api('detail',{batch_id:batch.id});if(token!==generation||!visible||busy||editing)return;batch=r.batch;if(batch.status==='completed'&&finishIntent?.batch_id===batch.id){await finishedHome(token);return;}paintCounts();enable();if(!batch.workers.some(w=>w.id===scannerBadge)){scannerBadge='';host.querySelector('[data-scanner]').textContent='请扫描工牌 / 명찰을 스캔하세요';enable();}if(batch.status==='completed'){clearInterval(timer);timer=null;await stopCamera();message('本批已由其他操作端完成，扫码已停止。请返回现场首页 / 다른 화면에서 차수 완료·스캔 중지. 현장 홈으로 돌아가세요.',true);}}catch(e){if(token===generation){message('同步失败，请重试 / 동기화 실패: '+e.message,true);}}}
 async function badgeGate(){await stopCamera();scannerBadge='';enable();const d=document.createElement('dialog');d.className='ck-workflow courier-dispatch';d.innerHTML='<form><h2>扫描本批操作员工牌 / 작업자 명찰</h2><label>工牌 / 명찰<input name="badge" autocomplete="off" required placeholder="工号|姓名 / 사번|이름"></label><p role="status"></p><div class="ck-buttons"><button>确认 / 확인</button><button type="button" class="light" data-cancel>取消 / 취소</button></div></form>';document.body.append(d);d.showModal();d.onclose=()=>d.remove();d.querySelector('[data-cancel]').onclick=()=>d.close();d.querySelector('input').focus();d.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=d.querySelector('form button');if(button.disabled)return;button.disabled=true;try{const parts=d.querySelector('input').value.trim().split('|'),r=await api('detail',{batch_id:batch.id});batch=r.batch;const w=batch.workers.find(x=>x.id===parts[0]&&x.name===parts[1]);if(!w||batch.status!=='working')throw Error('工牌不在本批或本批已结束 / 차수·명찰을 확인하세요');await api('config',{operation:'scanner',batch_id:batch.id,badge:w.id+'|'+w.name});scannerBadge=w.id;host.querySelector('[data-scanner]').textContent=w.name;paintCounts();enable();d.close();host.querySelector('[name=tracking]').focus();}catch(x){d.querySelector('[role=status]').textContent=x.message;}finally{button.disabled=false;}};}
 async function chooseStaff(adjust=false){
  if(peopleDialog)return;await stopCamera();clearInterval(timer);const token=generation;let pending=null;
  const component=CKNativePeopleDialog({className:'courier-dispatch',title:adjust?'调整本批人员 / 차수 인원 변경':'负责人分配快递收货人员 / 택배 수령 인원 배정',description:adjust?'新增人员从保存时加入，移除只结束本人参与。 / 추가 인원은 저장 시 시작, 삭제 인원만 종료합니다.':'扫描实际操作人员工牌，选择主操作员后开始本批。 / 실제 작업자 명찰을 스캔하고 주 작업자를 선택하세요.',workers:adjust?batch.workers:[],leadId:adjust?batch.lead_id:'',allowEmpty:adjust,disableUntilValid:true,cancelLight:true,cancelLabel:'取消 / 취소',submitLabel:adjust?'保存人员 / 인원 저장':'确认人员并开始 / 인원 확인·시작',onSubmit:async staff=>{const body={operation:adjust?'people':'start',...staff,...(adjust?{batch_id:batch.id,revision:batch.revision}:{})},fingerprint=JSON.stringify(body);let prior=adjust?pending:read(intentKey);if(!prior||prior.fingerprint!==fingerprint){prior={fingerprint,body:{...body,client_req_id:crypto.randomUUID()}};if(adjust)pending=prior;else localStorage.setItem(intentKey,JSON.stringify(prior));}const r=await api('receive',prior.body);if(!adjust)localStorage.removeItem(intentKey);return {batch:r.batch,staff};}});
  peopleDialog=component;picker=component.picker;const result=await component.promise;if(peopleDialog===component){peopleDialog=null;picker=null;}if(token!==generation||!visible)return;if(visible&&batch)timer=setInterval(()=>refresh(),5000);if(!result)return;batch=result.batch;await render();if(!adjust){scannerBadge=result.staff.lead_id;host.querySelector('[data-scanner]').textContent=result.staff.workers.find(w=>w.id===scannerBadge).name;enable();}else await badgeGate();
 }
 async function render(){
  const token=generation;host.className='courier-field';host.innerHTML='<h2>快递收货 / 택배 수령</h2><h3 data-batch-title></h3><p data-crew></p><p>扫描人 / 스캔 담당: <strong data-scanner>请扫描工牌 / 명찰을 스캔하세요</strong> <button class="courier-link" data-person>扫描工牌 / 명찰</button></p><div class="courier-actions"><button class="btn btn-outline" data-people>调整人员 / 인원 변경</button><button class="btn btn-primary" data-finish>完成本批 / 차수 완료</button></div><fieldset><legend>本批所属件数 / 차수 소속별 수량</legend><div class="courier-owner-buttons">'+owners.map(o=>'<button type="button" data-owner="'+o[0]+'" aria-pressed="false">'+esc(o[1])+'<small>0 件 / 건</small></button>').join('')+'</div></fieldset><form data-scan class="courier-scan-form"><label for="courierScanInput">快递单号 / 송장번호</label><div class="courier-scan-row"><input id="courierScanInput" name="tracking" autocomplete="off" disabled><button class="btn btn-primary" type="submit" disabled>收货 / 수령</button></div><div class="courier-actions"><button class="btn btn-outline" type="button" data-camera disabled>相机扫码 / 카메라</button><span data-total></span></div></form><div id="courierCamera" hidden></div><p class="courier-feedback" data-feedback role="status"></p><div class="courier-recent"><h3>本批最近收货 / 차수 최근 수령</h3><ul></ul></div>';
  owner='';scannerBadge='';finishIntent=null;paintCounts();enable();const input=host.querySelector('[name=tracking]');
  const loadRecent=async()=>{const r=await api('list',{batch_id:batch.id,limit:8});if(token!==generation)return;host.querySelector('ul').innerHTML=r.items.map(x=>'<li><div><b>'+esc(x.tracking_no)+'</b><small>'+esc(label(x.owner))+' · '+esc(x.scanner_name)+'</small></div><button class="courier-link" data-recent="'+esc(x.id)+'">修改 / 수정</button></li>').join('');host.querySelectorAll('[data-recent]').forEach(b=>b.onclick=async()=>{await stopCamera();editing=true;enable();try{await detail(b.dataset.recent,async()=>{editing=false;await refresh();await loadRecent();},b.closest('li'),()=>{editing=false;enable();});}catch(e){editing=false;enable();message(e.message,true);}});};
  host.querySelectorAll('[data-owner]').forEach(b=>b.onclick=()=>{owner=b.dataset.owner;host.querySelectorAll('[data-owner]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));enable();input.focus();});
  host.querySelector('[data-person]').onclick=badgeGate;host.querySelector('[data-people]').onclick=()=>chooseStaff(true);
  host.querySelector('[data-finish]').onclick=async()=>{if(busy||batch.status==='completed')return;if(!confirm('确认完成本批 '+batch.batch_no+'？全部参与人员结束本批计时。\n차수 완료 및 참여 인원 작업시간 종료를 확인하세요.'))return;busy=true;enable();await stopCamera();try{if(!finishIntent||finishIntent.revision!==batch.revision)finishIntent={operation:'finish',batch_id:batch.id,revision:batch.revision,client_req_id:crypto.randomUUID()};const r=await api('receive',finishIntent);if(token!==generation||!visible)return;batch=r.batch;await finishedHome(token);}catch(e){if(token!==generation||!visible)return;message(e.message+'\n完成未确认，核对后再返回 / 완료 확인 후 홈으로 이동합니다.',true);if(!e.businessError)try{const r=await api('detail',{batch_id:finishIntent.batch_id});if(token===generation&&visible){batch=r.batch;if(batch.status==='completed')await finishedHome(token);}}catch{}}finally{busy=false;if(token===generation&&visible)enable();}};
  const receive=async raw=>{if(busy||editing)return;if(!owner||!scannerBadge)return;let code;try{code=rules.trackingNumber(raw);}catch(e){message(e.message,true);return;}let pending=read(scanKey);if(pending&&pending.batch_id===batch.id&&(pending.tracking_no!==code||pending.owner!==owner||pending.scanner_badge!==scannerBadge)){message('上次保存结果未核实，请先重试原运单 / 이전 송장 저장을 먼저 확인하세요',true);return;}
   const body={owner,tracking_no:code,scanner_badge:scannerBadge,batch_id:batch.id};localStorage.setItem(scanKey,JSON.stringify(body));busy=true;enable();try{const r=await api('receive',body);localStorage.removeItem(scanKey);if(token!==generation)return;batch=r.batch;paintCounts();const x=r.item;let text=(r.duplicate?'已收过，不重复计件 / 이미 수령':'收货成功 / 수령 완료')+'\n'+x.tracking_no+' · '+label(x.owner)+'\n原批次 / 기존 차수: '+(x.batch_no||'历史无批次 / 과거 차수 없음')+'\n'+time(x.received_at)+' · '+x.scanner_name;if(r.owner_conflict)text+='\n此前所属不同，请在原明细核实 / 기존 소속 확인';if(r.plan)text+='\n'+r.plan.display_no+' · '+r.plan.progress.received+'/'+r.plan.progress.total;message(text,r.owner_conflict);input.value='';await loadRecent();}catch(e){if(e.businessError)localStorage.removeItem(scanKey);if(token===generation)message(e.message+(e.businessError?'':'\n请重试原运单 / 같은 송장을 다시 스캔하세요'),true);}finally{busy=false;if(token===generation){enable();input.focus();}}};
  host.querySelector('[data-scan]').onsubmit=e=>{e.preventDefault();receive(input.value);};
  host.querySelector('[data-camera]').onclick=async()=>{if(camera)return stopCamera();try{host.querySelector('#courierCamera').hidden=false;camera=new Html5Qrcode('courierCamera',{formatsToSupport:[Html5QrcodeSupportedFormats.CODE_128,Html5QrcodeSupportedFormats.CODE_39,Html5QrcodeSupportedFormats.ITF,Html5QrcodeSupportedFormats.CODABAR],verbose:false});await camera.start({facingMode:'environment'},{fps:10,qrbox:{width:260,height:100}},raw=>{if(busy||raw===lastCamera&&Date.now()-lastCameraAt<4000)return;lastCamera=raw;lastCameraAt=Date.now();input.value=raw;receive(raw);},()=>{});}catch(e){await stopCamera();message('无法打开相机，请使用扫码枪 / 스캐너를 사용하세요',true);}};
  const pending=read(scanKey);if(pending?.batch_id===batch.id){owner=pending.owner;input.value=pending.tracking_no;host.querySelector('[data-owner="'+owner+'"]').setAttribute('aria-pressed','true');message('上次保存结果未核实，请扫工牌后重试原单 / 명찰 확인 후 이전 송장 재시도');}
  await loadRecent();clearInterval(timer);timer=setInterval(()=>refresh(),5000);
 }
 async function open(id){await stop();visible=true;batch=null;const token=generation;host.className='courier-field';host.innerHTML='<h2>快递收货 / 택배 수령</h2><p data-feedback role="status">读取批次 / 차수 조회</p>';try{if(id){batch=(await api('detail',{batch_id:id})).batch;if(token!==generation)return;if(batch.status==='completed'){await finishedHome(token);return;}await render();await badgeGate();return;}const r=await api('config',{operation:'batches'});if(token!==generation)return;host.innerHTML='<h2>快递收货 / 택배 수령</h2><p>一次派工一个批次。继续原批请先扫本批工牌。<br>배정마다 차수 생성. 기존 차수는 명찰 확인 후 계속하세요.</p><button data-new class="btn btn-primary">扫描工牌并派工 / 명찰 스캔·배정</button><div data-active></div><p data-feedback class="courier-feedback" role="status"></p>';host.querySelector('[data-new]').onclick=()=>chooseStaff();for(const x of r.items){const b=document.createElement('button');b.className='btn btn-outline';b.textContent=x.batch_no+' · '+x.total+'件 · 继续 / 계속';b.onclick=()=>open(x.id);host.querySelector('[data-active]').append(b);}const pending=read(intentKey);if(pending){const b=document.createElement('button');b.textContent='核对上次派工 / 이전 배정 확인';b.onclick=async()=>{b.disabled=true;try{const r=await api('receive',pending.body);localStorage.removeItem(intentKey);await open(r.batch.id);}catch(e){message(e.message,true);b.disabled=false;}};host.querySelector('[data-active]').prepend(b);}if(!r.items.length&&!pending)await chooseStaff();}catch(e){message(e.message,true);}}
 return {open,stop};
}
function installPlanFields(){
 const enhance=tr=>{const select=tr.querySelector('.ibc-line-type');if(!select||select.dataset.courier)return;select.dataset.courier='1';select.add(new Option('快递 / 택배','courier'));
 const wrap=document.createElement('label');wrap.className='courier-plan-numbers';wrap.hidden=true;wrap.innerHTML='快递单号 / 송장번호<textarea rows="3" maxlength="6000" placeholder="每行一个单号 / 한 줄에 한 번호"></textarea><small>数量按不同单号自动计算 / 송장별 수량 자동 계산</small>';tr.querySelector('td').append(wrap);
 const qty=tr.querySelector('.ibc-line-qty');select.addEventListener('change',()=>{const yes=select.value==='courier';wrap.hidden=!yes;qty.readOnly=yes;if(yes){qty.value='0';wrap.querySelector('textarea').focus();}});wrap.querySelector('textarea').oninput=()=>{try{qty.value=rules.trackingNumbers(wrap.querySelector('textarea').value).length;}catch{qty.value='0';}};
 };
 const add=window.addIbcLine;window.addIbcLine=function(...args){add(...args);document.querySelectorAll('#ibcLinesBody tr').forEach(enhance);};document.querySelectorAll('#ibcLinesBody tr').forEach(enhance);
 const read=window.getIbcLines;window.getIbcLines=function(){const old=read().filter(x=>x.unit_type!=='courier');let count=0;for(const tr of document.querySelectorAll('#ibcLinesBody tr'))if(tr.querySelector('select').value==='courier'){count++;const codes=rules.trackingNumbers(tr.querySelector('textarea').value);if(!codes.length)throw Error('选择快递后请填写快递单号 / 송장번호를 입력하세요');old.push({unit_type:'courier',planned_qty:codes.length,tracking_nos:codes,remark:tr.querySelector('.ibc-line-remark').value.trim()});}if(count>1)throw Error('请把快递单号填写在同一行 / 한 행에 입력하세요');return old;};
 const submit=window.submitInbound;window.submitInbound=async function(...args){try{getIbcLines();return await submit(...args);}catch(e){alert(e.message);}};
 const unit=window.unitTypeLabel;window.unitTypeLabel=value=>value==='courier'?'快递 / 택배':unit(value);
 const load=window.loadInboundDetail;window.loadInboundDetail=async function(...args){await load(...args);const p=window._currentInboundPlan;if(p?.courier_progress){document.getElementById('inboundDetailBody').insertAdjacentHTML('afterbegin',progressHtml(p.courier_progress));}};
 const edit=window.openInboundEditForm;window.openInboundEditForm=function(...args){edit(...args);const progress=window._currentInboundPlan?.courier_progress,box=document.querySelector('#ibEditOverlay .modal-box');if(progress&&box){const field=document.createElement('label');field.className='courier-plan-numbers';field.innerHTML='快递单号 / 송장번호<textarea id="courierEditCodes" rows="4">'+esc(progress.items.map(x=>x.tracking_no).join('\n'))+'</textarea>';box.querySelector('div').after(field);if(progress.received)field.querySelector('textarea').readOnly=true;}};
 const originalApi=window.api;window.api=async function(body){if(body.action==='v2_inbound_plan_update'&&document.getElementById('courierEditCodes')){try{const codes=rules.trackingNumbers(document.getElementById('courierEditCodes').value);if(!codes.length)throw Error('快递单号不能为空');body.lines=window._currentInboundLines.map(x=>x.unit_type==='courier'?{...x,tracking_nos:codes,planned_qty:codes.length}:x);}catch(e){return {ok:false,error:e.message};}}return originalApi(body);};
}
window.CKInstallCourier=async function(app){
 if(!window.CK_SOP_ROLLOUT?.staging||!['001','002'].includes(app))return;
 rules=await import('/shared/courier-rules.js');owners=rules.courierOwners;
 if(app==='002'){
  installPlanFields();LANG.zh.tab_courier='到仓快递';LANG.ko.tab_courier='도착 택배';const tabs=document.getElementById('mainTabs'),b=document.createElement('button');b.type='button';b.dataset.tab='courier';b.dataset.i18n='tab_courier';b.textContent=L('tab_courier');tabs.append(b);
  const view=document.createElement('div');view.id='view-courier';view.className='view';view.style.display='none';document.getElementById('page-main').append(view);b.onclick=()=>{goView('courier');tabs.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));office(view);};
  if(new URLSearchParams(location.search).get('tab')==='courier')b.click();
  }else{
  const oldUnit=window.unitLabel;window.unitLabel=value=>value==='courier'?'快递 / 택배':oldUnit(value);
  const page=document.createElement('div');page.id='page-courier';page.className='page';page.innerHTML='<div class="topbar"><button class="back-btn">← 返回 / 뒤로</button></div><div data-courier-host></div>';document.body.append(page);page.querySelector('button').onclick=()=>goPage('home');let instance;
  const b=document.createElement('button');b.type='button';b.className='home-btn';b.innerHTML='<div class="icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 10V7l-9-4-9 4v11l9 4 M3 7l9 4 9-4 M12 11v11 M7.5 5l9 4 M16 17l2 2 4-4"/></svg></div><div class="label">快递收货</div><div class="label-ko">택배 수령</div>';const openBatch=id=>{showPage('courier');if(!instance)instance=field(page.querySelector('[data-courier-host]'));return instance.open(id);};b.onclick=()=>openBatch();window.CKOpenCourierBatch=openBatch;document.querySelector('#page-home .home-grid').append(b);
  const show=window.showPage;window.showPage=function(name,...args){if(name!=='courier')instance?.stop();return show(name,...args);};if(new URLSearchParams(location.search).get('tab')==='courier')b.click();
 }
};
})();
