/* One requirement -> scan staff -> inspect, record output and close. */
(function(){'use strict';const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const states={pending:'待派工 / 배정 대기',assigned:'已安排 / 배정 완료',working:'作业中 / 작업 중',paused:'已暂停 / 일시 중지',rework:'待整改 / 재작업',awaiting_review:'待审核 / 검수 대기',completed:'已完成 / 완료',waiting_customer:'等待客户安排',linked:'成果已关联出库',cancelled:'已取消'};
window.CKFieldWork=function(root,initial=''){
 root.className='ck-bulk';let picker=null,scan=null,current=null,closed=false,loadSequence=0,requestId='',requestSignature='';const api=(a,d={})=>CKSession.request(a,d),$=s=>root.querySelector('[data-'+s+']');
 async function cleanup(){if(picker){await picker.destroy();picker=null;}if(scan){const s=scan;scan=null;await s.stop().catch(()=>{});}}
 function error(x){if($('error')){$('error').textContent=x.message;$('error').hidden=false;}}
 async function write(action,data){const signature=JSON.stringify({action,data});if(signature!==requestSignature||!requestId){requestSignature=signature;requestId=crypto.randomUUID();}try{const r=await api(action,{...data,client_req_id:requestId});requestId='';return r;}catch(x){if(x.businessError)requestId='';throw x;}}
 async function resolve(code){const sequence=++loadSequence;await cleanup();if(closed||sequence!==loadSequence)return;const next=await api('sop_field_resolve',{code});if(closed||sequence!==loadSequence)return;current=next;draw();}
 async function home(){const sequence=++loadSequence;await cleanup();if(closed||sequence!==loadSequence)return;current=null;root.innerHTML=`<section class="ck-scan"><span class="ck-step">01 / SCAN WORK ORDER</span><h2>扫描作业计划单</h2><p>작업 계획서를 스캔하세요.</p><form data-scanform><label for="ck-work-code">作业单号 / 작업 번호</label><div class="ck-scan-row"><input id="ck-work-code" data-code autocomplete="off" placeholder="扫码枪扫描或输入编号" required><button class="ck-primary" style="width:auto;margin:0" type="submit">打开</button></div></form><div class="ck-actions" style="margin-top:14px"><button data-camera class="ck-small">相机扫码 / 카메라</button></div><div id="ck-work-camera"></div><p data-error class="ck-error" role="alert" hidden></p></section><section><div class="ck-section-heading"><h3>进行中的作业 / 진행 중</h3><button class="ck-small" data-refresh>刷新</button></div><div data-tasks>正在读取…</div></section>`;
  $('scanform').onsubmit=async ev=>{ev.preventDefault();const b=ev.submitter;if(b)b.disabled=true;try{await resolve($('code').value.trim());}catch(x){error(x);}finally{if(b)b.disabled=false;}};$('refresh').onclick=loadTasks;$('camera').onclick=async()=>{if(scan){await cleanup();$('camera').textContent='相机扫码 / 카메라';return;}try{scan=new Html5Qrcode('ck-work-camera');let reading=false;await scan.start({facingMode:'environment'},{fps:8,qrbox:220},async code=>{if(reading)return;reading=true;try{await resolve(code);}catch(x){error(x);reading=false;}},()=>{});$('camera').textContent='停止扫码 / 스캔 중지';}catch(x){error(Error('无法打开相机，请使用扫码枪或输入编号 / 카메라 사용 불가'));}};$('code').focus();await loadTasks();
 }
 async function loadTasks(){try{let items=[],offset=0,more=true;while(more){const r=await api('sop_list',{kind:'task',offset});items.push(...r.items);more=r.more;offset+=50;if(offset>=1000)break;}if(!$('tasks'))return;items=items.filter(t=>t.department==='bulk'&&!['completed','cancelled'].includes(t.status));$('tasks').innerHTML=items.map(t=>`<button class="ck-task-link" data-task="${e(t.id)}"><b class="ck-task-number">${e(t.work_plan_no||t.display_no||'单号待补充')}</b><span class="ck-task-customer">客户 / 고객：${e(t.customer||'—')}</span><span class="ck-task-title">${e(t.title)}</span><small>${states[t.status]||e(t.status)} · ${e((t.workers||[]).map(w=>w.name).join('、'))}</small></button>`).join('')||'<p class="ck-muted">暂无进行中的大货作业。扫描订单处理组打印的需求单即可开始。</p>';root.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>resolve(b.dataset.task).catch(error));}catch(x){if($('tasks'))$('tasks').textContent=x.message;}}
 function draw(){const {need:n,task:t,source,segments,changed}=current;const title=n?.title||t?.title||'',state=t?.status||n?.status,live=segments.filter(s=>!s.left_at);root.innerHTML=`<div class="ck-actions"><button data-back class="ck-small">← 扫描其他作业单 / 다른 작업</button><button data-refresh class="ck-small">刷新 / 새로고침</button></div><section class="ck-work-sheet"><span class="ck-state">${states[state]||e(state)}</span><p class="ck-work-number">作业单号 / 작업 번호：<b>${e(n?.display_no||t?.work_plan_no||t?.display_no||'单号待补充')}</b></p><h2>${e(title)}</h2><div class="ck-work-meta"><div>客户 / 고객<b>${e(n?.customer||source?.customer||'—')}</b></div><div>货物来源 / 화물 출처<b>${e(source?.number||window.CKDocumentLabels.source(n))}</b></div><div>货物范围 / 화물 범위<b>${e(n?.scope_text||'见作业要求')}</b></div><div>作业位置 / 작업 위치<b>${e(t?.location||n?.location||'待确认')}</b></div></div><div class="ck-instructions">${e(n?.instructions||title)}</div>${changed?'<p class="ck-warning">纸单版本已更新，请按本页最新要求核对后派工。</p>':''}${source&&!window.CKWorkChain?.enabled()?`<a href="/002/?${n.source_type==='inbound'?'inbound':'need'}=${encodeURIComponent(n.source_type==='inbound'?source.id:n.id)}" target="_blank">查看同批要求 ↗</a>`:''}</section><div data-content></div><p data-error class="ck-error" role="alert" hidden></p>`;$('back').onclick=home;$('refresh').onclick=()=>resolve(t?.id||n.id).catch(error);
  if(n&&window.CKWorkChain?.enabled()){const docs=document.createElement('section');root.querySelector('.ck-work-sheet').append(docs);CKWorkChain.materials(docs,n,{field:true}).catch(error);}
  if(!t&&n?.operation_kind==='direct_forward'&&n.status==='pending'){$('content').innerHTML='<section class="chain-forward"><h3>直接转发 / 작업 없이 전달</h3><p>收货后确认可发货数量，不记录加工工时。</p><form data-forward><label>可发货数量 / 출고 가능 수량<input data-forward-quantity type="number" min="1" step="1" required value="'+e(n.planned_quantity)+'"></label><button>确认可发货 / 출고 준비 확인</button></form></section>';$('forward').onsubmit=async ev=>{ev.preventDefault();ev.submitter.disabled=true;try{await write('sop_need_forward_ready',{id:n.id,revision:n.revision,quantity:Number($('forward-quantity').value)});await resolve(n.id);}catch(x){error(x);ev.submitter.disabled=false;}};return;}
  if(!t&&n?.status==='pending'){people('派工并开始 / 배정 및 시작',[],async staff=>{const r=await write('sop_task_dispatch',{department:n.department,title:n.title,need_id:n.id,job_type:'bulk_op',estimated_minutes:30,location:n.location||'',...staff});await resolve(r.id);});return;}
  if(!t){$('content').innerHTML='<p class="ck-muted">此需求已完成或暂不能派工，请联系订单处理组核对。</p>';return;}
  $('content').innerHTML=`<section class="ck-work-sheet"><span class="ck-step">02 / PEOPLE & EXECUTION</span><h3>参与人员 / 참여 인원</h3><p>${live.length?live.map(w=>e(w.worker_name)).join(' · '):'当前无人计时 / 현재 작업 인원 없음'}</p><p class="ck-muted">${t.started_at?'开始 '+CKAttendance.at(t.started_at):'人员到位后开始记录工时'} · 负责人 ${e(t.owner)}</p><div class="ck-actions" data-actions></div><div data-editor></div></section>`;
  const action=(label,fn)=>{const b=document.createElement('button');b.className='ck-small';b.textContent=label;b.onclick=async()=>{b.disabled=true;try{await fn();}catch(x){error(x);}finally{b.disabled=false;}};$('actions').append(b);};
  if(['assigned','paused','rework'].includes(t.status))action('核对人员并开始 / 인원 확인·시작',()=>people('开始作业 / 작업 시작',t.workers,async staff=>{let rev=t.revision;if(JSON.stringify(staff.workers)!==JSON.stringify(t.workers)||staff.lead_id!==t.lead_id){const x=await write('sop_task_people',{id:t.id,revision:rev,...staff,reason:'开工前核对到位人员'});rev=x.revision;}await write('sop_task_start',{id:t.id,revision:rev});await resolve(t.id);}));
  if(t.status==='working'){
   action('调整人员 / 인원 변경',()=>people('保存人员 / 인원 저장',live.map(w=>({id:w.worker_id,name:w.worker_name})),async staff=>{await write('sop_task_people',{id:t.id,revision:t.revision,...staff,reason:$('reason').value});await resolve(t.id);},true));
   action('登记休息 / 휴식 등록',()=>{window.CKOpenFieldLabor?.();});
   action('暂停作业 / 작업 중지',()=>{const host=$('editor');host.innerHTML='<form data-pause><label>暂停原因 / 중지 사유<textarea name="reason" required></textarea></label><button class="ck-primary">确认暂停 / 중지</button></form>';$('pause').onsubmit=async ev=>{ev.preventDefault();ev.submitter.disabled=true;try{await write('sop_task_pause',{id:t.id,revision:t.revision,reason:new FormData(ev.target).get('reason')});await resolve(t.id);}catch(x){error(x);ev.submitter.disabled=false;}};});
   action('填写产出并审核结束 / 산출·검수 완료',()=>finish(t));
  }else if(t.status==='awaiting_review')action('审核原有产出 / 검수',()=>{const host=$('editor');host.innerHTML=`${CKResultSummary(t.result)}${t.result?.location?`<p>${e(t.result.location)}</p>`:''}${CKResultPhotos(t.result)}<form data-review><label>审核结论<select name="decision"><option value="pass">通过 / 통과</option><option value="return">退回整改 / 재작업</option></select></label><label>审核说明<textarea name="reason" required></textarea></label><button class="ck-primary">保存审核 / 검수 저장</button></form>`;$('review').onsubmit=async ev=>{ev.preventDefault();ev.submitter.disabled=true;try{await write('sop_task_review',{id:t.id,revision:t.revision,...Object.fromEntries(new FormData(ev.target))});await resolve(t.id);}catch(x){error(x);ev.submitter.disabled=false;}};});
  else if(t.status==='completed')$('editor').innerHTML=`<h3>已审核完成 / 검수 완료</h3>${CKResultSummary(t.result)}${CKResultPhotos(t.result)}<p class="ck-muted">成果交回订单处理组继续安排。出库放行仍按出库流程执行。</p>`;
 }
 function people(label,workers,save,adjust=false){if(picker)picker.destroy();const host=$('editor')||$('content');host.innerHTML=`<form data-people class="ck-work-sheet"><span class="ck-step">02 / SCAN STAFF</span><h3>扫描操作员工牌 / 작업자 명찰</h3>${CKPeopleFields()}${adjust?'<label>调整原因 / 변경 사유<input data-reason required></label>':''}<button class="ck-primary" type="submit">${label}</button></form>`;picker=CKPeoplePicker($('people'),{workers,leadId:current.task?.lead_id,error:$('error')});$('people').onsubmit=async ev=>{ev.preventDefault();ev.submitter.disabled=true;try{await save(picker.read());}catch(x){error(x);ev.submitter.disabled=false;}};
 }
 function finish(t){if(picker){picker.destroy();picker=null;}const n=current.need,shipping=current.shipping,unit=shipping?.unit||n?.shipping_basis?.unit||n?.planned_unit||n?.unit||'箱',booked=shipping?.links?.filter(l=>l.phase==='planned')||[],counts=[['packed_sku_count','品数 / 품목수'],['packed_count','打包箱数 / 포장박스'],['used_carton_large_count','大纸箱 / 대형박스'],['used_carton_small_count','小纸箱 / 소형박스'],['repaired_box_count','修补箱数 / 수리박스'],['reboxed_count','换箱数 / 교체박스'],['label_count','标签数 / 라벨수'],['operated_box_count','操作总箱数 / 총 박스'],['pallet_count','打托数 / 팔레트'],['forklift_location_count','叉车货位数 / 지게차 위치']];$('editor').innerHTML=`<form data-finish><h3>审核并记录本次产出 / 검수·산출</h3><p class="ck-muted">核对现场实际完成内容后填写。本次产出整单记录一次，个人工时按参与时段计算。</p><div class="ck-instructions"><p>待操作货量 / 작업 대상: ${e(n?.planned_quantity||'—')} ${e(n?.planned_unit||'')}</p><p>预计可出库成果 / 예상 출고 산출: ${e(shipping?.quantity||n?.planned_quantity||'—')} ${e(unit)}</p>${booked.map(l=>`<p>已预约出库 / 출고 예약: ${e(shipping.orders.find(o=>o.id===l.outbound_id)?.display_no||l.outbound_id)} · <b>${e(l.quantity)} ${e(l.unit)}</b></p>`).join('')}<p>按实际完成的成果填写。打托后按托记录成果，操作总箱数填写实际处理的箱数。 / 실제 산출을 입력하세요. 팔레트 산출과 작업한 박스 수는 별도로 기록합니다.</p></div><div class="ck-counter-grid"><label>实际成果数量 / 실제 완료 수량<input type="number" name="quantity" min="1" step="1" required></label><label>成果单位 / 단위<select name="unit">${['箱','件','托','单','批'].map(u=>`<option ${u===unit?'selected':''}>${u}</option>`).join('')}</select></label></div><details open><summary>操作产出与耗材 / 작업 산출·자재</summary><div class="ck-counter-grid">${counts.map(([k,l])=>`<label>${l}<input name="${k}" type="number" min="0" step="1" value="0"></label>`).join('')}</div></details><label style="display:flex;align-items:center;gap:10px"><input name="used_forklift" type="checkbox" style="width:auto;margin:0">使用叉车 / 지게차 사용</label><label>附加操作（选填）/ 추가 작업 (선택)<textarea name="description" placeholder="产出之外的补充操作 / 추가 작업 내용"></textarea></label><div data-location-photos></div><label>审核说明 / 검수 내용<input name="reason" placeholder="核对数量、包装及货位后的结论" required></label><button class="ck-primary">审核通过并结束任务 / 검수 통과·종료</button></form>`;const photos=CKLocationPhotoPicker($('location-photos'),t);$('finish').onsubmit=async ev=>{ev.preventDefault();ev.submitter.disabled=true;try{const f=Object.fromEntries(new FormData(ev.target)),reason=f.reason;delete f.reason;if(booked.some(l=>l.unit!==f.unit))throw Error('本次成果单位与出库预约不一致，请联系办公室调整出库数量与单位。 / 출고 예약 단위를 확인하세요.');const reserved=booked.reduce((s,l)=>s+Number(l.quantity),0);if(reserved>Number(f.quantity))throw Error('已预约 '+reserved+' '+f.unit+'，本次填写 '+f.quantity+' '+f.unit+'，请核实实际成果或调整预约。 / 예약 수량을 확인하세요.');f.used_forklift=!!f.used_forklift;f.location_photos=await photos.read();await write('sop_task_complete_review',{id:t.id,revision:t.revision,result:f,decision:'pass',reason});await resolve(t.id);}catch(x){error(x);ev.submitter.disabled=false;}};
 }
 (initial?resolve(initial):home()).catch(error);return {destroy(){closed=true;loadSequence++;cleanup();},open:resolve};
};
// One requirement per printed page; the same inbound-plan reference remains visible.
})();
